### ISSUE TITLE
Question: loading TIFF as grayscale in v3

### ISSUE THREAD

**Issue by hermancollin** [imageio/imageio#1017]
Hi. I would like to load TIFF images in grayscale format. Previously, in v2, this could be done with

```
img = imageio.v2.imread(filename, format='tiff-pil', as_gray=True)
```

However, in v3, the `format` and `as_gray` parameters are deprecated. Is there a way to reproduce the v2 behavior? I looked around but couldn't find anything.

**Comment by mathieuboudreau** [comment]
I'm on the same team as @hermancollin. Specifically, we've already switched to using `mode="L"` instead of `as_gray=True`, but `mode="L"` appears to not be working the same way for multichannel TIFFs as the old way.

**Comment by FirefoxMetzger** [comment]
Try 

```python
import imageio.v3 as iio

iio.imread(filename, plugin="pillow", mode="F")
```

> However, in v3, the `format` [...] parameter [is] deprecated.

In v3 `format` has been split into `plugin` (the plugin/backend to use) and `extension` (the file extension to use). In your case this means you would want to set `plugin="pillow"`.

We did this because v2 was abusing `format` to accomplish both and was (arbitrarily) mixing conventions. For example `format="TIFF"` would use the tifffile backend (or fail) and `format="FFMPEG"` would use the imageio-ffmpeg backend (or fail). In both cases any format would be allowed and it just set the plugin/backend. However, `format="tiff-pil"` would use pillow and enforce TIFF (or fail). Similarly `format=PNG-FI` would use freeImage and force PNG. There was no way to use pillow with all pillow-supported formats and also no way to enforce a format when using imageio-ffmpeg.

To clean this up, we now have `plugin` which will use the chosen plugin or fail. We also have `extension` which limits reading to plugins that are known to read formats associated with the provided extension. Further, if the selected backend supports more fine-grained format selection, `extension` also limits the backend to only use formats associated with the provided extension. (Typically there is exactly 1 such format, which means providing `extension` enforces a particular format.)

> [and so is] `as_gray`

`as_gray` has been deprecated because it is redundant with `mode` (formerly `pilmode`). The deprecation warning has some details on how to migrate:

```python
if as_gray is not None:
            raise TypeError(
                "The keyword `as_gray` is no longer supported."
                "Use `mode='F'` for a backward-compatible result, or "
                " `mode='L'` for an integer-valued result."
            )
```

**Comment by hermancollin** [comment]
@FirefoxMetzger thank you for your response. This does clarify how things changed from v2 to v3. Your suggestion worked for PNG files, but in the end we had to use the `tifffile` backend for TIFF. As you pointed out, tifffile supports TIFFs more extensively than pillow.

**Comment by FirefoxMetzger** [comment]
Tifffile doesn't offer built-in colorspace conversion afaik, as such you would have to do the conversion manually. If you can make a few assumptions about the content of your TIFF, you could solve it using something like the following:

```python
import imageio.v3 as iio

props = iio.improps(filename).
_img = iio.imread(filename)

# TIFF is a "wild" format. A few assumptions greatly simplify the code below:
# 1. the image is interleaved/channel-last (not planar)
# 2. the colorspace is one of: binary, gray, RGB, RGBA (not aliasing ones like YUV or CMYK)
# 3. the image is flat (not a volume or time-series)

# make grayscale (treats binary as 1-bit grayscale)
colorspace_idx = 2 + int(props.is_batch)
if _img.ndims <= colorspace_idx:  # binary or gray
    pass  # nothing to do
elif _img.shape[colorspace_idx] == 3:  # RGB
    _img = np.sum(_img * (.299, .587, .114), axis=-1)
else:  # RGBA
    # discards alpha
    _img = np.sum(_img * (.299, .587, .114, 0), axis=-1)
```
