### ISSUE TITLE
super slow video reads 

### ISSUE THREAD

**Issue by bdytx5** [imageio/imageio#1050]
My tests show OpenCV is about 40-50x faster for reading frames of a video? Is this known? 

Heres a few scripts that demonstrate it 

```python
import cv2
import numpy as np
import os
import time
import random

# Constants
DURATION = 100  # Duration of the video in seconds
FPS = 24  # Frames per second
FRAME_COUNT = DURATION * FPS
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
VIDEO_FORMATS = ['mp4', 'avi', 'mjpeg']

def create_dummy_video(filename, format):
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    if format == 'mp4':
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    elif format == 'mjpeg':
        fourcc = cv2.VideoWriter_fourcc(*'MJPG')

    out = cv2.VideoWriter(filename, fourcc, FPS, (FRAME_WIDTH, FRAME_HEIGHT))

    for _ in range(FRAME_COUNT):
        frame = np.random.randint(0, 256, (FRAME_HEIGHT, FRAME_WIDTH, 3), dtype=np.uint8)
        out.write(frame)
    out.release()

def measure_access_time(video_file):
    start_time = time.time()
    cap = cv2.VideoCapture(video_file)

    for _ in range(100):
        start_frame = random.randint(0, FRAME_COUNT - 8)
        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)
        for _ in range(8):
            ret, frame = cap.read()
            if not ret:
                break

    cap.release()
    return time.time() - start_time

def main():
    for format in VIDEO_FORMATS:
        filename = f'dummy_video.{format}'
        create_dummy_video(filename, format)
        time_taken = measure_access_time(filename)
        print(f"Time taken to access {format.upper()} video: {time_taken:.2f} seconds")

if __name__ == "__main__":
    main()
```

```python
import numpy as np
import os
import time
import random
import imageio

# Constants
DURATION = 10  # Duration in seconds
FPS = 24  # Frames per second
FRAME_COUNT = DURATION * FPS
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
VIDEO_FORMATS = ['mp4', 'avi', 'mjpeg']

def create_dummy_video(filename, format):
    writer = imageio.get_writer(filename, fps=FPS)

    for _ in range(FRAME_COUNT):
        frame = np.random.randint(0, 256, (FRAME_HEIGHT, FRAME_WIDTH, 3), dtype=np.uint8)
        writer.append_data(frame)

    writer.close()

def measure_access_time(video_file):
    start_time = time.time()

    for _ in range(100):
        with imageio.get_reader(video_file) as vid:
            num_frames = vid.count_frames()
            start_frame = random.randint(0, num_frames - 8)
            for i in range(start_frame, start_frame + 8):
                try:
                    frame = vid.get_data(i)
                except IndexError:
                    # Handle case where frame index is out of range
                    break

    return time.time() - start_time

def main():
    for format in VIDEO_FORMATS:
        filename = f'dummy_video.{format}'
        create_dummy_video(filename, format)
        time_taken = measure_access_time(filename)
        print(f"Time taken to access {format.upper()} video: {time_taken:.2f} seconds")

if __name__ == "__main__":
    main()
```

(Edited by @FirefoxMetzger: wrapped code into code blocks to improve readability)

**Comment by bdytx5** [comment]
sorry, i dont know how to format the code properly.... just copy and paste into a editor for viewing........

**Comment by Pandede** [comment]
`imageio` reads video with `PyAV`.
By default, `PyAV` reads the video with `thread_type=SLICE`, which decoding the video with single thread.
You may assign `thread_type=FRAME` to enable the multi-threadings decoding.
Here is the [reference](https://pyav.org/docs/develop/cookbook/basics.html#threading).

In `imageio`, you may assign `thread_type` to `imiter`:
```python
import imageio.v3 as iio

for frame in iio.imiter("imageio:cockatoo.mp4", plugin="pyav", thread_type="FRAME"):
    print(frame.shape, frame.dtype)
```

**Comment by FirefoxMetzger** [comment]
As @Pandede said, you likely want to use pyAV if you need performance. What's more is that you likely also want to use the ImageIO v3 API to write it a bit cleaner. Here is how I would write your test case:

```python
# import imagei.v3 as iio 

def measure_access_time(video_file):
    start_time = time.time()

    for _ in range(100):
        with iio.imopen(video_file, "r", plugin="pyav") as vid:
            num_frames = vid.properties().n_images
            start_frame = random.randint(0, num_frames - 8)
            for i in range(start_frame, start_frame + 8):
                frame = vid.read(index=i, thread_type="SLICE")

    return time.time() - start_time
```

That said, there are several reasons why you are observing slower performance with ImageIO than with pyAV:

- You are using the legacy video plugin (`imageio-ffmpeg`) which is slow. If you seek performance you are better off updating to the v3 API and using our pyAV plugin.
- Your choice of seeking behavior biases the test in favor of OpenCV. `cv2.CAP_PROP_POS_FRAMES` will seek to the video's closest preceding keyframe (inexact seek), not the exact frame you are asking for. OpenCV behaves like this [since forever](https://github.com/opencv/opencv/issues/9053) and I'm not aware of a good workaround except decoding from frame 0. ImageIO, on the other hand, does frame-exact seeking. The exact process depends on the internals of the video but typically means that we have to manually decode and discard some frames under the hood to get the decoder into the correct state and allow decoding from the requested index. In your test, you are summing time for exact seeking 100x in the ImageIO side, but not on the OpenCV side (inexact seek is almost instant).
- You use a `try ... except` block inside the innermost loop. This is slow and not needed; you know how many frames there are so you don't have to worry about decoding beyond the last one. Alternatively, you can iterate over the frames which is both cleaner and faster.
- You are measuring timings on different videos. Different writers (`imageio-ffmpeg`, `pyav`, `openCV`) use different defaults when creating a video which affects both quality and decoding speed. If you want an apples-to-apples comparison choose one writer (e.g. cv2, because you trust it), create the test videos, and then use them in each test.
- Your output format differs. OpenCV will return videos in BGR colorspace whereas ImageIO will return RGB colorspace by default. Depending on your downstream requirements you will have to convert one of the two images. ImageIO can decode into either colorspace directly (via PyAV), but OpenCV will have to copy your data which will be slower. (You may or may not wish to include this in your benchmark. )


That being said, ImageIO is slower in getting set up (time to first frame) than OpenCV. Using the snippet above and controlling for the input video, my timings are:

```
-- OpenCV
Time taken to access MP4 video: 0.58 seconds
Time taken to access AVI video: 0.53 seconds
-- ImageIO
Time taken to access MP4 video: 1.32 seconds
Time taken to access AVI video: 1.27 seconds
```

This still has inexact seeking for CV2, but even if we remove seeking (both start at frame 0) the timings stay roughly the same. However, assuming you _need_ exact seeking for your use-case the only way I am aware of doing this in OpenCV is to decode from the start and discard until we get to the frames we need. As you would expect this is slow and brings performance in line with ImageIO:

```
-- OpenCV
Time taken to access MP4 video: 1.29 seconds
Time taken to access AVI video: 1.25 seconds
-- ImageIO
Time taken to access MP4 video: 1.32 seconds
Time taken to access AVI video: 1.27 seconds
```

The reason for this is that toy videos like the one used for this test often only have 1 keyframe in the beginning. If you look at actual videos (especially with duration > 30 seconds) you will notice that ImageIO will be faster, because it can leverage (approximate) keyframe-seeking while still giving you a frame-exact result.

**Comment by bdytx5** [comment]
ok thanks!

**Comment by bdytx5** [comment]
ok thanks!

**Comment by FirefoxMetzger** [comment]
@bdytx5 Does this help you solve your problem (and shed some light on the situation)?

**Comment by bdytx5** [comment]
I was able to solve it at the time using OpenCv. I just wanted to shed light on this, but it seems like it’s well known. Also, hopefully this thread can be useful to someone in the future. Thanks.
