### ISSUE TITLE
UnicodeDecodeError if metadata is not UTF-8 encoded (pyav plugin)

### ISSUE THREAD

**Issue by nebenwelt** [imageio/imageio#1059]
UnicodeDecodeError if metadata is not UTF-8 encoded (pyav plugin)
-----------

Hi. 
I get an exception when processing a large collection of old video files, because some of them have meta information stored in encoding other than UTF-8.

I've simplified my exception-causing code to a few lines:
(the functions `immeta`, `improps`, `imread` raise the same exception)
```python
import imageio.v3 as iio
r = iio.imopen('my_video.avi', io_mode='r', plugin='pyav')
```

Traceback:
```python
Traceback (most recent call last):
  File "C:\_DEV\extract-image-from-video\.venv\Lib\site-packages\imageio\core\imopen.py", line 138, in imopen
    return loader(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_DEV\extract-image-from-video\.venv\Lib\site-packages\imageio\core\imopen.py", line 130, in loader
    return config.plugin_class(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_DEV\extract-image-from-video\.venv\Lib\site-packages\imageio\plugins\pyav.py", line 308, in __init__
    self._container = av.open(request.get_file())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\\container\\core.pyx", line 401, in av.container.core.open
  File "av\\container\\input.pyx", line 87, in av.container.input.InputContainer.__cinit__
  File "av\\utils.pyx", line 26, in av.utils.avdict_to_dict
  File "av\\utils.pyx", line 14, in av.utils._decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\_DEV\extract-image-from-video\src\imageio_test.py", line 6, in <module>
    r = iio.imopen('my_video.avi', io_mode='r', plugin='pyav')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_DEV\extract-image-from-video\.venv\Lib\site-packages\imageio\core\imopen.py", line 156, in imopen
    raise err_type(err_msg) from err_from
OSError: An unknown error occurred while initializing plugin `pyav`.
```
OS: `Windows 10 x64`
Package Versions:
```
Package    Version
---------- -------
av         11.0.0 
imageio    2.33.1 
numpy      1.26.3 
pillow     10.2.0 
pip        23.1.2 
setuptools 65.5.0 
```

I found that the error is related to the `pyav` plugin. For example, the following code will cause the same exception:
```python
import av
container = av.open('my_video.avi', 'r')
```
Traceback:
```python
Traceback (most recent call last):
  File "C:\_DEV\extract-image-from-video\src\pyav_test.py", line 4, in <module>
    container = av.open('my_video.avi')
                ^^^^^^^^^^^^^^^^^^^^^
  File "av\\container\\core.pyx", line 401, in av.container.core.open
  File "av\\container\\input.pyx", line 87, in av.container.input.InputContainer.__cinit__
  File "av\\utils.pyx", line 26, in av.utils.avdict_to_dict
  File "av\\utils.pyx", line 14, in av.utils._decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
```

The solution to this problem already exists [here](https://github.com/PyAV-Org/PyAV/issues/629#issuecomment-1404301660):
```python
import av
av.open('my_video.avi', 'r', metadata_errors="ignore")
```
The `metadata_errors="ignore"` parameter causes errors related to metadata encoding other than UTF-8 to be ignored.

My suggestion. 
Fix code in PyAVPlugin class constructor:
`-   self._container = av.open(request.get_file())`
`+   self._container = av.open(request.get_file(), metadata_errors="ignore")`

**Comment by Pandede** [comment]
May you provide any example for the purpose of composing the testcase?

**Comment by FirefoxMetzger** [comment]
@nebenwelt I think there is actually a more elegant solution than hardcoding the flag into the plugin's constructor. We can (and should) forward additional kwargs from `imopen` to `av.open`, which would enable us to overwrite any default that `av.open` might set including `metadata_errors`.

Example:
```python
with iio.imopen("imageio:cockatoo.mp4", "r", plugin="pyav", metadata_errors="ignore") as file:
    frames = file.read()
```

The downside is that this won't work with `imread`, `imiter`, or `imwrite` because here additional kwargs are forwarded to `Plugin.read`, `Plugin.iter`, etc. We can solve this by changing the default value for `metadata_errors` in the plugin's constructor but I don't think this is desirable behavior. (1) We want ImageIO to be a lean wrapper around PyAV - with a perhaps more friendly UI, so we should aim to match its defaults unless there is good reason not to. (2) I prefer that (by default) issues announce themselves via exceptions unless the user explicitly chooses otherwise. I've burned myself too many times on silent failures that went unnoticed for weeks and would rather have the library raise too often than too seldom.

**Comment by nebenwelt** [comment]
> @nebenwelt I think there is actually a more elegant solution than hardcodinh would enable us to overwrite any default that...

I agree, this is a good solution.
