### ISSUE TITLE
Unable to write colored gifs with pyav

### ISSUE THREAD

**Issue by FloWsnr** [imageio/imageio#1079]
I am trying to write a simple batch of images to a .gif file. However, I get tons of bad error messages.

Example that works:
```python
import imageio.v3 as iio
  frame_list = [
      np.ones((200, 200), dtype=np.uint8),
      np.ones((200, 200), dtype=np.uint8),
  ]

  iio.imwrite(
      "test.gif",
      frame_list,
      plugin="pyav",
      codec="gif",
      out_pixel_format="gray",
      in_pixel_format="gray",
  )
```

Now, I want to change the color format. However this does not work in any configuration.

```python
import imageio.v3 as iio
  frame_list = [
      np.ones((200, 200,3), dtype=np.uint8),
      np.ones((200, 200,3), dtype=np.uint8),
  ]

  iio.imwrite(
      "test.gif",
      frame_list,
      plugin="pyav",
      codec="gif",
      out_pixel_format="rgb24", #"pal8" not working, leaving it empty is not working
      in_pixel_format="rgb24", #similar to out, both pal8 and empty not working
  )
```

What am I doing wrong or are there some bugs?
Often, I get these error messages:

```..\..\miniconda3\envs\porouspy\Lib\site-packages\imageio\v3.py:139: in imwrite
    with imopen(
..\..\miniconda3\envs\porouspy\Lib\site-packages\imageio\core\v3_plugin_api.py:367: in __exit__
    self.close()
..\..\miniconda3\envs\porouspy\Lib\site-packages\imageio\plugins\pyav.py:781: in close
    self._flush_writer()
..\..\miniconda3\envs\porouspy\Lib\site-packages\imageio\plugins\pyav.py:1189: in _flush_writer
    for packet in stream.encode():
av/stream.pyx:149: in av.stream.Stream.encode
    ???
av/codec/context.pyx:471: in av.codec.context.CodecContext.encode
    ???
av/codec/context.pyx:280: in av.codec.context.CodecContext.open
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   av.error.ValueError: [Errno 22] Invalid argument; last error log: [gif] pal8

av/error.pyx:336: ValueError
```

**Comment by Pandede** [comment]
You may use `plugin="pillow"` to write a GIF (if `pyav` is not mandatory):
```python3
import imageio.v3 as iio
import numpy as np

frame_list = [
    np.zeros((200, 200, 3), dtype=np.uint8),
    np.zeros((200, 200, 3), dtype=np.uint8),
]

iio.imwrite(
    "test.gif",
    frame_list,
    plugin='pillow'
)
```

**Comment by FloWsnr** [comment]
Yes, you are correct, I can use the Pillow plugin. Right now I am actually using plain Pillow without imageio.
However, these error messages still seem buggy. Also, the pyav plugin should work, right?

**Comment by FirefoxMetzger** [comment]
@FloWsnr Writing GIF via pyav works ... it's just very unintuitive and requires knowledge of FFMPEG. If you have a good suggestion on how to improve the API I'm all ears :)

The reason it's unintuitive is because it requires you to use FFMPEGs filters ... which I suspect is a stealth feature of ImageIO today, i.e., not many people have realized we support this. Here are [the docs](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pyav.html#filters) and here's the snippet:

```python
import imageio.v3 as iio

with iio.imopen("output.gif", "w", plugin="pyav") as gif:
    gif.init_video_stream("gif", fps=25, pixel_format="pal8")
    gif.set_video_filter(filter_graph=(
        {  # Nodes
            "split": ("split", ""),
            "palettegen": ("palettegen", ""),
            "paletteuse": ("paletteuse", ""),
        },
        [  # Edges
            ("video_in", "split", 0, 0),
            ("split", "palettegen", 0, 0),
            ("split", "paletteuse", 1, 0),
            ("palettegen", "paletteuse", 0, 1),
            ("paletteuse", "video_out", 0, 0),
        ],
    ))

    for frame in iio.imread("imageio:cockatoo.mp4", plugin="pyav"):
        gif.write_frame(frame)
```

For comparison, here is the snippet with pillow:

```python
frames = iio.imread("imageio:cockatoo.mp4", plugin="pyav")
iio.imwrite("output2.gif", frames, plugin="pillow", duration=1000//25)
```

The added complexity buys you a smaller, higher-quality GIFs compared to pillow. In the example above pyAV will produce a 45MB GIF and pillow will produce a 90MB GIF. The file size difference stems from better compression. PyAV will use a single global color palette whereas pillow will use one palette per frame. Ofc, both are too large for practical use, but that's because it's generally not advisable to transcode full video into GIF. The quality difference stems from a custom palette. Unless you provide the palette alongside a frame, pillow uses a default color palette. PyAV, on the other hand, will compute an optimized palette across all frames, which is what the `palettegen` leg in the filter graph does. You can see the effect when you look at the beams of the ceiling in the produced GIF. Pillow shows strong banding, but PyAV shows less.

---

That said, it still suffers from this bug https://github.com/imageio/imageio/issues/1003 which means that the available resolution is limited and you get an FFMPEG warning that will flood your console. I would like to see this fixed, but don't have the time to dig in. It's a slightly non-trivial PR but you're welcome to have a go if you fancy a challenge 😄

**Comment by FirefoxMetzger** [comment]
Also, for reference, here is a nice example to show what I mean with color banding:
https://github.com/imageio/imageio/issues/995#issuecomment-1570816784

**Comment by FloWsnr** [comment]
Ah, thank you for this small tutorial. This is really helpful! I will mark this issue as closed.
