### ISSUE TITLE
Incorrect loading of PNG using freeimage

### ISSUE THREAD

**Issue by patricksnape** [imageio/imageio#117]
This PNG:

https://github.com/menpo/lfpw-train/blob/master/lfpw-train/image_0779.png

Does not load correctly using freeimage. I've noticed that imageio has a lot of the [same code as skimage](https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_plugins/freeimage_plugin.py) when it comes to freeimage. Should I be reporting this here or there? skimage also fails to load this.

What happens is that it returns a uint16 image that has clearly not been de-interleaved correctly. PIL, which handles the image correctly, reports the following for `tile`:

```'tile': [('zip', (0, 0, 800, 440), 60, 'RGB;16B')]```

**Replicate**
```
import imageio
import numpy as np
from PIL import Image as PILImage
import matplotlib.pyplot as plt

path = 'image_0779.png'

# Wrong
plt.subplot(121)
plt.imshow(imageio.imread(path))
# Correct
plt.subplot(122)
plt.imshow(np.asarray(PILImage.open(path)))
```

**Comment by almarklein** [comment]
Yes, I can reproduce this. Imageio shares a lot of code with skimage because imageio basically started out as fork of skimage's freeimage plugin.

The plan is that skimage is going to make use of imageio (i.e. have it as a dependency). All other plugins have already been ported to imageio. The idea is to make the switch once imageio uses wheels/conda packages and has shown that installation is stable. 

So ... I thing its best to fix it here, and then perhaps "backport" the fix to skimage if they're interested.

**Comment by patricksnape** [comment]
OK that sounds great - good to know. I'm pretty unfamiliar with how the freeimage plugin works and so I've been struggling to try and track this down. Any pointers on where the data might be getting incorrectly interpreted?

**Comment by almarklein** [comment]
I concur that this is not the easiest code to read. It's probably related to the part where the bitmap is converted to a numpy array, or in some of the functions that is uses (like getting the bpp). https://github.com/imageio/imageio/blob/master/imageio/plugins/_freeimage.py#L896

**Comment by patricksnape** [comment]
OK - so it isn't a problem with de-interlacing, it's actually just that matplotlib is having trouble displaying the UINT16 values because they are so large. It seems that PIL is automatically coercing the values back down into UINT8. This shows that:

```
plt.imshow((imageio.imread(path) >> 8).astype(np.uint8))
```

Which renders correctly and:

```
np.allclose(np.asarray(PILImage.open(path)), (imageio.imread(path) >> 8).astype(np.uint8))
```

is ``True``. So, do we want to catch this case and coerce it as PIL does? Or should I just be catching this case in my own code (when the values are UINT16 and the values are too large).

**Comment by almarklein** [comment]
I would be against auto-converting to uint8, because the image was probably stored with higher precision for a reason. 

I think the best we could do is add a note in the documentation that it is recommended to use `.astype("float32")` before doing any calculations on the image and/or displaying it in MPL.

**Comment by patricksnape** [comment]
OK well then this is likely a non-issue but just something to note -> Apparently freeimage and Pillow will not always return the same results
