### ISSUE TITLE
mimread now broken for tiff stack

### ISSUE THREAD

**Issue by jgostick** [imageio/imageio#126]
The mimread method now throws the following error when I attempt to load in a TIFF stack:

**ValueError: Could not find a format to read the specified file in mode 'I'**

This used to work in about June/July time.  I've also tried the volread method on my test image and get:

**ValueError: Could not find a format to read the specified file in mode 'v'**

I'm using a Windows machine with Python 3.4 via the WinPy package (Version 3.4.3.5).  I should add that I'm sending the 'uri' as a string to the file directory:

``im = imageio.mimread('C:\\Users\\Jeff\\Code\\Git\\PoreSpy\\test\\fixtures\\voronoi_fibers.tif')``

**Comment by almarklein** [comment]
Strange. The new tiffile plugin should accept the file just by its extension. Any chance we could get a copy of that file for testing?

cc @blink1073

**Comment by jgostick** [comment]
It's a TIFF stack so is a bit hefty...here is a link to a dropbox file: 

https://dl.dropboxusercontent.com/u/8481862/Linked%20To/voronoi_fibers.tif

**Comment by almarklein** [comment]
Oh, I suspect that you used a version from github earlier, and now an actual release. We did not make a release with tiffile support yet.

**Comment by jgostick** [comment]
Ah, i see.  I'll pip install from git and report back...thanks.

**Comment by almarklein** [comment]
Or ``pip install --upgrade``, I ust did a release a few minutes ago :)  Your comment reminded me that it was high time for a new release.

**Comment by jgostick** [comment]
Yup, I installed the bleeding edge using ``pip install https://github.com/imageio/imageio/archive/master.zip`` and it works as it used to.  Time to roll out a new version!  The tiff stack is the main source of x-ray tomography data, so I don't think I'm the only one that needs it.  Thanks for this project!

**Comment by MDyahkonov** [comment]
I am getting this error on aws lambda. I created a local virtualenv and everything works great, but when I deploy for aws lambda I am getting this error. Any idea why? I am using the latest build v1.4 and attempting to read and write png files.

**Comment by MDyahkonov** [comment]
I rebuilt the whole environment on ec2 and made sure all dependencies were satisfied, I then downloaded all the files and dependencies and pushed that to aws lambda. It now works properly. I think the issue was related to ffmpeg, required by moviepy, or freeimage. I can't remember exactly, but I know I that I meticulously rebuilt the environment on ec2.

**Comment by mhfowler** [comment]
@MDyahkonov do you  know where in moviepy there is a list of said dependencies? I am also trying to get rid of this error on an EC2 instance running ubuntu 14, but you are inspiring me that it is possible!

**Comment by mhfowler** [comment]
I have isolated that the same line does not throw an error on my EC2 instance if I create the ImageClip in a python shell, but it does throw the error when trying to create the ImageClip from within my flask app, served by apache, if this leads anyone to any suggestions. Going to try messing around with environmental variables and other path stuff e.g. IMAGEIO_FREEIMAGE_LIB 

exact lines causing error
`
 File "/usr/local/lib/python2.7/dist-packages/moviepy/video/VideoClip.py", line 895, in __init__
   img = imread(img)
 File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 182, in imread
   reader = read(uri, format, 'i', **kwargs)
`

**Comment by mhfowler** [comment]
@almarklein Hey almarklein, I've specifically identified that from my EC2 instance in the python shell, imageio finds the freeimage lib jpeg format to recognize the image file (JPEG - JPEG - JFIF Compliant, A JPEG format based on the Freeimage library.)

but that when running the library through apache, it doesn't recognize the exact same file path as this format. for apache I tried setting IMAGEIO_FREEIMAGE_LIB=/home/ubuntu/.imageio/freeimage/libfreeimage-3.16.0-linux64.so. because at one point, in the python shell, this was printed

`
Imageio: 'libfreeimage-3.16.0-linux64.so' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/freeimage/libfreeimage-3.16.0-linux64.so (4.6 MB)
Downloading: 4830080/4830080 bytes (100.0%)
  Done
File saved as /home/ubuntu/.imageio/freeimage/libfreeimage-3.16.0-linux64.so.
`

Yet even with this set, it still can't recognize. Any ideas what I should set IMAGEIO_FREEIMAGE_LIB to on ubuntu or if there is another possible problem?

**Comment by mhfowler** [comment]
wooooooooooooooo

`
apt-get install libfreeimage-dev
`

solved my problem :-)

this still may be an issue in moviepy  / imageio installation, in that it seems strange that python shell would have automatically downloaded and installed libfreeimage-dev to a location that other processes don't have access to, and also that this library was installed by default as a dependency when installing imageio or moviepy

**Comment by almarklein** [comment]
mmm, maybe the prebuild freeimage library that we provide does not work on the system that you tried it on? I suppose that on most linuxes its best to use the system freeimage anyway.
