### ISSUE TITLE
Support writing 16-bit color channels for PNG

### ISSUE THREAD

**Issue by OrganicIrradiation** [imageio/imageio#146]
I'm trying to transition away from MATLAB and imageio has been incredibly helpful. However, I need to work with 64-bit PNGs (16-bit color channels and 16-bit alpha channel) and although it looks like reading 16-bit channels is supported, writing is not supported.

I created some 64-bit pngs in MATLAB using the following code:

    img_out = zeros(256, 256, 3, 'uint16');
    img_alpha = zeros(256, 256, 'uint16');
    color_grad = uint16(reshape(0:2^16-1, 256, []));
    img_out(:, :, 1) = color_grad;
    img_out(:, :, 2) = rot90(color_grad, 1);
    img_out(:, :, 3) = rot90(color_grad, 2);
    img_out_alpha = rot90(color_grad, 3);

    fprintf('Write unique values: R=%u, G=%u, B=%u, A=%u\n', ...
            length(unique(img_out(:, :, 1))), ...
            length(unique(img_out(:, :, 2))), ...
            length(unique(img_out(:, :, 3))), ...
            length(unique(img_out_alpha)))
    imwrite(img_out, '64bit_MATLAB.png', 'Alpha', img_out_alpha, 'BitDepth', 16)
    
    [img_in, ~, img_in_alpha] = imread('64bit_MATLAB.png');
    fprintf('MATLAB PNG unique values: R=%u, G=%u, B=%u, A=%u\n', ...
            length(unique(img_in(:, :, 1))), ...
            length(unique(img_in(:, :, 2))), ...
            length(unique(img_in(:, :, 3))), ...
            length(unique(img_in_alpha)))

This gives me the following output:

> Write unique values: R=65536, G=65536, B=65536, A=65536
> MATLAB PNG unique values: R=65536, G=65536, B=65536, A=65536

If I try the same with imageio in Python:

    import imageio
    import numpy as np

    img_out = np.zeros((256, 256, 4), dtype=np.uint16)
    color_grad = np.reshape(np.arange(2**16), (256,-1))
    img_out[:, :, 0] = color_grad
    img_out[:, :, 1] = np.rot90(color_grad, 1)
    img_out[:, :, 2] = np.rot90(color_grad, 2)
    img_out[:, :, 3] = np.rot90(color_grad, 3)

    print('Write unique values: R={}, G={}, B={}, A={}'.format(
        len(set(img_out[:, :, 0].flatten().tolist())),
        len(set(img_out[:, :, 1].flatten().tolist())),
        len(set(img_out[:, :, 2].flatten().tolist())),
        len(set(img_out[:, :, 3].flatten().tolist()))))
    imageio.imwrite('64bit_imageio.png', img_out)

    img_in = imageio.imread('64bit_imageio.png')
    print('imageio PNG unique values: R={}, G={}, B={}, A={}'.format(
        len(set(img_in[:, :, 0].flatten().tolist())),
        len(set(img_in[:, :, 1].flatten().tolist())),
        len(set(img_in[:, :, 2].flatten().tolist())),
        len(set(img_in[:, :, 3].flatten().tolist()))))

I get the following:

> Write unique values: R=65536, G=65536, B=65536, A=65536
> imageio PNG unique values: R=256, G=256, B=256, A=256

To confirm, imageio is able to read the 64-bit PNG:

    img_in = imageio.imread('64bit_MATLAB.png')
    print('MATLAB PNG unique values: R={}, G={}, B={}, A={}'.format(
        len(set(img_in[:, :, 0].flatten().tolist())),
        len(set(img_in[:, :, 1].flatten().tolist())),
        len(set(img_in[:, :, 2].flatten().tolist())),
        len(set(img_in[:, :, 3].flatten().tolist()))))

> MATLAB PNG unique values: R=65536, G=65536, B=65536, A=65536

Any idea how difficult this would be to implement?

**Comment by OrganicIrradiation** [comment]
Here are the images (sorry imgur changes the names and the indexing is rotated, but the "unique" values should be the same):

  * 64bit_imageio.png: http://i.imgur.com/UnYx1Lo.png
  * 64bit_MATLAB.png: http://i.imgur.com/syNXVYR.png

**Comment by almarklein** [comment]
Imageio makes use of freeimage for reading/writing png data. Good to hear it supports reading in this format. I am not sure whether it supports writing to it, but we can try.

This would need some changes in the imageio code, because currently, in the png writer, we explicitly convert to uint8 (https://github.com/imageio/imageio/blob/master/imageio/plugins/freeimage.py#L225).

I don't have an awful lot of time to look into it, but I am happy to guide you in trying to make it work.
* In the above link, you should remove the conversion to uint8
* The code then moves to `Writer._append_data()`, which makes calls into the freeimage wrapper here https://github.com/imageio/imageio/blob/master/imageio/plugins/freeimage.py#L126-L128
* Allocate: https://github.com/imageio/imageio/blob/master/imageio/plugins/freeimage.py#L126-L128
* set_image_data: https://github.com/imageio/imageio/blob/master/imageio/plugins/_freeimage.py#L938
* I am not sure how well our freeimage wrapper deals with 16bit data. Maybe it just works, or maybe it needs some changes ...

**Comment by OrganicIrradiation** [comment]
Thanks for the info, based upon your rehashing of the methodology. Turns out it's basically baked into free image, so I was able to add support for 16-bit PNGs pretty easily: https://github.com/imageio/imageio/pull/150

And it looks like all the tests pass with:

    python make test unit
    python make test style

**Comment by OrganicIrradiation** [comment]
For anyone who might come across this issue, since freeimage is being slowly phased out, the only way to read/write 48-bit (16-bit/channel) PNGs is to specify the format attribute. I found this out the hard way since imageio silently broke one of my processing pipelines, without a depreciation warning. :-(

So, the revised example here would be:

``` python
import imageio
import numpy as np

img_out = np.zeros((256, 256, 4), dtype=np.uint16)
color_grad = np.reshape(np.arange(2**16), (256,-1))
img_out[:, :, 0] = color_grad
img_out[:, :, 1] = np.rot90(color_grad, 1)
img_out[:, :, 2] = np.rot90(color_grad, 2)
img_out[:, :, 3] = np.rot90(color_grad, 3)

print('Write unique values: R={}, G={}, B={}, A={}'.format(
    len(set(img_out[:, :, 0].flatten().tolist())),
    len(set(img_out[:, :, 1].flatten().tolist())),
    len(set(img_out[:, :, 2].flatten().tolist())),
    len(set(img_out[:, :, 3].flatten().tolist()))))
imageio.imwrite('64bit_imageio.png', img_out, format='PNG-FI')

img_in = imageio.imread('64bit_imageio.png', format='PNG-FI')
print('imageio PNG unique values: R={}, G={}, B={}, A={}'.format(
    len(set(img_in[:, :, 0].flatten().tolist())),
    len(set(img_in[:, :, 1].flatten().tolist())),
    len(set(img_in[:, :, 2].flatten().tolist())),
    len(set(img_in[:, :, 3].flatten().tolist()))))
```

**Comment by almarklein** [comment]
@OrganicIrradiation thanks for the update.

As for breaking your pipeline, I'm sorry this happened, I understand this can be a pain. That said, it was not really feasible to show a warning for each case where the PIL plugin was used that would previously have used FI. I could respond by saying that you should have read the release notes, but I rarely read release notes myself when I update a package, especially since packages frequently update automatically with conda :)
