### ISSUE TITLE
Alpha Channel Property

### ISSUE THREAD

**Issue by asif-mahmud** [imageio/imageio#161]
It's sometimes needed to see if the image has alpha channel. A simple property in `imageio.core.Image` like the following -
`
@property
def alpha_channel(self):
        """ True if the image contains alpha channel.
        """
        return self.shape[2] == 4
`
should not hurt the codebase so much.

**Comment by almarklein** [comment]
The Image wrapper class is not something I am particularly happy about. Its purpose is to allow a `meta` attribute so that meta-data can be returned easily with the data to which it applies. I feel very strongly against making that class any smarter than it is.

In this particular case I'd suggest doing something like `if im.shape[2] == 4:`. Or maybe a small `has_alpha = lambda im: im.shape[2] == 4` at the top of your code.
