### ISSUE TITLE
RuntimeError: Could not read frame:

### ISSUE THREAD

**Issue by cancan101** [imageio/imageio#168]
Trying to run:

```
imageio.mimread('http://techslides.com/demos/sample-videos/small.mp4')
```

I get:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/alex/.virtualenvs/media/lib/python2.7/site-packages/imageio/core/functions.py", line 263, in mimread
    for im in reader:
  File "/Users/alex/.virtualenvs/media/lib/python2.7/site-packages/imageio/core/format.py", line 375, in iter_data
    im, meta = self._get_data(i)
  File "/Users/alex/.virtualenvs/media/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 300, in _get_data
    result = self._read_frame()
  File "/Users/alex/.virtualenvs/media/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 502, in _read_frame
    s = self._read_frame_data()
  File "/Users/alex/.virtualenvs/media/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 488, in _read_frame_data
    raise RuntimeError(fmt % (err1, err2))
RuntimeError: Could not read frame:
```

```
=== stderr ===
ffmpeg version 2.6.3-tessus Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa85b812800] overread end of atom 'colr' by 1 bytes
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/folders/nk/5v0p39pn4yg7c_3vtydljk000000gn/T/imageio_Y0WOps.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2010-03-20 21:29:11
    encoder         : HandBrake 0.9.4 2009112300
  Duration: 00:00:05.57, start: 0.000000, bitrate: 551 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 560x320, 465 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2010-03-20 21:29:11
      encoder         : JVT/AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 83 kb/s (default)
    Metadata:
      creation_time   : 2010-03-20 21:29:11
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    encoder         : Lavf56.25.101
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 560x320, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2010-03-20 21:29:11
      encoder         : Lavc56.26.100 rawvideo
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
frame=  166 fps=0.0 q=0.0 Lsize=   87150kB time=00:00:05.53 bitrate=129024.0kbits/s    
video:87150kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

**Comment by almarklein** [comment]
I suspect that there is a problem somewhere in the video file. I can reproduce it, though I can read the first 166 frames just fine, using this code that tries to read what it can:
```py
reader = imageio.get_reader('http://techslides.com/demos/sample-videos/small.mp4')
ims = []
try:
    for im in reader:
        ims.append(im)
except RuntimeError:
    pass
```

**Comment by almarklein** [comment]
Maybe we need a newer ffmpeg.

**Comment by igordertigor** [comment]
I can reproduce the same problem in a number of different mp4 files. In fact, using the `get_reader` version of the code, it seem as if it is always the last frame that breaks. Interestingly, that frame contains data beyond the nominal length of the video and calling ffmpeg from the command line like this:

**Comment by kuchi** [comment]
@almarklein I tried reading the video file with the newest ffmpeg version 3.2.2 with imageio but I also get the same issue showing it has 167 frames (with only 166 good frames). So that does not fix it. However, if I open the video file in question in Final Cut Pro, it shows there are only 166 frames, whereas ffmpeg reports 167. I think there is something bad with the encoding of the video file and ffmpeg doesn't correctly read it. It appears this video file was encoded with HandBrake (HandBrake 0.9.4 2009112300). Maybe it doesn't properly close the video file leaving ffmpeg to thing there is an extra frame? I'm not sure, but if I write the file back out using Final Cut Pro and read that back in using ffmpeg then I get the correct 166 count of frames. So this appears more to be some encoding or decoding issue on ffmpeg's side or the original encoding software side. 

I haven't run into this before and I process tons of videos from lots of different cameras & systems using imageio, so this may be an issue with HandBrake since that's the encoder listed in this file.  @igordertigor  @cancan101  are there other files you can point me to with this issue? I'd like to know if it's all coming from a specific encoder or not.

Note that if I try and convert the file using ffmpeg, it appears the derivative file also has the same issue, so FFMPEG does not properly rewrite the file (whereas I can get Final Cut Pro to properly re-encode). 

So, to me this does not really seem like a imageio bug, although perhaps it could fail in a nicer way using mimread if this occurs often (I haven't seen this before though). Maybe could just issue warning that last frame was not read and continue on since most people would probably be happy to have that than it fail for just the last frame.

**Comment by cancan101** [comment]
Take a look at file linked in #171. I don't recall if it was having the same issue. But it comes from a different source than handbrake.

**Comment by kuchi** [comment]
@cancan101 , this is a different issue in #171. I can read that file just fine using ffmpeg.

**Comment by kuchi** [comment]
@almarklein in reading more about incomplete video files, this isn't all that uncommon. It happens from time to time. I wonder if it makes sense for the `mimread` function to read up until a frame fails return the data read and print a warning that only x of y frames were read. That might be more user friendly since `mimread` for videos is probably being used by people less familiar with video processing compared to `get_reader`. I don't know what your opinion is, I don't use `mimread` since I usually have big video files. In some sense failing seems correct but then people probably just want the data they can get.

**Comment by almarklein** [comment]
@kuchi thanks for looking into this. Your suggestion makes sense. Lemme have a look :)

**Comment by igordertigor** [comment]
@kuchi, thank you for looking into this. Here is the example file I used (zipped to allow uploading to github): [example.zip](https://github.com/imageio/imageio/files/698943/example.zip).
It fails when using `mimread`, but works fine with this construction:

```python
try:
    frames = []
    for frame in get_reader(videofilename):
        frames.append(frame)
except RuntimeError:
    print('runtime error')
```
Note, that when I type `len(frames)`, I get 53, while 
```bash
ffprobe -v error \
    -count_frames \
    -select_streams v:0 \
    -show_entries stream=nb_read_frames \
    -of default=nokey=1:noprint_wrappers=1 \
    <videofile>
```
Only gives 52 frames! That makes me even more confused now. I hope, it's the other way round for you. Let me know if I can be of any help. I'm currently going with the try except clause, which isn't exactly beautiful...

**Comment by kuchi** [comment]
@igordertigor I opened the file in Final Cut Pro and it reads 53 frames. I also read it using imagio and it can also read the first 53 frames. I don't know how ffprobe gets the frame count using -count_frames but it appears wrong in this case. It seems like total frame count for video files is not always an exact process from what we are seeing. I don't know if this is due to some video files not being fully closed or completed or if this had to do with how many significant digits ffmpeg is printing for the duration and then that is causing issues due to us taking duration*fps to get frame count. I'm not sure. But maybe we just need to not believe the frame count is always exact.

**Comment by cancan101** [comment]
This sounds a little crazy:
>maybe we just need to not believe the frame count is always exact.

This looks wrong:
>us taking duration*fps to get frame count.

**Comment by almarklein** [comment]
> This looks wrong:

> > us taking duration*fps to get frame count.

I agree that its fragile at least. If you know of a better way for imageio to get the number of frames, I am all ears. But since the above discussion shows that well respected programs report different count of the same file, I'm starting to thing that @kuchi might be right.

**Comment by rmmcnulty9** [comment]
Why can't the number of frames be retrieved using `ffprobe` outlined here: https://stackoverflow.com/a/28376817/1439914

I have a high framerate video and I constantly get off by one errors with imageio's length. I am at the point where I am going to use `ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 input.mkv` instead of `len(imageio.get_reader('input.mkv'))`

**Comment by almarklein** [comment]
Because of the additional dependency that it would add, and because #115

**Comment by yujmo** [comment]
imageio.core.format.CannotReadFrameError: Could not read frame
