### ISSUE TITLE
Return PIL images instead of numpy arrays

### ISSUE THREAD

**Issue by igordertigor** [imageio/imageio#228]
I'm reading images from a webcam using `imageio.get_reader` and I really enjoy the convenient iterator style of handling the individual frames. I need to process the returned frames using PIL/Pillow so I convert every frame to a PIL image as a first step and then continue from there. This seems like a bit of a waste of resources to me, as imageio converts an underlying PIL image to a numpy array before returning it. It would be cool if imageio would provide a way to simple access the PIL image directly without converting it to a numpy array first. Is that planned any time soon? If not, would there be an interest for someone to implement it?

**Comment by almarklein** [comment]
If you're reading from a webcam, imageio does not use Pillow. The Pillow plugin is just one of many plugins, albeit the one that covers the most common formats. So I don't think that imageio will ever return a PIL image. I think converting a numpy array to a PIL image should be real easy nowadays, and otherwise I'd recommend writing a small function that does the trick and use that where you need it.
