### ISSUE TITLE
Issue using Pillow in a threaded context

### ISSUE THREAD

**Issue by NiklasRosenstein** [imageio/imageio#244]
I'm reading a bunch of JPG files from multiple threads at the same time. I consistently get `"Imageio Pillow plugin requires Pillow lib."` from `imageio.plugins.pillow.PillowFormat._init_pillow()`. If I wrap everything inside `_init_pillow()` in a lock, it works fine. Any idea how to make sure that `_init_pillow()` was called without reading a fake JPG file?

**Comment by almarklein** [comment]
Ah, I can see how this is a problem. The first thread that enters [_init_pillow()](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py#L38-L54) sets `_pillow_imported` but the second thread enters before the first has a chance to set `_Image`.

I think this can be fixed by putting a lock at the start of the function. Something like this:
```
def __init__(self, *args, **kwargs):
    self._lock = threading.RLock()

def _init_pillow(self):
    lock.require()
    try:
        ... the original code
    finally:
        threading.release()
```

Do you care for making a PR?

**Comment by NiklasRosenstein** [comment]
Yes, that's how I managed to get it working temporarily. :) I'll send a PR
in a bit.
