### ISSUE TITLE
[Feature Request] Partial Conformance with the SciPy Image I/O API

### ISSUE THREAD

**Issue by leycec** [imageio/imageio#289]
The long-heralded release of [SciPy 1.0.0](https://scipy.github.io/devdocs/release.1.0.0.html) has landed.

Sixteen years was a hard wait, but good things come to those who wait... *for sixteen years.*

## The Inevitable Bad News

Well, mostly good things. SciPy version:

* 1.0.0 [officially deprecates](https://scipy.github.io/devdocs/release.1.0.0.html#backwards-incompatible-changes) *all* image I/O functionality residing in the `scipy.ndimage` and `scipy.misc` packages – including the commonly called `scipy.ndimage.imread()` and `scipy.ndimage.imwrite()` functions.
* 1.2.0 plans to **permanently remove** this functionality. *Boom!*

Since [our downstream biophysics simulator](https://gitlab.com/betse/betse) heavily depends upon this functionality, SciPy 1.0.0 is more of a bad than a good thing for us. <sup>Yet again, progress only brings pain.</sup>

[SciPy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html) explicitly recommends `imageio` as a suitable replacement. Since the `imageio` API is *considerably* more bare bones than the equivalent SciPy API, however, `imageio` may prove to be a less-than-suitable replacement for some end users – mostly, us.

## The Overly Optimistic Hope

Ideally, the `imageio` API could be marginally improved to provide at least *partial* support for several of the most commonly used features of SciPy's image I/O API. This includes:

* **Pillow-based mode conversion.** The [`scipy.ndimage.imread()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html) function, for example, provides an optional `mode` string parameter permitting external callers to specify a desired target colorspace (defaulting to `None`). If non-`None` and different from the image's current `mode`, this parameter is passed as is to the `PIL.Image.convert()` method. This is two lines of Python. So, this is good.
* **Grayscale flattening.** Again, the [`scipy.ndimage.imread()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html) function provides an optional `flatten` boolean parameter permitting external callers to reduce non-grayscale images to grayscale (defaulting to `False`). If `True`, the `mode` parameter is coerced to `F`. Why not `L`? I have no idea and doubt SciPy developers do either. I also resent the overly ambiguous name of this boolean, when something resembling `grayscale` or `as_gray` would have sown less confusion. This also is two lines of Python. So, at least that is good.

This isn't simply syntactic sugar.

This is critical functionality of general interest. Well, O.K... `flatten` is blatantly syntactic sugar.

But `mode` isn't. External callers have *no* explicit access to the `PIL.Image` instance internally instantiated by this function. These optional parameters are the only means callers have of intervening in the conversion process. Doing so after the fact is non-trivial (or perhaps even infeasible).

I accept that `imageio` is not, will never be, and *should* never be an image processor. `imageio` is a pure image I/O framework – just as Code Jesus intended. Still... the thin line between image I/O and image processing is an easy Rubicon to cross, especially when Pillow already performs all of the heavy lifting on our behalf.

## Bold Details for a Bright Future

SciPy's image I/O is unconditionally implemented in terms of Pillow.

`imageio`, on the other hand, is conditionally implemented in terms of Pillow and whatever else it happens to scrounge from the local filesystem (e.g., FreeImage). Presumably, this conditionality prevents the optional `mode` and `flatten` parameters from being directly handled by the `imageio.imread()` function.

I grok that. Nonetheless, would it be feasible to permit these parameters to be:

* Passed by callers as variadic keyword arguments accepted by `imageio.imread()`.
* Passed by Pillow plugins invoked by `imageio.imread()` to the `PIL.Image.convert()` method, munging a `True` value for the `flatten` key into a `mode` value of either `L` or `F`.
* Processed in some fashion by the non-Pillow plugins. Hopefully, these parameters won't simply be silently ignored – but I'll take what I can get.

The `imageio.plugins.pillow.pil_get_frame()` function appears to offer similar functionality, albeit in a manner *not* exposed to external callers. Or is it? My modest (read: *awful*) `grep` skills failed me here.

Alternately, would exposing the `PIL.Image` instance internally instantiated by Pillow plugins via some public variable or getter method of the `imageio.core.format.Reader` class be feasible? I half-suspect this class *already* exposes `PIL.Image` instances, but (again) shamefully failed to `grep` the exact variable or method for doing so.

## The End of a Dream

Thus ends this excrutiating feature request.

Thanks for the long years of gruelling work. May there be many more to come! 🌞

**Comment by almarklein** [comment]
Hi @leycec, thanks for this request! I was not aware yet that scipy was deprecating their imageio functionality and putting imageio forward as a replacement. I agree that we should try to make the API more conformant to that of scipy to ease the transition. We might also setup a small doc page to help people in their transition.

The way that imageio's `imread()` works is that it accepts `**kwargs`, which are passed to the used format. What args are accepted is documented per format, e.g. here for [Pillow PNG](http://imageio.readthedocs.io/en/latest/format_png-pil.html). If a format behaves well, it will raise an error when it receives keyword arguments that it does not know. 

The Pillow plugin provides many formats, so it looks like we may want to add a common option (i.e. keyword argument) to all formats that the Pillow plugin provides. Further down the line, we can see if we can add the same keyword argument to other formats as well. Perhaps not for mode, since that seems specific to Pillow, but I can see it makes sense for `as_gray`.

I can have a look at this sometime in the coming weeks. Or at least do a bit of initial investigation as to how hard it would be. Imageio also tries to mimic the behavior of scikit-image (for similar reasons), so there might be some complexity in that regard.

As to the names of the options to add. I can see `mode` working for pillow-formats, but I would argue in favor of renaming the grayscale option to `as_gray` or perhaps `asgray`. What do you think? We could consider providing an alias `flatten` that prints a warning (or raises an error) telling the user to use `asgray` instead.

**Comment by leycec** [comment]
> I was not aware yet that scipy was deprecating their imageio functionality and putting imageio forward as a replacement.

_Yup._ This is a pivotal moment for imageio. I believe `scikit-image` is also [in process](https://github.com/scikit-image/scikit-image/issues/1605) of transitioning their backend from PIL to imageio. <sup>_no pressure though_</sup>

Congratulations on the increased attention this project has deservedly earned!

> we may want to add a common option (i.e. keyword argument) to all formats that the Pillow plugin provides.

👍 

> Perhaps not for mode, since that seems specific to Pillow,

👍 👍 👍 

Technically, it might be feasible to try to cobble together alternative implementations of the `mode` keyword for non-Pillow plugins. Pragmatically, doing seems undesirable. It's doubtful that Pillow's implementation of `mode` would exactly conform to that of imageio's for non-Pillow plugins. Data returned by `imread()` would then conditionally depend on which plugin the end user is currently using.

Which... kinda seems bad.

Which leads me to another question, actually. Is it feasible for users to specify not merely *soft* preferences but *hard* requirements for formats? Specifically, is it feasible for users to *require* (rather than merely *prefer*) that only Pillow plugins be used?

Since non-Pillow plugins would be unlikely to support the Pillow-specific `mode` parameter, imageio would probably raise a low-level exception (as you helpfully suggest earlier). That's reassuring. Still, explicit support for specifying mandatory dependencies *would* permit imageio to raise a more human-readable exception. <sup>in theory</sup>

At the moment, the following snippet appears to be the best approximation:

```
try:
    import PIL
except:
    raise ValueError('Mandatory dependency "Pillow" unimportable.')

import imageio
imageio.formats.sort('-PIL')
```

Perhaps a new `imageio.formats.require()` function passed the exact same positional and keyword arguments as the existing `imageio.formats.sort()` function could be added to the API. `require()` might iteratively validate all passed formats to be usable under the current environment, raising an exception if not *or* deferring to `sort()` if so. Maybe?

But... what do I know. I'm just a disembodied string of characters on a glowing phosphorescent screen.

> there might be some complexity in that regard.

May the overly complex source be with you. I feel your pain.

> I can see `mode` working for pillow-formats

**Right.** `mode` is absolutely appropriate. It's also a little... ambiguous. Maybe? I can't imagine Pillow is the only image framework to leverage that term. That said, I have a poor imagination. Maybe `pil_mode`, `mode_pil`, or something similarly Pillow-specific?

How *does* imageio handle keyword argument conflicts, actually? I assume it would be A Pretty Bad Thing™ if competing plugins for the same format (e.g., `PNG-FI` and `PNG-PIL`) both accepted a `mode` argument with different (and hence) conflicting interpretations. `</collective_shrug>`

> I would argue in favor of renaming the grayscale option to `as_gray`

I would argue identically. `as_gray` is particularly nice, in that the `skimage.data.imread()` function accepts a parameter of the same name. Conformance assists sanity, which is nice.

> We could consider providing an alias `flatten` that prints a warning (or raises an error) telling the user to use `as_gray` instead.

`flatten`. *Yeah.* From the usability perspective, I definitely see where you're coming from here. From the maintainability perspective, I shudder at bit rot, code smells, and *yet more* maintenance burden.

Developer time is precious. Perhaps imageio documentation could instead synopsize this change in human-readable text (e.g., "Substitute `flatten` for `as_gray`.")? Especially if *this* happens:

> We might also setup a small doc page to help people in their transition.

👍 

Thanks for the attentive ear, @almarklein. There's no immediate rush on any of this, of course. Best to get sweeping API generalizations right the first time, eh? <sup>_My Canadian dialect betrays me even online._</sup>

**Comment by untom** [comment]
I second the introduction of a scipy-compatible API, and would like to add that every call to `imwrite` which is fed a float-image will trigger a "UserWarning: Conversion from float32 to uint8" warning. I get the reasoning behind this warning, but it clutters my script's output. It would be nice if users had the option to easily surpress this warning (without having to use a context manager on each call).

**Comment by almarklein** [comment]
PR pending in #311 

Added a `pilmode` keyword (because `mode` was already in use) and `as_gray`.  I don't think we need any sorting of formats. Pillow is a hard dependency of imageio, and it is the preferred plugin for all formats except tiff. I suspect that forcing imageio to use pillow is thus also not necessary, but if I am proven wrong I am happy to add support for that. At the moment one can force specific formats, e.g. `imageio.imread(filename, 'png-pil')`, but not a plugin (i.e. a collection of formats).

As for conflicting keyword arguments for formats that support the same kind of files. Yeah, that could happen, but I guess its rare. That's why its possible to explicitly use a specific format.

@untom About that warning regarding precision loss: I did not (yet) add an option to suppress it. My guess is that if you want to suppress it, you should convert the data before saving it. I tweaked the warning so it says exactly that. What do you think?
