### ISSUE TITLE
Plugin: MHD format for reading ITK image data

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#29]
Used e.g. by the Elastix registration toolkiit.

http://www.itk.org/Wiki/ITK/MetaIO/Documentation

**Comment by almarklein** [comment]
Reopening; this is covered by the `simpleitk` plugin, but that dependency is not pure Python (I think?) and you cannot simply pip install it.

MHD is a simple format that we can implement in pure Python in imageio.

@blink1073 thoughs?

**Comment by blink1073** [comment]
Seems reasonable to leave this open, but I wouldn't say it is a "simple" format. :smile:

**Comment by gordon-n-stevenson** [comment]
MetaImage is always a pain but super useful for Medical Images. I've suggested a pull request to the SimpleITK plugin - adding formats '.mha' and '.nii' formats These are single file 3D image formats that solve I think the problems of a header and separate raw file.

**Comment by FirefoxMetzger** [comment]
@almarklein As you mentioned here a (long) while ago, MHD is supported via itk/simpleitk. Since then, our policy has become more liberal towards non-python backends, so I think it is okay to have MDH support via simpletik for those that need it.

Since this issue doesn't suggest a specific alternative backend for MHD, should we close it for now? (We can always open a new issue for a dedicated plugin/backend for MHD if this becomes relevant in the future.)

**Comment by almarklein** [comment]
I've worked on a pure Python mhd implementation a year or so ago. It's in a propitiatory codebase right now, but I think ppl may be open to bringing that code here. That said, yes lets close this.
