### ISSUE TITLE
Formalize plan to drop support for Python 2.x

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#291]
Numpy has recently [published their plan](https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst) for dropping Python 2.7. At the moment, imageio supports Python 2.6 and up.

I think it's clear that imageio will follow and drop support for 2.x (2.6 and 2.7 at the same time) at a similar schedule. We should document the plan for this.

**Comment by hugovk** [comment]
Good idea!

I also recommend dropping Python 2.6 now.

* Numpy and Pillow no longer support 2.6 
* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history), no more security updates
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Wheel no longer supports Python 2.6 https://github.com/pypa/wheel/commit/c9e54864b64ad5c949bfb6ce8cdfd77df03647ef
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by hugovk** [comment]
See PR https://github.com/imageio/imageio/pull/297 to drop EOL Python 2.6.

**Comment by almarklein** [comment]
Added a small page to the docs stating the plan: https://github.com/imageio/imageio/blob/master/docs/drop27.rst
