### ISSUE TITLE
PNG-PIL: low-saturation 16-bit array cast and saved as 8-bit PNG

### ISSUE THREAD

**Issue by LandingEllipse** [imageio/imageio#352]
## What did you do?
Try to save a _low saturation_ grayscale 16-bit PNG.

## What did you expect to happen?
Obtain a 16-bit PNG file.

## What actually happened?
The file was silently saved as an 8-bit PNG, despite the input array dtype being uint16.

## Reproducible example
imageio: 2.3.0
Pillow: 5.1.0
Python: 3.6.5
### Expected behaviour
```python
import numpy as np
import imageio

arr = np.full((32, 32), 256, dtype=np.uint16)
imageio.imwrite("~/16-bit_test.png", arr)

img = imageio.imread("~/16-bit_test.png")
print(img.dtype)  # => "uint16"
```
```
$ file ~/16-bit_test.png
16-bit_test.png: PNG image data, 32 x 32, 16-bit grayscale, non-interlaced
```
### Unexpected behaviour
```python
import numpy as np
import imageio

arr = np.full((32, 32), 255, dtype=np.uint16)
imageio.imwrite("~/16-bit_test.png", arr)

img = imageio.imread("~/16-bit_test.png")
print(img.dtype)  # => "uint8"
```
```
$ file ~/16-bit_test.png
16-bit_test.png: PNG image data, 32 x 32, 8-bit grayscale, non-interlaced
```

## Source of the issue
The behaviour originates in the Pillow plugin's `ndarray_to_pil` function:
https://github.com/imageio/imageio/blob/23ae5c1df0ca0d30931ff42833cf88fc3eb218aa/imageio/plugins/pillow.py#L621-L623
The function checks whether the values in the input ndarray fits in uint8 and recasts the array and sets the mode accordingly if this is the case. 

## Consequences and thoughts
My use case involves capturing calibration images from a scientific imaging system. Some sets are well saturated (e.g. flat fields), while others carry very low signal levels (e.g. bias images). Images can be captured in both 8-bit and 16-bit, and consuming pipeline scripts use the dtype of images for normalisation etc.

Therefore, it is vital that 16-bit data is actually saved as 16-bit PNGs. If for instance a 16-bit bias image peaking at `arr.max() == 255` is saved by `imageio` as an 8-bit PNG, pixel intensities will be completely misrepresented. In the original, the max intensity is just under 0.39% while in the saved 8-bit image the apparent max intensity is 100%. Image viewers will of course also reflect this issue.

 I understand that for input arrays that with `arr.dtype.kind == 'f'` it both makes sense and is necessary to bring the values into a supported unsigned integer format, but when the input array is already in uint16 I would argue that any casting to uint8 constitutes unexpected and counterintuitive behaviour, as the dtype likely has been specified consciously by the user to reflect the range/scale of the input data. But as I make this argument based on a sample size of one, I'm curious to hear your thoughts. Since git blames @almarklein for the lines quoted above, maybe you have some input on this?

**Comment by almarklein** [comment]
Hi @Legendin, I am indeed to blame :)  And after considering this, I agree that the behavior is probably wrong; I had not considered your use case.

As you say, it makes sense for float images, but for integer types, chances are that the user is explicitly using *that* type. Since you already found the source of the issue, would you mind making a PR to implement the improved behavior?

**Comment by Legendin** [comment]
Thank you for the quick reply @almarklein. I'm glad to hear there doesn't appear to be an obvious justification for the behaviour that I've missed. Though I do see it's also present in "upstream" scikit-image, and has been for 4-ish years (apparently since 16-bit support was added).

I'm travelling at the moment but I would be happy to send a PR your way as soon as I get the chance. Just want to get a sufficient overview of the issue first to minimise the risk of introducing regressions or messing up someone's workflow. :)

**Comment by almarklein** [comment]
Great!

Yeah, it would probably be good to introduce a new parameter that with its default value maintains the current behavior, and is settable to get the "improved" behavior.

**Comment by OrganicIrradiation** [comment]
@Legendin You can always use the freeimage plugin, which works fine:

```python
import numpy as np
import imageio

arr = np.full((32, 32), 256, dtype=np.uint16)
imageio.imwrite("16-bit_test.png", arr, format='PNG-FI')

img = imageio.imread("16-bit_test.png", format='PNG-FI')
print(img.dtype)
```

Returns uint16

**Comment by Legendin** [comment]
@OrganicIrradiation Thank you for the input! You are indeed correct in that freeimage produces the desired result, but as it is not / no longer the standard backend I still think developing a patch for the Pillow plugin is warranted. Maybe even more so because your findings reveal undocumented differences between the backends.

In any case I agree with @almarklein that the old behaviour should probably be left as standard for now. to avoid breaking someone's workflow. I've been unusually busy over the last couple of weeks, but I'll be able to work on implementing a keyword parameter switch for the new behaviour soon™. I'll also put a reference to this in the documentation.

**Comment by almarklein** [comment]
@LandingEllipse are you still interested in picking this up?

**Comment by LandingEllipse** [comment]
Hi @almarklein,

 Thank you for your patience; it seems life got in the way of my good intentions with this one. 

I was initially a bit hesitant to delve into the task as I wasn't too familiar with the code base. However nearly a year has gone by and I've been using imageio extensively (and encountered the issue at hand in a few more use cases in the process), so I do definitely still want to pick this up.

I should have time this month to implement the necessary changes, and I'll move the issue to the priority list so it won't slip back to the back burner...

**Comment by almarklein** [comment]
This is resolved right?
