### ISSUE TITLE
Fits Support

### ISSUE THREAD

**Issue by burhankhanlodhy** [imageio/imageio#477]
I am currently trying to save a fits file but, it's giving me an error that `OSError: FITS save handler not installed
` While I already have numpy and astropy installed. Can you please provide example code to give an idea on how to save a fits file?
My code:
`import rawpy
import imageio
raw = rawpy.imread('E:\FYP\cr.cr2')
rgb = raw.postprocess()
imageio.imwrite('E:\FYP\cr.fits', rgb)`

**Comment by burhankhanlodhy** [comment]
I have tried calling the `FitsStubImagePlugin.register_handler(handler=fits)
` But, still problem isnt solved

**Comment by almarklein** [comment]
This message does not come from imageio. My guess is that it comes from Astropy, though I cannot find it when searching its Github repo. I'm not familiar with FIT myself. My advice would be to run this with a debugger to see where it originates.

Also, you should probably use *raw strings* to define Windows paths (e.g. r'E:\FYP\cr.cr2'), because the backslashes may escape its next character (eg. 'E:\FYP\aa.cr2' would fail).

**Comment by almarklein** [comment]
Closing as it's not likely an upstream issue. Please re-open if you disagree :)
