### ISSUE TITLE
Generate video before closing with FFMPEG writer

### ISSUE THREAD

**Issue by carpemonf** [imageio/imageio#537]
Is there away to create intermediate video files before executing `W.close()?` In the example below, I would like to use the data appended to the writer for checking the video as it is generated. This code creates `test.mp4` at the writer definition but it is not longer modified until `W.close()` which I guess is the expected behavior.

Thank you.

```
import time
import numpy as np
import imageio

W = imageio.get_writer("test.mp4")
for i in range(12):
  W.append_data(np.zeros((128, 128, 3), np.uint8))
  time.sleep(10)
W.close()
```

**Comment by almarklein** [comment]
What happens as you write a video file, is that Python handles the frames (when you call `append_data`) to `ffmpeg`, which runs in a subprocess. The `ffmpeg` decides when data is written to disk. It will likely first accumulate some frames so that it can generate a key-frame followed by diff-frames.

So ... not really. If you want to view the video as it is being created, this *may* be possible, but expect to not see the last few frames yet. Also, not all formats/players allow viewing a video that is incomplete.

**Comment by almarklein** [comment]
What is the intention behind this question? Perhaps there is another way to achieve what you need.

**Comment by carpemonf** [comment]
Thanks @almarklein for your reply. Good to know, I will check if changing fps and number of images is a solution for me. With this specific example the write only happened at the end with the `close` command. I expect playing the video with `ffplay` for `MP4` which worked for me for other approaches.

The idea is encoding a video on-the-fly (using Python) as the images are generated by another program. So basically I do an `append_data` as the images are generated and looking forward for a solution where I can control the frequency of the encoding. For instance, something such as `W.save()` would be helpful. I have been thinking of doing that manually, although not optimal, by keeping one writer opened and using another thread for closing a copy of this writer when needed.

**Comment by almarklein** [comment]
The `ffmpeg` process might also buffer its output and not flush it that often. That's something we do not control at all. Unless perhaps `ffmpeg` has command line arguments to flush to disk more often or something.

**Comment by carpemonf** [comment]
If I'm not wrong `-flush_packets` can be used for writing inmediately - although not a good idea for I/O with high frequency image generation but useful in some cases. I passed this flag as an argument through `input_params` but it failed:

```
Output file #0 does not contain any stream
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/imageio_ffmpeg/_io.py", line 479, in write_frames
    p.stdin.write(bb)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test3.py", line 7, in <module>
    W.append_data(np.zeros((128, 128, 3), np.uint8))
  File "/usr/local/lib/python3.7/site-packages/imageio/core/format.py", line 492, in append_data
    return self._append_data(im, total_meta)
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 571, in _append_data
    self._write_gen.send(im)
  File "/usr/local/lib/python3.7/site-packages/imageio_ffmpeg/_io.py", line 486, in write_frames
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
/usr/local/lib/python3.7/site-packages/imageio_ffmpeg/binaries/ffmpeg-osx64-v4.2.2 -y -f rawvideo -vcodec rawvideo -s 128x128 -pix_fmt rgb24 -r 1.00 -flush_packets -i - -an -vcodec libx264 -pix_fmt yuv420p -crf 25 -v warning $HOME/imageio/test.mp4

FFMPEG STDERR OUTPUT:
```

**Comment by FirefoxMetzger** [comment]
@carpemonf Is this still a problem for you, or did you manage to solve the issue?

If your goal is to simply pipe the video into another program while it is being generated, then using a socket as an endpoint instead of a file will be much faster. You can check the ffmpeg protocols documentation [here](https://ffmpeg.org/ffmpeg-protocols.html) and see if any of the formats are supported by your downstream application. Streaming instead of writing to disk should do exactly what you want and may send data as frequently as every frame (depending on the encoding and streaming protocol used, ofc).

If this helps (or if you already solved the problem otherwise) let me know and I will close the issue. If I don't hear anything in the next couple of days, I will simply assume it is solved and close the issue, as well. If it isn't, feel free to reach out and we can re-open it.
