### ISSUE TITLE
read image directory from AWS S3 bucket

### ISSUE THREAD

**Issue by CindyQi7788** [imageio/imageio#541]
I used AWS s3path to read a AWS S3 bucket folder containing all the dicom images. 

I use AWS Sagemaker notebook to run imageio. 

However imageio.volread() can not recognize the 's3://mybucket_folder/' because it automatically add the current SageMaker folder directory in front of the S3 bucket folder path. 

Please let me know how to load multiple dicom images from S3 bucket to AWS sagemaker notebook by imageio. 

Thank you very much.

**Comment by almarklein** [comment]
The feature to read a DICOM volume from multiple images in a folder only works for folders on your file system, not for url's. So you'd have two options:

* First download the data to a local folder (manually, or with Python), then call imageio on that.
* Read the individual DICOM files from their url's, and then pack them into a 3D array.

**Comment by CindyQi7788** [comment]
Thanks for the reply! 

Xin

**Comment by FirefoxMetzger** [comment]
Picking this up again, I am a bit confused by the URI `'s3://mybucket_folder/'`. `s3` is not a valid protocol for our requests, and I did some googling, but couldn't find any reference. All buckets seem to be referred to via `https://s3.Region ...` or `https://bucketName.s3. ...`.

@almarklein Do you happen to know what the `s3` protocol does and where it is documented? If not, I think there is no further action needed, since the original question was answered. In that case, I think we can close this issue as resolved.

The ability to read multiple files from a folder (for DICOM) is something we will have to discuss separately since it collides a bit with the inability of other formats to read from folders, and we should find a smooth way to integrate this. In particular, we need to think about edge cases like `iio.imread('')` being expanded to the current directory and being confusing.

**Comment by almarklein** [comment]
Might be that this AWS Sagemaker uses this url format. Regardless, I think we can indeed close this.
