### ISSUE TITLE
Potential unspecific error message while writing large pillow image into file using imwrite

### ISSUE THREAD

**Issue by CielAl** [imageio/imageio#543]
Environment: Windows 18363.959
Python  3.7.4
imageio                  2.6.1
Pillow                   6.2.2
numpy                  1.19.0

I haven't confirmed it with more test yet, but it appears that in certain circumstances, potentially when memory is sufficient, conversion between Pillow and Numpy arrays using `np.asanyarray`/`np.array`/`np.asarray` yield a numpy array of `Image `object with `dtype('O')`, and thus failed the test in https://github.com/imageio/imageio/blob/master/imageio/core/functions.py#L293
and reports "Image is not numeric, but Image", which can be confusing.

I tested it with an image of 80000 x 80000 x 3. It doesn't seem to raise the exception when the memory is sufficient even with the exact same images.

**Comment by almarklein** [comment]
I can indeed reproduce this. On a 32-bit Python implementation:

```py
import numpy as np
import PIL.Image

im1 = PIL.Image.new("I", (100, 100))
im2 = np.asanyarray(im1)

print(im1)
print(im2.shape, im2.dtype)

im3 = PIL.Image.new("I", (20000, 20000))
im4 = np.asanyarray(im3)

print(im3)
print(im4.shape, im4.dtype)
```

Produces:
```
<PIL.Image.Image image mode=I size=100x100 at 0xC5A7530>
((100, 100), dtype('int32'))
<PIL.Image.Image image mode=I size=20000x20000 at 0xC5A7C10>
((), dtype('O'))
```

**Comment by almarklein** [comment]
I find it somewhat disturbing that `np.asanyarray()` has a different result when there is too little memory, instead of raising `MemoryError`.  Not sure what we could do about this, to be honest ...

**Comment by FirefoxMetzger** [comment]
Does the same happen with `np.asarray`?

Regarding `np.asanyarray` I wouldn't be too concerned actually since it is all expected behavior. It is a niece function that exists to explicitly allow array sub-types like `dtype=object` (I think `MaskedArray` lives here, too). In the case of `object`, the array is essentially just some metadata and one (or many) pointers to `pyobject`s. In this case, the pillow `Image` isn't copied, and - since `Image` fits into memory - so do a couple extra bytes of `ndarray` metadata (the raw data is re-used). Since there is enough memory to fit everything no `MemoryError` needs to be raised.

The solution is to simply _not_ use `asanyarray` and instead use `asarray`, which ensures that we get a non-derivative type, aka. an actual `np.ndarray`. I haven't tested this version, but I suspect that it will consistently raise a `MemoryError` if the image doesn't fit.

**Comment by almarklein** [comment]
I just tested `np.asarray` on a 32bit Python. I had to install a fresh version, and not I found that a `MemoryError` is raised also for `np.asanyarray`. So it looks like this has been fixed downstream (in either numpy or Pillow).

For the record: tested with Python 3.8.10, Numpy 1.21.0.
