### ISSUE TITLE
Creating Array from preexisting Array drops metadata

### ISSUE THREAD

**Issue by anntzer** [imageio/imageio#544]
```python
>>> import numpy as np, imageio
>>> t = imageio.core.Array(np.array([1, 2]), meta={"foo": 1})
>>> (t * 2).meta
Dict([('foo', 1)])
>>> t[:].meta
Dict([('foo', 1)])
>>> imageio.core.Array(t).meta
Dict()
```
Given that most operations on an Array appear to just keep the metadata as is, it seems reasonable to expect that creating a new Array from a preexisting one, without explicitly setting new metadata, should also keep the original metadata.

**Comment by almarklein** [comment]
> it seems reasonable to expect ...

This depends on the situation. We've chosen to explicitly not do this. If you want to keep the metadata, keep your own reference using the image that imageio returns.

**Comment by anntzer** [comment]
OK, I'll give another try at arguing for this.
Currently, if you add two Arrays, imageio keeps the metadata of the first array and drops the second:
```
In [2]: (imageio.core.Array(np.array([[1]]), meta={"foo": 1}) + imageio.core.Array(np.array([[2]]), meta={"bar": 2})).meta
Out[2]: Dict([('foo', 1)])
```
but it is rather unlikely that `{"foo": 1}` is the correct metadata for the sum!  Well, it's not *impossible*, but certainly it is more likely that a simple copy would not invalidate the metadata.

**Comment by almarklein** [comment]
Ah, I must have rushed a bit when I read the original question. You mean that `imageio.core.Array(t).meta` does not take over the metadata of `t`, even though that would be expected.

That makes sense, and a PR is welcome to fix it. Otherwise I'll likely fix it when I spend some free cycles on imageio maintenance.  Note though that we want to make major changes to how metadata is handled in imageio.
