### ISSUE TITLE
Build imageio without ctypes

### ISSUE THREAD

**Issue by oeway** [imageio/imageio#580]
Hi, I would like use imageio in Pyodide but it has been currently disabled because of the issue related to `ctypes`. As I understand, an issue was encountered when building imageio as a dependency of scikit-image in Pyodide ([see here for the issue in the scikit-image PR](https://github.com/iodide-project/pyodide/pull/866#issuecomment-746021613)). 

Can someone please take a look and see if we can make ctypes as an optional dependency for imageio? Maybe allowing a build flag to mask out `freeimage` plugin?

**Comment by almarklein** [comment]
The freeimage plugin indeed uses ctypes. There already is a plan to move that to its own repository. But I'm not 100% sure whether there are other plugins that use ctypes.

**Comment by FirefoxMetzger** [comment]
I just checked Pyodide and they seem to happily depend on the latest ImageIO. The plugin that is discussed in this issue (freeimage) still uses ctypes, but is now optional and dynamically imported only if needed.

I will close this issue because it appears to be solved, but if it isn't please feel free to let me know and I will reopen.
