### ISSUE TITLE
Reading GIF returns no color channels axes

### ISSUE THREAD

**Issue by danijar** [imageio/imageio#600]
I think imageio sometimes does not read compressed GIFs correctly.

I would expect the output of `imageio.mimread('animation.gif')` to always return an array with four axes for time, width, height, and channels. However, some of the GIFs I'm trying to process return an array with only three dimensions.

This can be reproduced with [this example GIF](https://user-images.githubusercontent.com/2111293/108618859-78714800-73ef-11eb-8928-03e8dfb8581a.gif) and also with a solid-color GIF as shown in the minimal example below:

```python
import imageio
import numpy as np

imageio.mimsave('animation.gif', np.zeros((20, 64, 64, 3), np.uint8))
np.array(imageio.mimread('animation.gif')).shape  # (20, 64, 64)
```

**Comment by FirefoxMetzger** [comment]
By default, we aim to return the raw pixel value stored in the file whenever possible; we don't want to make assumptions about how you will use the image and RGB isn't always the correct choice. For `.gif` - a palleted format - this translates into returning the pallet values stored in the file. 

`.gif` uses `pillow` as a backend, so you could normally specify `pilmode="RGB"`, have the pallet values looked up for each frame, and the result converted to RGB. I tried this, but unfortunately `pilmode` is not a valid keyword argument for `gif`. This is a bug we'll need to fix.

From here you have 3 options:

1. Wait for us to fix the bug. I've identified the fix, but merging will have to wait until after #595 (our new CI) is merged.
2. We are upgrading the API to work more fluently with nd-images and are combining `imread`, `mimread`, and `volread`. The PR (#574 ) works, but I am still writing tests. You could give this one a shot and, if you wanted, give us feedback on the design. With it, you can load your image via `imageio.new_api.imread("animation-gif", legacy_api=False, mode="RGB")` which will return a numpy array of shape `(160, 675, 1200, 3)`.
3. Implement the fix yourself and update once the fix (option 1) got merged. 

To implement the fix yourself, you'd have to find your imageio installation and navigate to `imageio/plugins/pillowmulti.py` and remove lines 58 - 60:
```
    class Reader(PillowFormat.Reader):
        def _open(self, playback=None):  # compat with FI format
            return PillowFormat.Reader._open(self)
```

Afterward, you can use `pilmode` to select the color format via

```
import imageio as iio
import numpy as np

image = np.asarray(iio.mimread("animation.gif", pilmode="RGB", memtest="2GB"))
# image.shape = (160, 675, 1200, 3)
```

Here `memtest` specifies the maximum size of the resulting list in memory; the default is `256MB`. This option exists to prevent crashes when carelessly applying `mimread` to a video file (`ffmpeg` backend), which would otherwise decompress the entire video and load it into memory. Something which would be troublesome on many devices.

**Comment by danijar** [comment]
Thanks a lot! I'm using the manual fix for now and will update `imageio` once it's merged.
