### ISSUE TITLE
width/height appears to get swapped on imwrite

### ISSUE THREAD

**Issue by anthony-sarkis** [imageio/imageio#626]
```
## pillow 8.2.0 
## imageio 2.9.0
## python 3.7.4 

import imageio
image = imageio.imread("in4.jpg")
imageio.imwrite("out.jpg", image)
print(image.shape)
```

![width height swapped on save](https://user-images.githubusercontent.com/18080164/114486595-0b925700-9bc3-11eb-962f-ce7beaf48aa4.PNG)

It prints the shape as `(4032, 1960, 3)`. This is the correct (height, width, channels). However then it proceeds to save it as width first.

Here's the image:
https://drive.google.com/file/d/1et_VG8UJfhG_hYM4NSd-FA26rQ3-yqzx/view?usp=sharing

**Comment by FirefoxMetzger** [comment]
This is a known issue that comes from the image's metadata; in particular the orientation flag.

`in4.jpg` stores the pixels as a `(1960, 4032)` image on disk and sets the orientation flag to `6` (rotate 90 degrees and mirror). Imageio then loads the image and applies the orientation flag to the data so that you can use it as you would expect. When later saving the image the metadata is copied from the original image, but the new (correctly rotated) data is used. The resulting mismatch between orientation flag and pixel data ends up causing the behavior you can observe (the Windows image previewer rotating the image).

Metadata is an open problem in imageio; mainly due to the large heterogeneity of metadata across formats. Once there is a clear vision on how metadata should be handled, this will likely get resolved in the process. Here are related issues: 
https://github.com/imageio/imageio/issues/371
https://github.com/imageio/imageio/issues/362
https://github.com/imageio/imageio/issues/501

If you don't need the image's metadata, you could simply drop it which would solve the problem in this particular instance:

```python
import imageio
import numpy as np
image = imageio.imread("in4.jpg")
imageio.imwrite("out.jpg", np.asarray(image))
```

If you need the metadata, you can drop the orientation flag only (since it no longer applies), or rotate the data before saving. YMMV, since this is rather application dependent.

**Comment by anthony-sarkis** [comment]
Thank you very much for the detailed information!
