### ISSUE TITLE
Roadmap to ImageIO v3

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#644]
With the basics of the new API in place, there are a few more things that need doing and then we can release a new version of imageio.

Here is a (loose) checklist. Please feel free to make additions:

- [x] Set up a CD pipeline (I've been thinking a lot about [semantic versioning 2.0.0](https://semver.org/)) Maybe it is worthwhile here?
- [x] Fix issue #640 
- [x] Fix issue #643 
- [x] Fix issue #641
- [ ] Add depreciation warnings to v2 functions

**Comment by FirefoxMetzger** [comment]
@almarklein What are your thoughts about this library: https://github.com/semantic-release/semantic-release

Could it be useful for us to set up a CD pipeline?

**Comment by almarklein** [comment]
At first glance my feeling is that the tool you mentioned is overkill, and the fact that it tries to determine how the version should be bumped based on commit messages seems like it might also work against us.

I am not against some form of automation, but since imageio is pure Python, the release procedure is already quite easy, so I would warn against overdoing it and thereby locking us into a certain toolchain. Some ideas for inspiration:
* Run a CD build when a tag named `v...` is pushed, that makes a GH release, and a package that is pushed to pypi (like e.g. [here](https://github.com/pygfx/wgpu-py/blob/main/.github/workflows/ci.yml#L164)).
* Another idea, since imageio is pure Python, is to create a script that does the release locally: bump the version, git tag that commit, pushes that to github, builds a wheel and pushes that to pypi (like e.g. [here](https://github.com/almarklein/timetagger/blob/main/tasks.py#L129)).
* I know some packages (skimage?) auto-generate release notes based on closed issues and PR's. Very interesting, but the amount of activity (once this big refactoring is over) might not be high enough for this to be worth the effort?

**Comment by almarklein** [comment]
All this said, if that tool (or another) is easy to set up and does not have too much implications elsewhere, feel free to give it a spin.

**Comment by FirefoxMetzger** [comment]
> I would warn against overdoing it and thereby locking us into a certain toolchain

I have the same concerns; I'd like to remain lightweight and flexible. It could be that I am keen on some kind of framework, because I have much more experience with Dev than with Ops, so whenever I get to delegate Ops responsibility I'm happy. Perhaps that skews my view.

At the same time, I really like a lot of the core ideas they propose and started adopting some outside of using the tool. Most prominently I started "tagging" commit messages depending on the type (MAINT/DOC/TEST/FEAT/BUG/... loosely based on what scipy is doing). This started as a test to see how I like it without committing to a framework, and now I have started defaulting to it because it is surprisingly handy. Tracing bugs is much easier and, weirdly enough, it makes commit messages shorter. I guess releases are based on these tags where FEAT commits release a new version minor, and `BREAKING CHANGE` releases a new version major. Everything else increases the bug counter or doesn't affect the version?

In any case, we can roll with a simpler CD toolchain. I'd still advocate releasing a new version after each commit so that changes are made available asap and don't idle forever (for example our last release was more than 1 year ago). Not sure how we should handle the associated version number in this case; I like most of the proposal of semantic versioning 2.0.0 but this is again me deligating responsibility, so I'm happy to hear about alternatives :)

**Comment by almarklein** [comment]
Yeah, we should release more often. Automating some of it would make that easier. I'm not sure if automatically doing a release on each commit is necessary, but I guess you're right in that it might just make things easier. Semver is fine for me.

**Comment by FirefoxMetzger** [comment]
@almarklein I can use the pillow vulnerability as another opportunity to lobby for a fully automated CD pipeline :laughing: 

I have set one up over at [scikit-bot](https://github.com/FirefoxMetzger/scikit-bot/blob/main/.github/workflows/cd.yml) and I've been quite happy with it. There are a few tweaks (e.g. I would trigger it nightly instead of triggered by commit) and a better/neater changelog would be nice), but the general idea of documenting changes by commit messages has quite a few nice implications :)

If this is interesting we can set something similar up here.

**Comment by almarklein** [comment]
Sure, if you want to have a go with that, I won't stop you ;)

**Comment by FirefoxMetzger** [comment]
Closing this in favor of #725 . Everything here is sorted except for deprecation which is discussed in the referenced issue.
