### ISSUE TITLE
'import imageio' on M1 MacBook with Python 3.9 causes "MemoryError" - installed with conda/pip

### ISSUE THREAD

**Issue by slerman12** [imageio/imageio#665]

**Comment by slerman12** [comment]
```
Python 3.9.1rc1 | packaged by conda-forge | (default, Nov 28 2020, 22:21:58) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/samlerman/code/miniforge3/lib/python3.9/site-packages/imageio/__init__.py", line 38, in <module>
    from . import plugins
  File "/Users/samlerman/code/miniforge3/lib/python3.9/site-packages/imageio/plugins/__init__.py", line 87, in <module>
    from . import freeimage
  File "/Users/samlerman/code/miniforge3/lib/python3.9/site-packages/imageio/plugins/freeimage.py", line 13, in <module>
    from ._freeimage import fi, download, IO_FLAGS, FNAME_PER_PLATFORM  # noqa
  File "/Users/samlerman/code/miniforge3/lib/python3.9/site-packages/imageio/plugins/_freeimage.py", line 1332, in <module>
    fi = Freeimage()
  File "/Users/samlerman/code/miniforge3/lib/python3.9/site-packages/imageio/plugins/_freeimage.py", line 428, in __init__
    def error_handler(fif, message):
MemoryError
```

**Comment by slerman12** [comment]
Hi, is there still a known bug with M1 Mac? I get the following error:

`RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.`

**Comment by FirefoxMetzger** [comment]
@slerman12 Your error doesn't sound like it is related to this issue. Instead, you simply didn't perform the post-install step needed to get the ffmpeg plugin. In the docs on the ffmpeg plugin you can find how to do this: https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.ffmpeg.html#module-imageio.plugins.ffmpeg

**Comment by slerman12** [comment]
The strange thing is I definitely have installed imageio-ffmpeg.

```console
pip install imageio-ffmpeg
```

However, when I run the recommended install `pip install imageio[ffmpeg]`, I get this error, might be a mistake:
`zsh: no matches found: imageio[ffmpeg]`.

**Comment by FirefoxMetzger** [comment]
@slerman12 Which version of ImageIO are you using?

**Comment by slerman12** [comment]
I tried the latest version and `2.9.0`.

**Comment by slerman12** [comment]
Is it possible that it's because I installed within a conda environment?

**Comment by slerman12** [comment]
I had it installed in conda, but through pip. I uninstalled from pip, re-installed with conda, and it works. :)

**Comment by slerman12** [comment]
Dang. Is there any way to get it to work through pip? My school cluster seems to bug for some reason when I enable the conda-forge channel. I'm using a conda .yml file which downloads `imageio` and `imageio-ffmpeg` through pip.

**Comment by FirefoxMetzger** [comment]
Conda is something I never really picked up. My projects live either in a venv (via poetry) or bare-metal so this is, unfortunately, outside of my area of expertise. However, @anjos might know.

@anjos The problem is that @slerman12 is installing imageio and imageio-ffmpeg through pip into a conda environment, and that imageio doesn't find the ffmpeg executable afterwards. Do you know why this could be and if there is an easy fix for it?

**Comment by anjos** [comment]
Likely, the base conda environment @slerman12 is installing imageio-ffmeg does **not** contain the `ffmpeg` binary.  If you install `ffmpeg` on that environment, does that fix it?

The conda-forge `imageio-ffmpeg` [has a direct dependence on ffmpeg](https://github.com/conda-forge/imageio-ffmpeg-feedstock/blob/main/recipe/meta.yaml#L27).  This level of control  is possible because conda/mamba can have non-Python dependencies (contrary to pip/setuptools).  For pip, I guess this must be manually handled somehow.
