### ISSUE TITLE
"Local" plugins

### ISSUE THREAD

**Issue by anntzer** [imageio/imageio#679]
I would like to be able to "locally" register a plugin, within a bounded context.  An example would be a library where I know, locally that I would be dealing with ".dat" / ".raw" files which actually have a certain binary format, so I want to register a plugin for these, but I don't want this plugin to affect the entire Python process (because ".dat"/".raw" could be anything, and I don't want to make promises for other modules in the same process that could also be using imageio).  IOW, I'd like something like (API names up to bikeshedding)
```python
def my_libs_public_api(path: Path, ...):
    # path can be a .dat/.raw, or perhaps any other format supported by imageio
    imopen_with_extra_plugins = imopen.with_plugins(extra_plugins)  # perhaps instantiated at module level
    with imopen_with_extra_plugins(path, "r") as file: return file.read()
```
I *think* this is "mostly" just a matter of having an extra class attribute `_instance_plugins`, which is checked before `_known_plugins`, have `with_plugins` return a new imopen instance with extra entries in `_instance_plugins`, and check `_instance_plugins` before `_known_plugins` in `imopen.__call__`.

Thoughts?

**Comment by FirefoxMetzger** [comment]
There is a chance that I don't fully understand your use-case yet, so my thoughts may not apply here.

First off, are we talking about old-school style plugins (imageio v2) or new style plugins (upcoming imageio v3)? The old style is [documented here](https://imageio.readthedocs.io/en/stable/development/plugins.html#what-is-a-plugin) and the new style is currently undocumented, but you can find an example implementation for pillow [here](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py). Documentation will come soon™, but certainly before v3.

For old style plugins you will have to implement `_can_read` and `_can_write`, which could check the beginning of the file instead of or in addition to the extension when deciding if they can handle the file. We already have several formats (via FreeImage and LYTRO) using `.raw` that coexist and - to my knowledge - get sorted out correctly using this method. 

For reading, we might check if your plugin can read a RAW file, but then move on, because your plugin will reject it.  FOr writing it is generally best practice to specify the full name of the format in `format=` instead of the extension to avoid exactly this situation with aliased extensions.

New style plugins work the same, except that they do this test (and potentially others) upon construction and raise a `InitializationError` if anything goes sideways, e.g., the plugin can't read/write the file.

Would that do the trick in your case?

---

On the note of registering plugins, I am currently reworking the backend for that a bit (no PR yet, so no link). The motivation here is to sync `imopen`, `FormatManager` and the docs and also to add some nice to haves: (1) extension-specific plugin priority, (2) lazy loading / importing of plugins upon first use, and other goodness.

This will make use of the new `imageio.config` module to hold the global config of known extensions and plugins (which will undergo some change compared to what it is now). There are a number of advantages to doing this, one of which is that you can solve your problem by adding (and later removing) your plugin from the config module.

Doing this inside your library could look something like this, assuming you pick a unique name for the plugin:

```python
from contextlib import contextmanager
from imageio.config import known_plugins, known_extensions, PluginConfig

config = PluginConfig(...)
supported_extensions = [".raw", ".dat"]

@contextmanager
def register_my_plugin():
    known_plugins[config.name] = config

    for ext in supported_extensions:
        # insert with highest priority (checked first, fallback to rest on fail)
        known_extensions[ext].priority.insert(0, config.name)

    yield

    for ext in supported_extensions:
        known_extensions[ext].priority.remove(config.name)

    known_plugins.pop(config.name)
```

and then you can use it in places you need as:

```python
iio.imread(..., plugin="my_plugin") #raises ValueError, because plugin is not registered

with register_custom_plugin():
    iio.imread(myfile.raw)  # should try your plugin first, based on .raw extension
    iio.imread(..., format="my_plugin")  # forcing the plugin v2 style
    iio.imread(..., plugin="my_plugin")  # forcing the plugin v3 style

iio.imread(..., plugin="my_plugin") #raises ValueError, because plugin is not registered

```

**Comment by anntzer** [comment]
Thanks for the extensive reply.

Re: new/old plugins: it doesn't really matter for me; I wrote the example code against the new API but I'm fine with whatever you prefer.

I am specifically considering the case of reading here (I guess the considerations are different when writing).  In my case, I have no real way of knowing whether a file was indeed produced by the camera (let's call it camera X) I want or not, because the format is literally a raw dump, except for the first few bytes which indicate the frame size (OK, technically, I can check whether the total file size is a multiple of the frame size, but I could have trailing bytes sometimes too; anyways, the format is not really something I can do anything about...).  So the documented interface on my library's side is "pass a file name; the following formats are supported: $fmt, $otherfmt, and raw; raw files are ASSUMED to be produced by camera X; no guarantees whatsoever if they are not".  So it's kind of a sharp edge, and that's also why I want to limit the plugin effect to my function and not have it leak out to anywhere else.

Explicitly passing the plugin to imread() is a good idea, although in that case I would suggest supporting directly passing plugin classes as the plugin kwarg, and completely skip the registration step; this way I could write something like (again, approximately)
```python
def my_imread(path, ...):
    if path.suffix == ".raw":
        # no global registration, no effect anywhere outside of this function,
        # no need for context-manager API, no thread-safety issues
        return imageio.imread(path, plugin=MyPlugin)
    else:
        return imageio.imread(path)
```

**Comment by FirefoxMetzger** [comment]
> I would suggest supporting directly passing plugin classes as the plugin kwarg

I like this idea. You can already skip the plugin manager and instantiate plugins directly via

```python
request = iio.core.Request(path, "r")
with MyPlugin(request) as img_file:
    # context manager for resource cleanup
    return img_file.read(...)
```

However, I do agree that a one-liner would be cleaner:

```python
return iio.imread(path, plugin=MyPlugin)
```

The changes would essentially be to add an a branch here

https://github.com/imageio/imageio/blob/f3fa6318ebd6005ebf2361438795cfbf87e62f7c/imageio/core/imopen.py#L84-L95

update the function's signature (and docstring)

https://github.com/imageio/imageio/blob/f3fa6318ebd6005ebf2361438795cfbf87e62f7c/imageio/core/imopen.py#L42

and add a unit test for the new behavior. An example for the docs could also be useful, too, so that others may see how this is supposed to work.

Anything I am missing @anntzer ?

**Comment by anntzer** [comment]
I think that looks good, at least as a first step, to me.

**Comment by FirefoxMetzger** [comment]
Awesome.

@almarklein Any objections to extending support of `plugin` in `imopen(..., plugin=...)` to allow plugin objects as input?

@anntzer Would you be interested in contributing this feature?

**Comment by anntzer** [comment]
Not now, but I'll keep this somewhere in the back of my mind.
