### ISSUE TITLE
AttributeError: module 'imageio.plugins' has no attribute 'freeimage'

### ISSUE THREAD

**Issue by KelSolaar** [imageio/imageio#690]
Hello,

I have started to get [CI failures](https://github.com/colour-science/colour/runs/4270969224?check_suite_focus=true#step:8:177) today, most likely due to some changes introduced by *imageio 2.11.0*.

I usually install the Freeimage plugin as follows:

```bash
poetry run python -c "import imageio;imageio.plugins.freeimage.download()"
```

Which now raises an exception:

```python
AttributeError: module 'imageio.plugins' has no attribute 'freeimage'
```

**Comment by FirefoxMetzger** [comment]
Try

```python
poetry run python -c "import imageio;imageio.plugins.freeimage.download()"
```

it works on my local version without error, so that should be an initial solution/workaround. I have FreeImage installed already, but that shouldn't make a difference here.

---

2.11.0 stops importing all plugins immediately; instead, plugins are lazy-imported on first use. This makes ImageIO (marginally) faster, but also means you won't have to deal with plugin-specific problems (like random `MemoryError`s due to FreeImage https://github.com/imageio/imageio/issues/665) until you actually make use of that plugin. The downside is that `imageio.plugins` is now empty and that you have to explicitly import a plugin if plan to use it directly (instead of using a ImageIO API call).

I just had a quick look at the source, and the download function lives here

https://github.com/imageio/imageio/blob/e2a0363513c3d1d4699bf6206274deb9091796e7/imageio/plugins/_freeimage.py#L47-L67

At first glance, there doesn't seem to be anything in there that actually loads the library, so in theory, it should be possible to pull this out and place it back into the plugin namespace while - at the same time - avoiding to import FreeImage immediately. I'll have to test if `plugins.freeimage.download` and `plugins.freeimage` can happily coexist, or if that will cause problems.

Long term, we will move freeimage into a different repo to make all of the above cleaner. This should then allow you to 
 `pip install imageio[freeimage]`, which is arguably easier to maintain than `poetry run python -c "import imageio;imageio.plugins.freeimage.download()"` :)

**Comment by FirefoxMetzger** [comment]
@KelSolaar I've added a PR to bring back

```
poetry run python -c "import imageio;imageio.plugins.freeimage.download()"
```

We will have to internally discuss the solution I've chosen, so it might not be merged immediately. Either way, a solution has been identified and is on its way into one of the next releases :) In the meantime you can of course rely on the workaround I posted above.

**Comment by KelSolaar** [comment]
Hi @FirefoxMetzger,

I think it would be worthwhile to not break this API. Only speaking for us here, but we do use `python -c "import imageio;imageio.plugins.freeimage.download()"` in a lot of places, continuous integration, Docker containers, Ansible recipes, Jupyter and Colab Notebooks, etc...

It means that as of right now, all of this breaks. It is certainly our fault for not pinning specific versions but we do it purposely so that we can catch that type of issue as early as possible. Hope it makes sense!

Cheers,

Thomas

**Comment by FirefoxMetzger** [comment]
@KelSolaar It does make sense, and I agree.

It wasn't my intention to break this API, which is why there is a PR to bring it back and also why there was no deprecation warning. I develop against our CI because that's the best way to check if I broke anything, but that clearly isn't infallible. However, the CI does get better incrementally and #693 includes a new unit test to check for the availability of `imageio.plugins.freeimage.download()` and prevent this from breaking again.

**Comment by KelSolaar** [comment]
Thank you, this sounds awesome!

**Comment by FirefoxMetzger** [comment]
@KelSolaar CD just picked up the PR addressing the `imageio.plugins.freeimage.download()` problem and it should be fixed on pypi now. Could you try running your CI and see if it is resolved?

**Comment by KelSolaar** [comment]
@FirefoxMetzger : Awesome guys, confirming it works fine!

https://github.com/colour-science/colour/runs/4378240753?check_suite_focus=true
