### ISSUE TITLE
BytesWarning thrown in imread in 2.11.1

### ISSUE THREAD

**Issue by johnthagen** [imageio/imageio#694]
There seems to be a small regression when calling `imread` and enabling `BytesWarning`s ([-bb](https://docs.python.org/3/using/cmdline.html#cmdoption-b)):

```py
from pathlib import Path

import imageio

image_bytes = Path("image.png").read_bytes()
image = imageio.imread(image_bytes)
```

Run with:

```
python -bb test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    image = imageio.imread(image_bytes)
  File "venv/lib/python3.9/site-packages/imageio/core/functions.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "venv/lib/python3.9/site-packages/imageio/core/imopen.py", line 221, in imopen
    plugin_instance = config.plugin_class(request, **kwargs)
  File "venv/lib/python3.9/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "venv/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 64, in __init__
    f"`{self._format.name}`" f" can not read `{self._request.raw_uri}`."
BytesWarning: str() on a bytes instance
```

Enabling `BytesWarning`s helps users catch `str`/`bytes` confusion in their own code.

### Environment

Python 3.9.8

```
pip list
Package    Version
---------- -------
click      8.0.1
imageio    2.11.1
numpy      1.21.4
pep517     0.10.0
Pillow     8.4.0
pip        21.3.1
pip-tools  6.4.0
setuptools 57.0.0
toml       0.10.2
wheel      0.36.2
```

**Comment by FirefoxMetzger** [comment]
The warning you shared points to us raising an exception when a plugin/backend can't read a resource:

https://github.com/imageio/imageio/blob/e2a0363513c3d1d4699bf6206274deb9091796e7/imageio/core/legacy_plugin_wrapper.py#L62-L65

I can see how this could be cryptic/undesirable if the exception surfaces for `bytes` since it would flood the console/log.

@johnthagen What do you think would be a good a cleaner error message here? `f"{self._format.name} can not read the provided bytes."`?

**Comment by johnthagen** [comment]
@FirefoxMetzger I think that error message could be a better fit.

Another option would be to check if `raw_uri` is `bytes` and try to `.decode()` or base64 encode it so it's a proper `str`.

But like you said, this would probably not be a useful error message as it could be very long and flood the screen.

I think what you propose would be the best solution for `bytes`.

**Comment by FirefoxMetzger** [comment]
This is a small change, but I think I won't be able to implement it in the next couple of days, because I am occupied with other work. 

@johnthagen Would you like to contribute this update? 

It would mean testing if the input is `bytes`, and if so, to then change the error message for the `InitializationError` I shared in the previous comment and the message of the exception for writing (below the one for reading).

I don't think we need an explicit unit test for this (since it is covered by `-b`), but that would of course be a welcome addition :)

**Comment by FirefoxMetzger** [comment]
I implemented a fix locally; however, I currently have to call pytest via `python -bb -m pytest` to make sure a `BytesWarning` is raised.

@johnthagen Do you know if there is an option in pytest itself to enable `BytesWarning`s?

**Comment by johnthagen** [comment]
@FirefoxMetzger I have only ever used the `-bb` flag. I think this might be a special case for the interpreter?

You could check the `warnings` module to see if it's configurable there.
