### ISSUE TITLE
ffmpeg.Reader._get_cam_inputname causes "ResourceWarning: unclosed file"

### ISSUE THREAD

**Issue by dennisvang** [imageio/imageio#697]
### Description

In my tests I keep seeing `ResourceWarning: unclosed file <_io.BufferedWriter name=3>`

With `PYTHONTRACEMALLOC=1`, here's what I get:

```
...\lib\site-packages\imageio\plugins\ffmpeg.py:303: ResourceWarning: unclosed file <_io.BufferedWriter name=3>
  self._filename = self._get_cam_inputname(index)
Object allocated at (most recent call last):
  File "...\lib\subprocess.py", lineno 935
    self.stdin = io.open(p2cwrite, 'wb', bufsize)
...\lib\site-packages\imageio\plugins\ffmpeg.py:303: ResourceWarning: unclosed file <_io.BufferedReader name=4>
  self._filename = self._get_cam_inputname(index)
Object allocated at (most recent call last):
  File "...\lib\subprocess.py", lineno 941
    self.stdout = io.open(c2pread, 'rb', bufsize)
...\lib\site-packages\imageio\plugins\ffmpeg.py:303: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  self._filename = self._get_cam_inputname(index)
Object allocated at (most recent call last):
  File "...\lib\subprocess.py", lineno 946
    self.stderr = io.open(errread, 'rb', bufsize)
```

### How to reproduce

On a Windows 10 laptop with built-in webcam (`<video0>`), using Python 3.9.7, `imageio` 2.11.0, `imageio-ffmpeg` 0.4.5, run the following test:

```python
from imageio import get_reader
import unittest

class ReaderTests(unittest.TestCase):
    def test_get_reader(self):
        reader = get_reader(uri='<video0>')
```

### Cause

Looking at the [source of _get_cam_inputname](https://github.com/imageio/imageio/blob/v2.12.0/imageio/plugins/ffmpeg.py#L209), and looking at the trace above, I suspect the issue is caused by the `stdin`, `stdout`, and `stderr` streams not being closed properly after use in `subprocess.Popen`.

### Proposed solution

Use `subprocess.Popen` as a context manager, to ensure streams are always properly closed, as suggested e.g. [here](https://stackoverflow.com/a/58696973).

Replace this ([source](https://github.com/imageio/imageio/blob/v2.12.0/imageio/plugins/ffmpeg.py#L228)):
```python
...
proc = sp.Popen(
    cmd, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE, shell=True
)
proc.stdout.readline()
proc.terminate()
infos = proc.stderr.read().decode("utf-8", errors="ignore")
...
```

by this:
```python
...
with sp.Popen(
         cmd, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE,
         shell=True) as proc:
    proc.stdout.readline()
    proc.terminate()
    infos = proc.stderr.read().decode("utf-8", errors="ignore")
...
```

**Comment by dennisvang** [comment]
... and I'm seeing a similar thing in [ffmpeg.Reader._close()](https://github.com/imageio/imageio/blob/v2.12.0/imageio/plugins/ffmpeg.py#L350).

**Comment by FirefoxMetzger** [comment]
@dennisvang Interesting find. Are you on the latest version of ImageIO?

**Comment by FirefoxMetzger** [comment]
I had a look and can reproduce this locally. I made two modifications to your MWE. One is cosmetic (execute unittest when the MWE is run), the other is I think an omission. When you use `get_reader`, you have to explicitly `close()` the file/reader when you are done, similar to the built-in `open` when used outside a context manager:

```python
from imageio import get_reader
import unittest

class ReaderTests(unittest.TestCase):
    def test_get_reader(self):
        reader = get_reader(uri='<video0>')
        reader.close()  # must close manually

if __name__ == "__main__":
    unittest.main()
```

Moving into the warning itself, we are indeed letting GC close the file streams for us in `_get_cam_inputname`. In CPython this is not a big issue, because GC will be run right after the function returns. Other python implementations (e.g., pypy) may rely on a different GC strategy, so - in the interest of not hoarding file pointers in long-running applications - we should indeed do a better job here.

Since our focus is python 3.6+, my preferred solution is to use `subprocess.run` instead of using a context manager around manually handling the subprocess. It makes for cleaner code:

```diff
--- a/imageio/plugins/ffmpeg.py
+++ b/imageio/plugins/ffmpeg.py
@@ -225,12 +225,10 @@ class FfmpegFormat(Format):
                 # Set `shell=True` in sp.Popen to prevent popup of a command line
                 # window in frozen applications. Note: this would be a security
                 # vulnerability if user-input goes into the cmd.
-                proc = sp.Popen(
+                result = sp.run(
                     cmd, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE, shell=True
                 )
-                proc.stdout.readline()
-                proc.terminate()
-                infos = proc.stderr.read().decode("utf-8", errors="ignore")
+                infos = result.stderr.decode("utf-8", errors="ignore")
                 # Return device name at index
                 try:
                     name = parse_device_names(infos)[index]
```

The above would resolve the warnings from `_get_cam_inputname`. The other warning from `_close()` traces into `imageio-ffmpeg`. Likely something similar is happening there; however, I am not familiar with that codebase, so I can't say much more at this stage.

Another thing I am not sure of is how to reproduce this test in the `pytest` framework. Once we have that worked out, we can add a regression test for it.

@dennisvang What are your thoughts on this approach, and would you be interested in submitting a PR for this?

**Comment by dennisvang** [comment]
@FirefoxMetzger : Good point about the `reader.close()`: my example was a bit too minimal there. I also agree that `sp.run()` would yield the cleanest code. On the other hand, I suggested using `Popen` as context manager because it stays as close as possible to the current implementation, just to be on the safe side. I believe `subprocess.run()` uses a slightly [different approach](https://github.com/python/cpython/blob/main/Lib/subprocess.py#L504), with `communicate()`, etc. Not sure if that could introduce other side effects. What do you think?

**Comment by FirefoxMetzger** [comment]
@dennisvang Hm, the main difference I see is that `communicate` will wait for the sub-process to close by itself, whereas the `Popen` route will explicitly close/kill the process. Potentially, this could recover if the subprocess gets stuck. However, we are calling

```
ffmpeg -list_devices true -f dshow -i dummy
```

here, followed by a `stdout.readline()` which we discard. This essentially just blocks the main process until the subprocess exits (since the command prints to `stderr` and will only print a single `\n` to stdout when it is done. To me, this looks like we are doing the same thing as `communicate` but in a more hacky/problem-specific way. However, it could be that I am missing something here?

That being said, I am happy with either solution and I think so will be the CI. If you want to implement the fix, feel free to choose the approach you find more suitable :)

**Comment by dennisvang** [comment]
@FirefoxMetzger It looks like you are right. I'll give it a try.

**Comment by dennisvang** [comment]
@FirefoxMetzger  Sorry it took so long, I had some other, more pressing concerns.

I tried to address the issue both here and in `imageio-ffmpeg`, see above.
