### ISSUE TITLE
Simplifying pytest markers/skip conditions for "no internet"

### ISSUE THREAD

**Issue by anjos** [imageio/imageio#700]
I'm trying to enable test runs in the conda-forge builds of this package, but I'm finding it hard to get the implementation right.

One of the reasons for this is that this package implements a way to check for internet access which is a bit unusual for a framework based on pytest.  As far as I could understand, if the value of the environment variable `IMAGEIO_NO_INTERNET` assumes a true value, then certain tests should be skipped.  This in turn is used inside `imageio/testing.py` to issue a `pytest.skip("No internet")` within a function called `need_internet()`, which is in turned used within each test inside `tests/`, which would require internet access otherwise.

Would it be possible to consider a simplification of this testing in which, instead of this system, you mark the tests that require internet with something like:

```python
@pytest.mark.requires_internet
def test_bla():
    ...
```

Then, you select tests with or without internet access with:

```sh
$ pytest -m "requires_internet" ... # all tests that require internet
$ pytest -m "not requires_internet" ... # all tests that do not require internet

```

**Comment by FirefoxMetzger** [comment]
> Would it be possible to consider a simplification of this testing in which, instead of this system, you mark the tests that require internet

Yes, it would certainly be possible and a very welcome refactor. The reason it is like this is that it was written in this way some 7 years or so ago, and nobody refactored it since. If you would like to do the refactor, I'm happy to do the reviewing 🚀 

---

While being on that topic @almarklein is there a deeper reason for being able to manually disable parts of the unit tests (that presumably need internet)? 

For some places, I know this happens because the test would like to download a standard image and, if there is no internet, the failed download would make the test fail. Those cases could, however, be better handled by downloading all test images one in a test-level fixture. If the fixture fails to download some images, we could simply skip associated tests.

There are also some tests that download backends, e.g. the FreeImage library, and that are guarded by `need_internet`. I don't know the motivation here though. Maybe it can be refactored by our effort/idea to migrate vendored backends into their own repos?

Are there other cases where we need `need_internet`?

**Comment by anjos** [comment]
Agreed.  If a refactor is to be considered, may be you can consider the following as well:

* The possibility to run the unit tests directly by calling pytest instead of passing by `invoke`, and requiring `pytest-cov` is installed together with `.coveragerc`, that is actually not packaged on the PyPI package
* Auto-skip markers for modules/tests requring extra python modules to be installed
* Removal of tests concerning ffmpeg, which could be moved to `imageio-ffmpeg` instead

Let me know.  I can prepare a PR with those.

**Comment by FirefoxMetzger** [comment]
> The possibility to run the unit tests directly by calling pytest instead of passing by invoke,

This should already be possible. I don't use `invoke` in my local setup at all and instead directly call `pytest` or `coverage run -m pytest`. Our CPython CI matrix calls `pytest` directly as well. Are you facing issues with this?

>requiring pytest-cov is installed together with .coveragerc, that is actually not packaged on the PyPI package

We shouldn't package the tests into the PyPI package/wheel, do we? What would be the advantage of shipping `.coveragerc` and adding `pytest-cov` as a requirement?

> Auto-skip markers for modules/tests requiring extra python modules to be installed

Yes, this would be nice. I think it will strongly correlate with the individual plugins, which may or may not have an optional backend as a dependency. This will become even more relevant in the future because backends will move into their own repo instead of being vendored here.

> Removal of tests concerning ffmpeg, which could be moved to imageio-ffmpeg instead

This is a tricky one. `imageio-ffmpeg` targeting the backend can move to `imageio-ffmpeg`, yes. However, tests that target the plugin itself will have to stay, since the plugin itself will continue to live here for the time being.

There are discussions about allowing and/or moving to entripoint-based plugin discovery, which would allow the plugin itself to live in a separate repo as well. It's a pretty cool suggestion, and in this case, we could think about migrating all of `ffmpeg`'s tests together with the plugin itself. I am, however, currently vetoing this suggestion though, because there are a few features in ImageIO that I am not sure how to easily migrate/integrate into such an approach.

So yeah, bottom line is that I am happy to move some of the `ffmpeg` tests to `imageio-ffmpeg` if it makes sense, but I doubt we can move them all, because the plugin lives in ImageIO and needs coverage.

> I can prepare a PR with those.

🚀 🚀 that sounds pretty awesome @anjos

**Comment by anjos** [comment]
> > The possibility to run the unit tests directly by calling pytest instead of passing by invoke,
> 
> This should already be possible. I don't use `invoke` in my local setup at all and instead directly call `pytest` or `coverage run -m pytest`. Our CPython CI matrix calls `pytest` directly as well. Are you facing issues with this?
> 
> > requiring pytest-cov is installed together with .coveragerc, that is actually not packaged on the PyPI package
> 
> We shouldn't package the tests into the PyPI package/wheel, do we? What would be the advantage of shipping `.coveragerc` and adding `pytest-cov` as a requirement?

This probably relates to my own ignorance on how to maintain this package - looking at the `ci.yaml` file, I got under the impression that `invoke` was required.  This seems to work, if ffmpeg and iomage-ffmpeg are not installed:

```sh
$ pytest -sv --ignore=tests/test_ffmpeg.py --ignore=tests/test_ffmpeg_info.py tests/
```

Please ignore that point.

> 
> > Auto-skip markers for modules/tests requiring extra python modules to be installed
> 
> Yes, this would be nice. I think it will strongly correlate with the individual plugins, which may or may not have an optional backend as a dependency. This will become even more relevant in the future because backends will move into their own repo instead of being vendored here.

OK.

> 
> > Removal of tests concerning ffmpeg, which could be moved to imageio-ffmpeg instead
> 
> This is a tricky one. `imageio-ffmpeg` targeting the backend can move to `imageio-ffmpeg`, yes. However, tests that target the plugin itself will have to stay, since the plugin itself will continue to live here for the time being.
> 
> There are discussions about allowing and/or moving to entripoint-based plugin discovery, which would allow the plugin itself to live in a separate repo as well. It's a pretty cool suggestion, and in this case, we could think about migrating all of `ffmpeg`'s tests together with the plugin itself. I am currently vetoing this suggestion though, because there are a few features in ImageIO that I am not sure how to easily migrate/integrate into such an approach.
> 
> So yeah, bottom line is that I am happy to move some of the `ffmpeg` tests to `imageio-ffmpeg` if it makes sense, but I doubt we can move them all, because the plugin lives in ImageIO and needs coverage.

Fair enough - I'll leave this bit to you then.

> 
> > I can prepare a PR with those.
> 
> 🚀 🚀 that sounds pretty awesome @anjos

**Comment by FirefoxMetzger** [comment]
Ah yes, I recall seeing some code in our setup.py that would download all standard images and build dedicated "offline wheels". Do you think it is worthwhile revisiting this behavior? I think that a person looking to get a version of ImageIO that works offline is likely not very interested in our standard image suite, but has something more specific in mind.

**Comment by almarklein** [comment]
> I recall seeing some code in our setup.py that would download all standard images and build dedicated "offline wheels". Do you think it is worthwhile revisiting this behavior? 

That's still there, is it not? It just includes a few small standard images. It slightly increases the size of the wheel, but in return you always have some test images on the system, which is nice for examples, or e.g. replicating certain issues.

> On second thought, I actually still don't understand why we would want to be able to turn off internet access in the test suite. 

Well, quite a few of our tests require an internet connection. E.g. some tests are specific to a particular test image which is downloaded on demand. We don't want *these* images in the wheels ...

Simply skipping a test when an internet request fails does not seem like a good idea. If there are networking errors, the tests pass even though you expected the whole suite to run. Better keep this explicit.

**Comment by FirefoxMetzger** [comment]
> That's still there, is it not?

Yes we still do that. If you think it is still relevant do have them, then lets keep them around.

> Simply skipping a test when an internet request fails does not seem like a good idea. If there are networking errors, the tests pass even though you expected the whole suite to run. Better keep this explicit.

That's a valid point; I didn't think about that at all. This is indeed enough reason to keep a switch like this around.
