### ISSUE TITLE
Reconsider release frequency policy

### ISSUE THREAD

**Issue by kmilos** [imageio/imageio#715]
It's great that we have more regular releases after such a long pause (thank you!), but can we please do them in a more meaningful way, i.e. real feature or bug fix, and perhaps when a couple of them accumulate? Like a monthly rather than a weekly/daily basis that seems to be done now via some automation as soon as a line changes somewhere in the repository?

I don't want to have to be reminded to re-package imageio for distribution constantly and to have to check changes just to find an URL update for example and then decide to skip it...

**Comment by FirefoxMetzger** [comment]
Hey @kmilos. Yes, a monthly release cycle is possible though I personally like a daily cycle because it means that there is little delay between having a bug fixed and having the fix propagate to whoever reported it. I like to imagine that this encourages contribution because you can benefit from your own work more easily.

The type of release is determined by a leading tag in a commit message FEAT/BUG/MAINT/DOC/... which also determines if a release should be made in the first place. For example, DOC releases won't trigger a release and simply accumulates until the next version-changing change is committed. What is currently missing in this setup, however, is a tag for dev/tooling changes, that also just accumulates. This is because, in my infinite wisdom (lol), I set up the `DEV:` commit to bump the version minor. This, however, can be fixed upstream, or we could run our own version parser locally (which may be the smart thing to do since we won't get surprised by upstream changing things).

Whichever path we choose, it is probably useful to revisit what should happen for each commit message tag. There was little external input when I first wrote it, so I am very happy to discuss if you have suggestions for improvement :). The current config resides here: https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/parser_scipy.py#L82-L99

So in sum, I think we can probably solve the "empty releases" problem by being smarter about the above config, but - independently of that - we can also discuss a less frequent release cycle if there is a need for that. For the release cycle I'd also like to hear @almarklein s thoughts 😃.

**Comment by almarklein** [comment]
I think @kmilos makes a good point. If you follow the release, then daily releases will feel like spam.

My suggestion would be an automated monthly release, with the option to trigger a new release in case urgency is required (only for security issues, I suppose).

As for people contributing, the fact that we can tell the user exactly when their change will be available in the new release is already a big benefit. I mean, as opposed to saying "I will make a release soon" and then forgetting about it (I plead guilty).

**Comment by kmilos** [comment]
@FirefoxMetzger That system you have built is pretty neat indeed! I'd just like it to be a little bit less trigger-happy ;)

**Comment by FirefoxMetzger** [comment]
Hmm. What do you guys think about a weekly release cycle, @almarklein @kmilos? That would be less frequent than it is right now, and we can put it on every Monday as the start of the workweek.

Beyond that, I remembered two other questions on the versioning that I resolved arbitrarily at the time, but that are worth a second opinion:

1. Should a change in dev tooling affect the version (bump 0.0.X)? The logic here would be that changes in the build system might end up breaking something for a version, so it might affect downstream users. On the flip side, there are dev changes that are invisible downstream, so it would feel weird to have an "empty" new release.
2. Same question, but for refactors / maintenance commits: Should refactors (which could cause regression/bugs) keep causing the bug number (0.0.X) to increase? My motivation was to allow downstream an easy way to roll back and undo a refactor that caused a regression, but I can also see merit in not rolling out a new version that just contains refactors.

**Comment by almarklein** [comment]
> What do you guys think about a weekly release cycle?

I suspect that a week can still feel short.

I think that (once your current "sprint" is about done) any changes will be more sporadic. Could we do something like, once an (api-changing) change happens, a release is scheduled a week later, unless the previous release was less than a month earlier, in which case its scheduled a month after the previous release. Would this be doable without overcomplicating the release process? 

> Should a change in dev tooling affect the version (bump 0.0.X)? 

Only for dev changes that affect the API. I'd say that changes to the tooling that affect the API should be marked as such. Can we do that?

> Should refactors (which could cause regression/bugs) keep causing the bug number (0.0.X) to increase?

I'd say typically no. We should assume that the API has not changed, even if we know that this is not always true, but that's life, and we can then fix that. In case the refactor is very large, then it might be worth an exception to break that rule.

**Comment by almarklein** [comment]
Funny, I just realized that what I described for the release scheduling is *very* similar to how draw events are typically scheduled under the restriction of a max-FFPS (which I recently implemented wgpu-py).

**Comment by kmilos** [comment]
Nothing further to add, your Honour. ;)

**Comment by FirefoxMetzger** [comment]
> Could we do something like, once an (api-changing) change happens, a release is scheduled a week later, unless the previous release was less than a month earlier, in which case its scheduled a month after the previous release. Would this be doable without overcomplicating the release process?

API changing PRs are breaking changes/depreciations or new features; though not all new features will affect the user-facing API.  We could build a system around that, but it would be different from what we have now, so we would have to rewrite large parts of the CD pipeline. The same goes for dynamically scheduling releases depending on the date of the previous release. If one of you wants to write this, I'm happy to review; however, I don't have too much interest in leading the efforts in this direction.

We could release on a fixed day each month, instead of releasing weekly/daily. Both of you like a monthly cycle, so we could go with that. To me it feels a bit odd, because - in my mind - we will have at least one (small) feature change during a month, which means we won't really push out any releases that fix bugs anymore and instead bump the version minor each month. You could counter-argue that we can release bugfixes at a higher frequency (weekly/daily), but that just complicates the entire pipeline. For that we would need one branch which merges bugfixes and releases them, and a separate branch that aggregates features that get merged/released once a month. I don't think we need such a complicated setup.

In sum, I think we have two options from here:

1. We can reduce releases to once a month (on a fixed day each month). In this case, we wouldn't even need to do anything else, because the low release frequency would take care of all the other things we discussed so far. 
2. We adjust the way in which tags bump versions and see if that is already enough to make the library silent / less chatty enough. Potentially, we can additionally reduce the release frequency further; anything you can do with a cron time string can be done here.

I think that both options will solve @kmilos problem, and they are fairly easy to implement. We could do something more sophisticated, but I'm not convinced that we need the added complexity so I'm not super interested in adding it (although I won't veto it or anything; I just won't be actively pushing the effort).

**Comment by almarklein** [comment]
I agree that if anything, we should avoid making things more complex.

Maybe another option:

3. Adjust the cron time to run the release script each month,*and* allow the script to run manually. so that when there is something urgent in the `main`, a new release can be created sooner (without doing a complicated branch scheme). Now that I look at it, the script can already be run manually (due to the `workflow_dispatch` option).

Or, maybe a combination of doing a weekly run + your option 2 :)

Ok, I think we have quite some options now, and most are not mutually exclusive. I'd be fine with your option 2, maybe in combination with reducing the frequency a bit. We can see how that works out, and if @kmilos still experiences it as spam, he should let it know and we can take more measures.

**Comment by FirefoxMetzger** [comment]
@almarklein Yes, the options are not mutually exclusive, so we can always add them later. For now, though I think it is enough to solve @kmilos problem.

Yes, manual execution of the workflow is already possible and will continue to be possible in either case.

I can add a PR to reduce the release frequency to weekly today and then look into the adjustments of the automated semver once I return from my vacation.

**Comment by kmilos** [comment]
That sounds like an ok balance, thanks, and Happy New Year all!
