### ISSUE TITLE
Deprecation plan while transitioning to v3

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#725]
Unless I'm mistaken we've not yet explicitly discussed how to transition from v2 to v3. Or it has been so long ago that I forgot :) 

As a first point, I like the idea of having an `imageio.v2` and `imageio.v3` namespace. My suggestion would be to actually make them modules so one can do e.g. `from imageio.v3 import imread`. 

As for the transition, I see ~two~ three possible routes:

A) With the v3.0 release we put the v3 functions in the `imageio` root namespace instead of the v2 functions. Maybe some compatibility stuff for a while. This may feel clean, but I fear can also be very disruptive, because although `imread()` will behave the same in like 95% of use-cases, it may not in the other 5%.

B) A softer approach would be to steer people into using `import imageio.v3 as iio`. Then, after a while we can add deprecation warnings to the v2 functions, and after yet another year or so we can kill off the v2 code.

C) We can change the name of imageio to `imageio3`, so people can actually use both side-by-side. Now that I'm writing this I think we discussed this earlier, and IIRC we decided against it.

**Comment by almarklein** [comment]
> My suggestion would be to actually make them modules so one can do e.g. from imageio.v3 import imread.

nvm, I just realized this is already implemented in #720, nice!

**Comment by FirefoxMetzger** [comment]
> Unless I'm mistaken we've not yet explicitly discussed how to transition from v2 to v3. Or it has been so long ago that I forgot :)

Nothing super specific other than https://github.com/imageio/imageio/issues/644 tracking some (most) of the things needed for us to actually be capable of transitioning.

> As a first point, I like the idea of having an imageio.v2 and imageio.v3 namespace. My suggestion would be to actually make them modules so one can do e.g. from imageio.v3 import imread.

Yes. This originates from a PR comment I made a while ago: https://github.com/imageio/imageio/pull/689#issuecomment-973230019

The idea here would be to remove `imageio.v2` once we have `imageio.v4` and to display a deprecation warning for everything in `imageio.v2` once we release v3. This way we have the API of the previous version major around for people that migrate slowly, we have the current version major for stable usage, and (just like now) we can have the next version major API for experimental usage as well, i.e., v3 would eventually have `imageio.v2` (past), `imageio.v3` (current), `imageio.v4` (future).

> A) With the v3.0 release we put the v3 functions in the imageio root namespace instead of the v2 functions. Maybe some compatibility stuff for a while. This may feel clean, but I fear can also be very disruptive, because although imread() will behave the same in like 95% of use-cases, it may not in the other 5%.

I am ambivalent about making the v3 API available in the root namespace. We can use v3 to remove it and enforce explicit API versioning (`import imageio.v3 as iio`) or we can cycle it. Shifts in version major tend to break things in incompatible ways, so - to me - that would be the appropriate time to do it.

Looking into the future, I can see how removing it completely will be easier though, because once we move into v4 people won't have to change historic scripts, because they will already import v3 explicitly (just like the recommendation now would become to `import imageio.v2 as imageio` to avoid migration). 

> B) A softer approach would be to steer people into using import imageio.v3 as iio. Then, after a while we can add deprecation warnings to the v2 functions, and after yet another year or so we can kill off the v2 code.

I think this makes sense. Although, if we are being strict with versioning, removing the v2 namespace would then be another breaking change. We could also keep it around with a warning and remove it once we introduce v4.

> C) We can change the name of imageio to imageio3, so people can actually use both side-by-side. Now that I'm writing this I think we discussed this earlier, and IIRC we decided against it.

Yes, we explicitly decided against this. Making a new library comes with a lot more overhead, and maintenance effort (if people should be able to use it side-by-side). I can dig for the previous discussion if you think that is worthwhile.

**Comment by FirefoxMetzger** [comment]
Ah, I forgot to write down my suggestion explicitly. I'd suggest a mix of @almarklein 's three option's.

Before v3: 

- We introduce namespaces for the APIs (imageio.v2, imageio.v3). This way, the class-based API we discussed with @jni a while ago will be able to live alongside.
- we deprecate the functions in the main namespace and ask users to `import imageio.vX` explicitly to silence the warning.
- we mark the old FormatManager as depreciated (the v2 API goes through imopen directly, and the formatmanager too calls imopen)
- we mark the v2 Pillow plugin as depreciated

At v3 release:
- we remove the v2 functions in the main namespace, the FormatManager, and all the parts that are now no longer in use
- we add a depreciation notice to the functions in `imageio.v2` and ask users to migrate to `imageio.v3`.
- we keep `imageio.v2` until we release v4; however, with the caveat that this is not actively versioned and mainly intended to ease transitioning into imageio.v3. As such, breaking changes may occur without being reflected in the versioning of the library.
- we remove the v2 pillow plugin

Something that need further thought:
- The way plugins are resolved is much simpler in v3 than it is in v2 (see below). Do we want to remove it in v3? This would change the behavior of the v2 API, but wouldn't affect the API itself. I vote for yes because I want to avoid maintaining two "projects" with different behavior in some edge cases.
 
https://github.com/imageio/imageio/blob/836b7a9b077a96de8adab5b67ea53b1292048275/imageio/core/imopen.py#L16-L61

**Comment by almarklein** [comment]
Wait, what do you mean with v4? You make it sound like there are already planned changes.

I must say that pushing users to use `import imageio.vx as iio` for the indefinite future does not feel particularly elegant :/  On the other hand it solves some pain during the transition phase.

> Making a new library comes with a lot more overhead, and maintenance effort 

Not necessarily, we could (semi) abandon the old version, that will over time be a good incentive for people to transition to the new version. But I also realize that these two are about equally in-elegant:
```py
import imageio.v3 as iio
import imageio3 as iio
```

Maybe, after some years, once a v3 (or v4) feels good enough, we can solidify that choice by putting that API back in the root.

----

> At v3 release [...] we remove the v2 functions in the main namespace

Maybe leave them for a while (though deprecated), because there won't be that much time between the latest v2 release and the 3.0 release. We need to give people enough time (a year, I'd say) to transition.

> The way plugins are resolved is much simpler in v3 than it is in v2 (see below). Do we want to remove it in v3? This would change the behavior of the v2 API, but wouldn't affect the API itself.

Well, since the point of `v2` is to have the same non-breaking API as before, and the fact that this would change the behaviour, I'd say no. I'd also like to get rid of the old code, but I don't expect much maintenance, because it's been like this for ages, and if people have a problem with it they should use `v3` instead.

**Comment by FirefoxMetzger** [comment]
> Wait, what do you mean with v4? You make it sound like there are already planned changes.

No, no. There is nothing new planned yet. It's more that we had a v1, v2, and now a v3. I think it is reasonable to assume that we will eventually feel the desire/need to introduce a v4 and beyond. I have no idea when this will happen, but I wouldn't be surprised if it does eventually do so.

> I must say that pushing users to use import imageio.vx as iio for the indefinite future does not feel particularly elegant :/

I noticed that you brought that up a couple of times in your reply. Could you elaborate, which part of the import feels inelegant? I currently can't see anything particularly wrong with it, so maybe understanding that better would help us come up with a better solution.

To me, having a unique namespace for each API is just a way to stay organized and to allow people to explicitly select the (frontend) API they want to use; especially considering that we will also have the class-based API in the future. Anything that allows that is fine with me, so I'm happy to take suggestions.

> Maybe, after some years, once a v3 (or v4) feels good enough, we can solidify that choice by putting that API back in the root.

I don't know; maybe I misunderstood things, but I would avoid going back and forth between repos. I think the goal should be to find the least intrusive way of doing the backward-incompatible changes that v3 brings along.

Speaking off least-intrusive, what did you do for the transition from imageio v1 to imageio v2? Maybe we can use that transition as a guide for how to do this one.

---

> Maybe leave them for a while (though deprecated), because there won't be that much time between the latest v2 release and the 3.0 release. We need to give people enough time (a year, I'd say) to transition.

Hm, I think the point of bumping a version-major is that it indicates that things break in the ABI/API. It feels weird to bump the version major and still keep the deprecated functions around, but then remove them later during a minor/patch release (which is the actual act of breaking stuff).

This is probably me being idealist, but I'd rather stay on imageio 2.X for a while (id' say until summer or so, but if you think a year is better, we can do that, too) and then remove everything when we bump to imageio 3.0. Then again, the longer we wait, the more things that will be removed will accumulate. This runs the risk that the change feels like a massive purge or a completely new library, where it really just is a reorganization to make things easier for everyone involved.

> Well, since the point of v2 is to have the same non-breaking API as before, and the fact that this would change the behaviour, I'd say no

non-breaking to what extent? The v3 pillow plugins tries to make the plugin less opinionated, so there are incompatibilities between the v2 pillow plugin and the v3 pillow plugin. For example, v2 tries to convert everything to RGBA (with a bunch of exceptions that I find a bit unintuitive at times), whereas v3 will yield the format that was stored in the file itself (RGBA, RGB, L, ...) unless explicitly asked to return in a desired `mode`. So if we would use the v3 pillow plugin with the v2 API (which is perfectly possible), then this would change the behavior. For the better, I'd say (because you can do more than before), but still a change in default behavior. 

I think this is not an easy line to draw, but if we want to keep the behavior of v2 (beyond having that API on a functional level so that people can keep calling `mimread(ImageResource, format=XX)` to get a list of images) we will have to sort this out.

**Comment by jni** [comment]
I agree that imageio.v3 is the best option. To be honest having versioned APIs right there in the API is nice and does away with a whole bunch of discussion about the best way to break stuff (progressively or all at once). And I agree with @FirefoxMetzger that it's reasonable to assume there will eventually be a v4 (depressing though that thought might be). Ultimately, it would be awesome if people put version caps on their dependencies and we could just bump the major version. But the reality is that they don't, so breaking things between major versions is still disruptive. New namespaces are the only way to ensure that we don't surprise users. See also the scikit-image SKIP-3 discussion [here](https://github.com/scikit-image/scikit-image/pull/5475) and [here](https://mail.python.org/archives/list/scikit-image@python.org/thread/DSV6PEYVJ4RZRUWWV5SBNF7FFRERTSCF/).

**Comment by almarklein** [comment]
I suppose my main reluctance for forcing users to `import imageio..vx` is that I have never seen in any other libs,  and it looks weird to people who are relatively new to Python. Maybe we should just have the guts to chose/design an API and then go for it.

On the other hand, I want to make the transition easy for our users, and give them a reasonable time-frame to make the transition. As Juan says, most will just blindly update and still be caught by surprise by breaking changes in a major-release bump.

> what did you do for the transition from imageio v1 to imageio v2? 

The API itself did not change much in this transition. The big change then was that we started using Pillow instead of FreeImage to handle the majority of formats.

> This is probably me being idealist, but I'd rather stay on imageio 2.X for a while  [...]

Right, that's probably better. My point is that there should be sufficient time (close to a year, I'd say) where the old API produces deprecation warnings, before it is removed. BTW, during this time we are already considering the old API deprecated, so we won't be maintaining it except for urgent stuff like security issues.

> non-breaking to what extent? The v3 pillow plugins tries to make the plugin less opinionated, so there are incompatibilities between the v2 pillow plugin and the v3 pillow plugin. 

I think you mean that changing the plugin selection for v2 is ok, because we can see it as an improvement? I'm fine with that, as long as the chance of breaking people's code is very small.

----

Let's take a step back and see what changes make up the transition. 

* New plugin selection mechanism. We could roll this our while we're still version 2.x.
* We introduce new functions. We can already make them available.
* Some functions will be removed. We can keep keep these alive for a while, with a deprecation warning, and then remove them when we bump to v3.0.
* Some functions (`imread` and `imwrite`) change behavior:
  * Will return volumes as well as images.
  * Will return an ndarray without the meta attribute.

It's especially the last point that makes the transition tricky. If there would be no overlap in function names between the old and new api, then it would be much easier for the user to transition at a time that suits them ...

So, to stir things up a bit :D what about we rename our new functions `iio.read`, `iio.write`, `iio.meta`, `iio.open`, `iio.iter`? That way the two API's can live side-by-side in the root namespace, we can emit deprecation warnings when the old functions are used, and remove them when we bump to 3.0.

**Comment by FirefoxMetzger** [comment]
> I suppose my main reluctance for forcing users to import imageio..vx is that I have never seen in any other libs, and it looks weird to people who are relatively new to Python. Maybe we should just have the guts to chose/design an API and then go for it.

Or have the guts to do something new that no other library did before? :D As we established before, nobody pins their dependencies in python (though this might change at the rate at which poetry is being adopted). Maybe there is merit to the idea of forcing people to "pin a version major" by making it part of the import string. From the discussion we had so far it sounds like some form of namespacing like this would smooth the transition process significantly.

The original idea comes from scipy actually. While I do have mixed feelings about their API, one thing that I think works quite well is that their modules are largely independent and that you import them almost independently, too. Having something like that to separate the new API from the current one seemed quite worthwhile. Initially, I thought we could do something similar and end up with

```python
from imageio.functional_api import imread, imwrite
```

but then I quickly changed to something closer to what [statsmodels is doing](https://www.statsmodels.org/stable/api-structure.html#api-import-for-interactive-use)

```python
# import statsmodels.api as sm
import imageio.functional_api as iio
```

Eventually, I thought that we might be able to learn from what all the people developing REST APIs are doing and use the version major as a namespace (since - surprise - people don't/can't pin versions there, too). So I settled for

```python
import imageio.v3 as iio
```

which is indeed a bit unusual, but - considering the problem that it tries to solve - I think overall quite neat.

@almarklein Would it be more elegant if we settle for a different name that doesn't include the version major, e.g., my previous `import imageio.functional_api as iio`? 

> On the other hand, I want to make the transition easy for our users, and give them a reasonable time-frame to make the transition. As Juan says, most will just blindly update and still be caught by surprise by breaking changes in a major-release bump.

How about we pick a deadline - say summer 2022 - until which we stay on v2.X (with depreciation warnings) and then we migrate to v3.0 which deletes the old API and replaces it with an exception along the lines of `iio.mimread has been removed in V3. Use iio.imread from imageio.v3 instead.` This will still break things for users, but it will do so in a rather obvious way, plus it tells you how to fix it.

Alternatively, we can keep the v2 API indefinitely. There is nothing stopping us from having `iio.mimread` wrap `iio.imiter` or `iio.v2.imread` delegate to `iio.v3.imread(index=0)` combined with an assertion that the result is a flat (dim = 3) image. In that case though, I would really vote to remove the current (v2) API from the main namespace to avoid confusion, and to replace it with a variant of the constructive exception mentioned above.

> I think you mean that changing the plugin selection for v2 is ok, because we can see it as an improvement?

Hm, not exactly. 

If I understand correctly, our philosophy of writing plugins is changing a bit. Before plugins seemed to try to unify things a lot, e.g., PillowFormat converts almost everything to RGBA (or RGB?) unless explicitly told not to (e.g., via `as_gray`).  Now our philosophy is leaning more towards writing plugins that match the behavior of the underlying backend where possible. This is - for the most part - more intuitive and much easier to maintain. Backends tend to serve data as is, so you tend to get exactly what is in your file which is the least surprising choice from a library's perspective.

As such [PillowFormat ](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow_legacy.py) and [PillowPlugin](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py) are not compatible with each other. For example, because of the RGBA vs native color channel thing mentioned above.

The question then is if - starting with ImageIO v3 - the `imageio.v2` API should use PillowPlugin to open files as well (which may be a breaking change), or if we should keep the old PillowFormat as well to allow the old behavior to persist.


---

> New plugin selection mechanism. We could roll this our while we're still version 2.x.

We actually already have. FormatManager is now wrapper around the current format selection mechanism from v3. My main point here is to see if we can get rid of some of the old behavior which - at least to me - is odd and counter-intuitive. 

For example, we can currently pass a filepath into `iio.mimread(ImageResource, format="path/to/file"`) and it will use the extension of that path to choose the format to read ... but only if the path actually points to an existing file, otherwise this will raise an exception. I'm still working out when this would be useful.

Another example is the ability to sort formats, which currently exists, but is a bit inconsistent. The general idea is nice, but because some backends are registered as a single format (FITS, FFMPEG, ...) and others are registered as many formats (JPG-PIL, GIF-PIL, ...), you don't really have full control over which backend should be chosen for which format. The new `imageio.config` does this properly by maintaining a list for each known extension individually (`imageio.config.known_extensions["extension"].priority`) and you can sort it as you please. There also is a general list of plugins that determines the search order in case of an unknown or missing extension (`imageio.config.known_plugins`). On top of allowing more sophisticated tuning, we are also using those config files to keep our docs in sync with what formats are supported and how, as well as what the priority over backends is for each format.

As a result, I would like to remove the old ability to simply call `imageio.formats.sort`, because it aliases the search order of extensions and plugins which is confusing. This, however, is again a breaking change.

There's other examples like that, but the pattern is the same: We had some feature that grew organically and we have now realized that it is a bit inconsistent in some places. V3 then takes that feature, tries to work out the known kinks, and then fits it into a structure that is easy to maintain.

> Some functions (imread and imwrite) change behavior [...] It's especially the last point that makes the transition tricky. If there would be no overlap in function names between the old and new api, then it would be much easier for the user to transition at a time that suits them ...

I agree on this point. Hence my proposal of `imageio.v3` to avoid competing in a global namespace.

> So, to stir things up a bit :D what about we rename our new functions iio.read, iio.write, iio.meta, iio.open, iio.iter? That way the two API's can live side-by-side in the root namespace, we can emit deprecation warnings when the old functions are used, and remove them when we bump to 3.0.

If you think this will help migration as well as long-term use we can consider it. Would that be on top of a `imageio.v3` or a replacement of it?

A concern with this solution is that we will run out of names at some point. If we need to make another round of incompatible changes we have to come up with new names that won't conflict. Note that we can't reuse `iio.imread`, because that would alias with ImageIO v2. But such are the pains of global namespaces xD

---

On a tangent, I am a bit curious why you (@almarklein and @jni) think of changes in version-major as depressing or concerning. I don't think we can get an API perfectly right on the first try and even if we could the environment around it changes and makes an API inadequate or suboptimal in some places. Replacing old things that aren't appropriate anymore seems like an obvious choice to me. I feel like there is there something I'm not getting x)

**Comment by jni** [comment]
@almarklein 

> I suppose my main reluctance for forcing users to import imageio..vx is that I have never seen in any other libs

It was brought up in the skimage discussions that tensorflow does this:

https://www.tensorflow.org/api_docs/python/tf/compat

Haven't read the other comments yet but just wanted to alleviate that concern. 😊

**Comment by FirefoxMetzger** [comment]
I think we are slowly getting somewhere with this. Here is an improved approach based on the above discussion:

- We introduce `imageio.v3` and `imageio.v2` to have a place for each API to live (and to add others like the imageio.Image one in the future)
- We keep `imageio.v2` as a flat wrapper that calls `imageio.v3`
- We deprecate the API functions in `imageo` (global namespace), first by having a deprecation warning (about half a year), and then via an exception that tells people that the function moved to `imageio.v2`. (Maybe we should keep the exception indefinitely, because it is also a reminder for us to not reuse that name in the future)
- We add the version namespaces into the global namespace (`from . import vX` in the main `__init__.py`) to allow discovering the APIs from the main namespace.
- We use the transition to v3 for some behind-the-scene changes that will break exotic/rare use-cases (like removing `formats.sort()`) to allow us to tidy up the library a bit.

Open points that still need resolution:

- Should we make the v3 API functions a direct part of the global namespace?

---
Other comments:

> I guess this means I'm ok with using the PillowPlugin over the PillowFormat.

Would you consider this a breaking change or an enhancement? It changes some of the behavior, but from what it sounds like the change is towards what you always intended anyway. We could roll this out as a new feature and clean that part of the codebase up already.

> My main point about the root namespace is that although it's just 4 extra characters to type ".v3", it is an extra burden that we must not underestimate.

Just to make sure we don't misunderstand each other here, `import imageio as iio` will still continue to work. However, in this case you would use `iio.v3.imread` (which you commented on in #718 ). You will continue to get auto-completion for the APIs; however, they will be `[v2, v3, Image, ...]` or whichever names we choose, and after typing `imageio.v2.` you will see the familiar `imread`/`imwrite`, etc.

A scientist doing `import imageio` will hence get `v2` and `v3` (perhaps `api_v2`?) as suggestions which are - hopefully - self-explanatory assuming he/she has some programming experience. This is of course more verbose than doing `import imageio.v3 as iio` at the top-level once. It does, however, make the API discoverable with `import imageio` as a starting point.

> In other words, as cool and sophisticated as we might think that imageio is, for most users it feels like that tiny tool to get the "simple" job of reading images done. We must strive for our API to be boring and easy to discover.

I agree with this. I think the best tools are the ones that actively save you time/effort while making you forget that you are using them. And the fact that users think of the job of reading images as "simple" goes to show that we are on the right track here :D

> Maybe the second option is fine, because the cases where the behaviour would be different are rare; people loading volumes used volread, so what's left is edge cases of Tiff, I think, and this was somewhat iffy and subject to change already.

In terms of behavior yes. `imwrite` isn't even a breaking change, because it essentially now allows you to pass in a ndarray with `ndim>3`, so I think that one could even be implemented in a non-breaking way. `imread` is a bit more tricky, because the output changes for some files in a non-breaking way.

In terms of API design, I'm not entirely sure what the differences are. Likely, you can merge those changes by adding deprecated kwargs that raise warnings and forward to the new behavior. I haven't thought about this a lot though, so I don't have a lot to contribute at this point.

---

> This is because imageio has thousands of users

I think you are being humble here, though we can't know for sure since we don't have any way of measuring or tracking that. Even if it is mostly CI/CD rebuilding the internet twice per day I think it isn't unrealistic to add a 0 to your estimated userbase based on our monthly download count.

Speaking off measuring impact, any objections to me setting up google analytics for our docs at some point in the future? I'm curious which parts are actually in demand and how people navigate the docs. RTD offers simple analytics, but nothing to actually generate concrete/tangible insight.

Funfact: Pillow uses the same download tracker we use and apparently almost half of the people that download pillow also download ImageIO (or download pillow _because_ they download ImageIO since we depend on it).

**Comment by almarklein** [comment]
>> I guess this means I'm ok with using the PillowPlugin over the PillowFormat.
>>
> Would you consider this a breaking change or an enhancement? 

Let's consider it an enhancement. The nice thing about this part is indeed that we can do it now.

> A scientist doing import imageio will hence get v2 and v3 (perhaps api_v2?) as suggestions which are - hopefully - self-explanatory assuming he/she has some programming experience.

Sure, that helps, but it will likely result in some confusion (should I use v2 or v3? v3 is probably newer, but why is v2 there too?).

> `imread` is a bit more tricky, because the output changes for some files in a non-breaking way.

Maybe we can create a POC branch in which we replace `imread` with the v3 version, and see what tests break. Perhaps such cases can even be detected.

> Speaking off measuring impact, any objections to me setting up google analytics for our docs at some point in the future?

Sure.

**Comment by FirefoxMetzger** [comment]
> Sure, that helps, but it will likely result in some confusion (should I use v2 or v3? v3 is probably newer, but why is v2 there too?).

How about this approach: For `imread` and `imwrite` we don't deprecate them in the global namespace. Instead, we do the following:
- for now we add a deprecation warning that their behavior will change in V3 and ask people to use `imageio.v2` to retain the old behavior.
- in v3 we replace the deprecation warning with a UserWarning saying something like "Using the global `imread` is discouraged and may break in a future version of ImageIO. Use `iio.v3.imread` to silence this warning. More info at <link-to-docs-here>."

For the other functions that are specific to the v2 API namespace in the global namespace we deprecate them using the warning+exception cycle discussed above.

Then, once we need to transition into v4, we don't go through a deprecation cycle for global `imread`/`imwrite`, but simply update the UserWarning to point to v4.

**Comment by almarklein** [comment]
I still hope that we can keep the global namespace as the-place-to-go. I also think we should not plan for a v4. If there will ever be one, I expect it to be a rather different API that will use names that don't collide with what we have now, so it will be possible to fit in in the root namespace too.

> AK: Maybe we can create a POC branch in which we replace imread with the v3 version, and see what tests break. Perhaps such cases can even be detected.

I'll try to find time to try this this week. Maybe .. we can detect the cases where the API will break, and for these cases produce the warnings ...

**Comment by FirefoxMetzger** [comment]
> I still hope that we can keep the global namespace as the-place-to-go. 

In the sense that it should be possible to discover the API via `import imageio`? (regarding this I tried to make suggestions above) Or in the sense that we should discourage `import imageio.v3 as iio` as the desired way to import the library?

> Maybe we can create a POC branch in which we replace imread with the v3 version [...] I'll try to find time to try this this week.

If you just want to change `imread` and `imwrite`, that is a fairly trivial change. Just set the legacy mode of `imopen` to `False` in those functions:

```diff
diff --git a/imageio/core/functions.py b/imageio/core/functions.py
index 38400bc..2856b33 100644
--- a/imageio/core/functions.py
+++ b/imageio/core/functions.py
@@ -156,7 +156,7 @@ def imread(uri, format=None, **kwargs):
             'Invalid keyword argument "mode", ' 'perhaps you mean "pilmode"?'
         )

-    with imopen(uri, "ri", plugin=format) as file:
+    with imopen(uri, "ri", plugin=format, legacy_mode=False) as file:
         return file.read(index=0, **kwargs)


@@ -192,7 +192,7 @@ def imwrite(uri, im, format=None, **kwargs):
     else:
         raise ValueError("Image must be 2D (grayscale, RGB, or RGBA).")

-    with imopen(uri, "wi", plugin=format) as file:
+    with imopen(uri, "wi", plugin=format, legacy_mode=False) as file:
         return file.write(im, **kwargs)
```

**Comment by FirefoxMetzger** [comment]
@almarklein Another idea: Howe about adding a new kwarg to imread called `version="v2"`, which controls the version that imread will forward to?

If we really want to keep all the functions in the primary namespace, do we want to deprecate `mimwrite` and the other v2-specific functions and only keep v3? or do we want to keep everything?

**Comment by almarklein** [comment]
I wanted to try dropping in the new imread to see what it does to the tests, but I cannot succesfully run the tests in the first place, because it's missing the test images. How do I install these nowadays, I checked the CI workflow, but I don't think I missed a step ...

**Comment by FirefoxMetzger** [comment]
@almarklein Oh that's odd. All the test images should be downloaded on demand, i.e., when you first run it. There is https://github.com/imageio/imageio/pull/705 which changes things around (prefetch the images before running any tests), but that isn't on master yet. What's the exception you are getting?

**Comment by almarklein** [comment]
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\almar\\AppData\\Local\\Temp\\pytest-of-almar\\pytest-3\\image_cache\\test-images'

**Comment by almarklein** [comment]
Aha
```
$ git --version
git version 2.29.1.windows.1
```
![image](https://user-images.githubusercontent.com/3015475/150776750-e2aba0b6-922a-4556-85cb-7b3452234df4.png)

**Comment by FirefoxMetzger** [comment]
> $ git --version
git version 2.29.1.windows.1

Yeah, with that exception, my first question would have been to ask how old your git version is :D What's interesting here is that we do have a fallback path for this case (the one you linked), but it doesn't seem to work. My WSL (linux) has git v2.25.1 and that path works as intended. Do you think we should follow this up, or should we consider it niche?

**Comment by almarklein** [comment]
Somehow that fallback git command just deletes all the images. I can `git restore --staged . & git checkout .` in the shell to bring them back, but running the test just deletes them again.

**Comment by FirefoxMetzger** [comment]
@almarklein I would like to lobby for making the plans discussed in this issue concrete sooner rather than later :) 

If our goal still is to release v3 late summer/fall 2022 (would be good for me, because it is just after I graduate from my PhD, so I have time to address potential fallout from breaking the API) and we want at least 6 months notice period for any deprecations, then we should try to figure out what parts of the library deserve such a notice soon.

**Comment by almarklein** [comment]
Yeah, sorry I got a bit demotivated  by that testing/git stuff, and was overwhelmed by other obligations.

I still feel strongly that we should take care to minimize the burden/surprise for existing users, and allow them to transition in their own time. It should also be possible to use the old and new version side-by side (for a while), because an application might have multiple dependencies that use imageio, and these might be in different states of transitioning.

The `imageio.v2` and `imageio.v3` solution would help achieve that. In my earlier posts I advocated that the root namespace should contain the API, but I now think that this will make the transition more painful, both for us and for our users. Instead I'd say we keep the old API in the root namespace for quite a long time, giving users time to transition by themselves, then issue a warning, also for a long time, and finally error out. I'd say that process should take at least half a year for each step.

I'd also like to bring up (again) the idea of creating a new package, e.g. `imageio2` or `iio2` or whatever. IIRC this idea was discarded because we expected it to be additional maintenance, but I'm starting to think it may actually be easier. I this approach the new library can drop *everything* from the old imagio that it does no longer need, resulting in a cleaner codebase from the start. The old codebase will continue working and we can just do some minor maintenance but no new features. We could make it issue a warning on import time to start using the new lib instead. I'd be happy to take responsibility for "decomissioniong" the old imagio :)

**Comment by FirefoxMetzger** [comment]
> I still feel strongly that we should take care to minimize the burden/surprise for existing users, and allow them to transition in their own time.

We are still in agreement on this point :) I think the main difference is what we see as an adequate amount for "in their own time". I put this at around 6 months, whereas you put it somewhere north of 1.5 years.


> I'd also like to bring up (again) the idea of creating a new package

On top of the maintenance burden, there is also the everpresent "curse of mylib2". You make a new package ought to become the new version and instead, it splits your community in half, with 50% being early adopters and enthusiasts and the other 50% never updating, because of some reason. It happened to angular/angular2, ros/ros2, and many others that went down that path. Of all the projects I am aware of that went down that path, all ended up worse than before. Maybe you know of some success stories? (That's one of the big reasons why I am wary of this road.)

Another point is that, if you really think about it, the breaking changes aren't actually that many. It's just `imread` which changes its output, and us deciding on what should happen with the old API functions. Most other things should be resolvable in a backward-compatible way; especially considering the new `format_hint` feature (https://github.com/imageio/imageio/pull/734), which can take most (all?) of the v2 `format=` behavior that isn't plugin related. We can simply run a deprecation cycle on the kwarg and ask people to rename it to `format_hint` or `plugin` as needed. The output change also isn't too bad, considering that we rarely hear about metadata issues, and that we didn't have a clear policy on that to begin with.

The top-level namespace needs sorting out, but I am still confident that we can find a suitable solution. How about we keep the top-level functions indefinitely (no deprecation) and give it a dedicated name, say "meta"? We would then have

- `import imageio as iio` --> imports the meta API which is a conglomerate of all API versions (with the behavior of the latest one replacing the previous one in the case of a name collision)
- `import imageio.v3 as iio` --> v3 API only
- `import imageio.v2 as iio` --> v2 API only (albeit using the new backends)
- `from imageio import Image` --> OOP Image API (tbd)

Except for `Image` all of these would be tight wrappers around `iio.imopen`, so there would be little maintenance burden and we can keep them alive indefinitely.

**Comment by almarklein** [comment]
> Maybe you know of some success stories? 

There is jinja2, which is - oddly enough - at version 3 now. But maybe it's an exception. I honestly don't know.

Let's not make this issue an endless discussion indeed :)  let's go with your latest suggestion 👍

**Comment by jni** [comment]
cv2 and bs4 are another two success stories.

**Comment by FirefoxMetzger** [comment]
> There is jinja2

> cv2 and bs4 are another two success stories.

Interesting, I need to find some time to look into what these projects did differently; sounds like there is something to learn :)

> Let's not make this issue an endless discussion indeed :) let's go with your latest suggestion 👍

OKies. I will update the PRs related to v3 appropriately, and I will start a new PR with deprecation warnings where appropriate. If the latter reveals anything we did not discuss here we can always reassess.

So I guess ETA for imageIO v3 is September/Oktober 2022?

@jni I know you guys have been working towards scikit-image v1. How do you go about advertising such changes? (beyond the obvious deprecation warnings where needed)

**Comment by FirefoxMetzger** [comment]
> import-time warning that says, skimage2 is out, the transition guide is here (link)

Amazing. Is there a point to having a version major reserved for breaking changes if everybody releases a new package every time they make a breaking changes?

> When we release it, we will simultaneously release version 0.(x+1) of scikit-image, which is identical to v0.x

I assume this also means a new repo, new docs and everything will get a copy (good bye SEO)? Or just a new pypi project with a new name and the old one gets "abandoned" on v0.(x+1)? How would that solve the case of users running legacy scripts that don't track dependencies? This would imply that we will also get `import skimage` and `import skimage2` depending on the package we use? I am so confused right now xD

---

On a more general note: My question was more so about disseminating that there is new stuff and that folks should go and check it out (because it is super awesome, as usual ;) ). Is it just via deprecation warnings, or do you do other forms of "outreach" (for the lack of a better word)?

**Comment by almarklein** [comment]
> We will release skimage2 as a separate package. 

Interesting! So that might be another success story, I'm sure ;)

**Comment by FirefoxMetzger** [comment]
@almarklein We are pretty much set here I guess? Deprecation warnings were released this week, so now we wait for feedback. Should we leave this issue open or close it?

**Comment by almarklein** [comment]
I guess we can close!
