### ISSUE TITLE
setup.py "python_requires" is still set to Python 3.5

### ISSUE THREAD

**Issue by BTOdell** [imageio/imageio#756]
https://github.com/imageio/imageio/blob/master/setup.py#L221

I'm using Python 3.6 and now with version 2.16.0 of `imageio` forcing the `numpy` requirement >= 1.20.0, pip is having a hard time resolving dependencies (only on Windows for some reason). pip thinks it can install `imageio` 2.16.0 because it says it's compatible with python 3.5 but `numpy` 1.20.0 requires Python 3.7+.

I'm using the latest version of pip (21.3.1) that is supported on Python 3.6.
For some reason, I don't have any issue resolving dependencies on Linux.

If the "python_requires" had been updated to 3.7+ for the 2.16.0 release of `imageio`, then pip would stick with using version 2.15.0 and there would be no problem.

Can you publish a hotfix to pypi for version 2.16.0 with the "python_requires" set to Python 3.7?

**Comment by BTOdell** [comment]
I just found out that you can't overwrite a version of a package on pypi with a modified release. So, I'm not sure how this is going to be resolved. Simply releasing a new version (ex: 2.16.1) with the "python_requires" change isn't going to fix the dependency resolution issue on Python 3.6 because pip will just continue to use 2.16.0 because it defines that it's compatible with Python 3.5+.

**Comment by BTOdell** [comment]
Perhaps "yank" the release on pypi and release 2.16.1 with the fix?

**Comment by FirefoxMetzger** [comment]
Good catch. Looks like I forgot to change that number as I went over the repo to bump it to python 3.7. I saw that you submitted a PR for this, so I will merge it once CI is happy :)

> If the "python_requires" had been updated to 3.7+ for the 2.16.0 release of imageio, then pip would stick with using version 2.15.0 and there would be no problem.

We officially dropped python 3.6 support in v2.15.0 (see the last item in the changelog for that version), since python 3.6 has reached EOL at the end of last year. If you are forced to use python 3.6 then you should pin your version to `imaegio==2.14.1`, which is the last version that is still happy with 3.6 (officially). That said, I don't think we introduced any python 3.6 incompatible changes alongside this change, so v2.15.0 might still work (when in doubt, run the test suite). In any case, if you want to use ImageIO on old python versions (especially in production) then explicitly pinning the version is probably a good idea.

> Perhaps "yank" the 2.16.0 release on pypi and release 2.16.1 with the fix?

I'm not entirely convinced yet that yanking is necessary because it only affects users with a  python version that nobody should be using anymore. Those users are probably much more well-advised to either upgrade their python version to something that still gets security updates or to pin every dependency. Then again it's early morning here and I didn't have any caffeine yet, so I will revisit this once my brain starts working normally.

**Comment by BTOdell** [comment]
Thanks for the quick action to get this fix merged in!

In my situation specifically, we're using Python 3.6 in production on Ubuntu 18.04 LTS where it is the default Python version. My company is investigating switching to Python 3.7 or 3.8 which is also available on that version of Ubuntu, but it's lower priority at the moment.

As for pinning the version, we don't directly use imageio as a dependency of our software but use it through scikit-image. We pin the version of scikit-image in our setup.py and let pip-tools generate the requirements.txt - we don't manage pinning of transitive dependencies ourselves.

Despite officially deprecating support for Python 3.6 in v2.15.0, I believe that version still effectively supports it since there is no hard version requirement for numpy. The last version 2.16.0 is the only version that has true break in compatibility (thankfully at install time instead of runtime!).

It's ultimately up to you if you want to yank the recent release. Eventually my company will probably move to Python 3.7 or 3.8 and this won't be an issue for us specifically. But there may be others that haven't realized the problem yet and in my opinion it would be better to directly fix the problem. Yanking doesn't disrupt those who have pinned the exact version and it avoids any chance of this same thing happening to someone else stuck on Python 3.6.
