### ISSUE TITLE
Feature Request: FFMPEG Writer: Provide users with the ability to specify the pixel format

### ISSUE THREAD

**Issue by hmaarrfk** [imageio/imageio#761]
it would be nice to provide users with the ability to specify their own input pixel format as the input.

Users may choose to represent their images in exotic format.

Wrapping the following `self._pix_fmt` assignment in an `if self._pix_fmt is not None:` might be enough if we provide the users with an input parameter too.

https://github.com/imageio/imageio/blob/6c259ba3d21e6f69f46f7ae8ecbe0e1a2e6ec242/imageio/plugins/ffmpeg.py#L588

Let me know if this is something you would want a PR for.

**Comment by FirefoxMetzger** [comment]
> it would be nice to provide users with the ability to specify their own input pixel format as the input. [...] Users may choose to represent their images in exotic format.

Yes, that would be nice. Do you have a specific subset in mind, i.e., how esoteric were you thinking of?

> Wrapping the following self._pix_fmt assignment in an if self._pix_fmt is not None: might be enough if we provide the users with an input parameter too.

My knowledge of the ffmpeg plugin is not as broad as the other plugins, but based on that (and the check I just did) it looks like this is indeed all that would be needed. and I'd also be happy to review a PR for this.

---

At the same time, the pyAV plugin [will be able to do that](https://github.com/FirefoxMetzger/imageio/blob/6f0b8c911cee7fc14c6da1009e0579b11df19830/imageio/plugins/pyav.py#L470-L475). I can't say how long it will take for that to get merged though (it's missing some coverage and documentation at this point, but I have been quite busy lately). Bottom line is: If you are okay with waiting one or two months for this, then you should get this via pyav. If you need it earlier then I will happily review a PR.

**Comment by hmaarrfk** [comment]
The nice thing about the ffmpeg plugin is that it uses the ffmpeg EXE which is standalone compared to a linked application.

Honestly, I've included:
```
writer._pix_fmt = pix_fmt
writer._size = image_shape
writer._depth = 1
writer._initialize()
```

to my code. I know I shouldn't, but for now it works.

Some might choose to have their images in YUV or RAW ;)

**Comment by FirefoxMetzger** [comment]
> The nice thing about the ffmpeg plugin is that it uses the ffmpeg EXE which is standalone compared to a linked application.

Yes calling an executable is nice, because you can easily switch between API-compatible versions. You do pay for that flexibility with performance though (multiprocessing + stdin/stout pipe), but if you don't mind that it is a workable solution indeed.

> Some might choose to have their images in YUV or RAW ;)

By RAW you are talking about the Bayer formats? The FFMPEG ones I am aware of are a bit weird from a numpy perspective. You get either 8-bit or 16-bit variants, which is bits _per pixel_ not _per channel_. So your actual channels will have 2-bit or 4-bit width and channels won't be byte aligned, which numpy doesn't support since byte is the atomic unit in an array. 

To cleanly access pixel components you'd have to copy the array into a buffer where components are byte aligned, but at that point, you might as well convert to RGB, YUV, or some that is natively stridable on a component level. I do admit though that I don't have a good use-case in mind, so maybe this is not necessary, and striding on a pixel level is the right approach? What do you think?

YUV444 is definitely possible, but that only exists as a planar format in FFMPEG (YUV444p). I'm not aware of a channel-last variant, but we can definitely support YUV444p. 

Subsampling, however, throws a bit of a wrench that needs dealing with. You again loose the ability to nicely stride the array. If you want to force it, you could stride on a macro pixel level for some formats. For example, if we look at yuyv422, you could read/write something of shape `(subsample_height, subsample_width, 4)` and understand it as the last channel containing the components [Y1, U1, Y2, V1]. That's not super intuitive, but I guess solvable with documentation (also because it is niche so people would [hopefully] consult docs before doing this ... but maybe I am being naive on this). However, this doesn't solve planar YUV (which is most of FFMpegs YUV collection). I never managed to work out how to stride something like YUV420p. For those formats I don't see a way around conversion if you want to read/write from a ndarray, but maybe you have any good insight here?

**Comment by hmaarrfk** [comment]
> You get either 8-bit or 16-bit variants, which is bits per pixel not per channel. So your actual channels will have 2-bit or 4-bit width and channels won't be byte aligned

That isn't my interpretation of what `bayer_rggb8` means.

My interpretation is that:
The pixels look like:
```
rgrgrgrgrgrgrgrgrgrgrgrg
gbgbgbgbgbgbgbgbgbgbgbgb
rgrgrgrgrgrgrgrgrgrgrgrg
gbgbgbgbgbgbgbgbgbgbgbgb
rgrgrgrgrgrgrgrgrgrgrgrg
gbgbgbgbgbgbgbgbgbgbgbgb
``` 

where each physicla pixel only has 1 "channel":
* `r` is a single pixel, 8 bits in value, with a `red` color filter on it.
* `g`  is a single pixel, 8 bits in value, with a `green` color filter on it.
* `b`  is a single pixel, 8 bits in value, with a `blue` color filter on it.

Typically images start with this data, then convert to a "3 channel"/pixel interpolating in between physical value.

Note that the data above is aligned with numpy pixels.

If you get raw data from your image sensor (which we can toggle from our sensors) then you reduce the total amount of data (in bytes) you receive by transmitting it in raw bayer format.

We have a few ways of converting between raw -> color, opencv, some OpenGL shader we wrote, and now FFMPEG. I am pretty confident to say that the input data is the one I described. Trying to disable compression to compare the results frame by frame to our other display mechanisms. But with `-crf 0`I got garbled videos on VLC (but not on the gnome player).

**Comment by hmaarrfk** [comment]
Without specifying `-crf 0` the videos look great!

**Comment by FirefoxMetzger** [comment]
> That isn't my interpretation of what bayer_rggb8 means.

Yep mine neither, but that is what I see when I inspect the format via pyav:

```python
>>> import av
>>> [component.bits for component in av.VideoFormat("bayer_rggb8").components]
[2, 4, 2]
>>> av.VideoFormat("bayer_rggb8").bits_per_pixel
8
>>> import numpy as np
>>> foo = av.VideoFrame(width=16, height=16, "bayer_rggb8")
>>> bar = np.frombuffer(foo.planes[0], dtype=np.uint8)
>>> bar.shape
(256,)
```

Then again this might be me not interpreting this right, or the format description not being correct, because the following works:

```python
>>> import av
>>> import numpy as np
>>> foo = av.VideoFrame(16,16, "bayer_rggb8")
>>> bar = np.frombuffer(foo.planes[0], dtype=np.uint8)
>>> bar[:] = 42
>>> im = foo.to_ndarray(format="rgb24")
>>> assert np.allclose(im, 42)
>>> im.shape
(16, 16, 3)
```

Maybe I am confusing how demosaicing works? I would have expected every pixel to correspond to 4 components in the bayer image. Therefore a `(16, 16, 3)` rgb24 image should have 1024 uint8 components as bayer_rggb8; but the above only has 256...

How are you loading data into ffmpeg? Maybe that gives me an entripoint?

---

> If you get raw data from your image sensor (which we can toggle from our sensors) then you reduce the total amount of data (in bytes) you receive by transmitting it in raw bayer format.

This statement is interesting. Sending raw bayer with 8bit per component would involve sending 32bit per pixel which is more than the 24bit per pixel you'd have in a format like rgb24. Is this due to compression?

**Comment by FirefoxMetzger** [comment]
I did some digging, and I think it might be a bug in FFmpeg. 

PyAV gets the format info from ffmpeg (`libavutil.av_pix_fmt_desc_get`) which passes the call around a few times, but ultimately [ends up here](https://github.com/FFmpeg/FFmpeg/blob/25c8507818d8559a6654a5b30a0f8aae11a48181/libavutil/pixdesc.c#L1942-L1966
) to get the format info. The cryptic `comp` argument is the component descriptor and is what I used in the previous comment. It is [defined and documented here](https://github.com/FFmpeg/FFmpeg/blob/25c8507818d8559a6654a5b30a0f8aae11a48181/libavutil/pixdesc.h#L30-L58). So yeah, according to the format description, `bayer_rggb8` is indeed this weird 8 bit per pixel format that has less than 8bits per component. 

However, - and this is where it gets good - if you digg up how ffmpeg does demoasicing, you find [this snippet](https://github.com/FFmpeg/FFmpeg/blob/1a502b99e818ee7b8b2b56c4f5c27e31f674c555/libswscale/bayer_template.c#L56-L70), which completely ignores any format info and performs demosaics in the way you (and I) would expect it to happen. This comes from libswscale, which is what PyAV calls when consuming the `format=rgb24` arg.

I wonder if you have any further insight here @hmaarrfk .

**Comment by hmaarrfk** [comment]
Thank you for spending so much time thoroughly going through this. Let me get back to after sunday. Got to wrap up some stuff today.

**Comment by FirefoxMetzger** [comment]
Sure. I just got word from a ffmpeg dev on this, and his response was `It is there as stub and meaningless.` so there's that 😅 .

Now I only have to work out why/how numpy is able to set all pixels using the snippet above even though the view I constructed should be less than the full buffer...

**Comment by hmaarrfk** [comment]
```python
import imageio
import numpy as np
image_shape = (128, 128)
image = np.zeros(image_shape, dtype='uint8')

bayer_pattern = 'rggb'
image[...] = 0
writer = imageio.get_writer(f'test_{bayer_pattern}.mp4')
writer._pix_fmt = f'bayer_{bayer_pattern}8'
writer._size = image_shape
writer._depth = 1
writer._initialize()

for i in range(256):
    image[::2, ::2] = i
    writer.append_data(image)

image[...] = 0
for i in range(256):
    image[0::2, 1::2] = i
    image[1::2, 0::2] = i
    writer.append_data(image)

    
image[...] = 0
for i in range(256):
    image[1::2, 1::2] = i
    writer.append_data(image)
writer.close()
```
will generate a video that cycles through red green and blue


https://user-images.githubusercontent.com/90008/156827356-d392caee-e094-40a3-bbbe-e997b4271749.mp4

**Comment by FirefoxMetzger** [comment]
> Sure. I just got word from a ffmpeg dev on this, and his response was `It is there as stub and meaningless`. so there's that 😅 .

I just realized that this turned out ambiguous. The question I asked the devs was how I should understand the inconsistency between the format description for `bayer_rggb8` and the code for demosaicing it in libswscale. The answer to that was that the format description is a stub and meaningless, and that I/we should take the conversion code as source of truth for how FFMpeg deals with bayer formats. 

Considering this, I think it does make sense for us to support raw/bayer formats as inputs.

**Comment by FirefoxMetzger** [comment]
@hmaarrfk The pyav plugin has been merged. One of its features is a `in_pixel_format` kwarg, which does the thing you request in this issue. 

I've also added #788 to extend this to bayer formats (writing only). For reading, this would be easy to add as well; however, pyav doesn't support bayer formats yet. Once it does, I'm happy to add that, too.
