### ISSUE TITLE
Stop shipping standard images as part of the wheel to reduce wheel size

### ISSUE THREAD

**Issue by Akascape** [imageio/imageio#827]
I found these images and files in imageio's resource folder. Do they have any purpose or it is safe to delete that whole folder?

![Screenshot 2022-07-02 165421](https://user-images.githubusercontent.com/89206401/176998787-abf4233e-ffd0-4e0f-9ef4-da7fa24089b9.png)

**Comment by FirefoxMetzger** [comment]
The images in this folder are standard images. You can read more about them [in their documentation](https://imageio.readthedocs.io/en/stable/user_guide/standardimages.html).

The purpose of these standard images is to give you access to different images for testing and debug purposes. A second purpose is that you can use them to write snippets that reproduce certain behaviors (e.g. bugs) and which are are easy to share because everybody can get easy access to the image involved. Another reason you may wish to use them is to study artifacts produced by different image processing methods. This is similar to the idea of [genera-purpose images in scikit-image](https://scikit-image.org/docs/dev/auto_examples/data/plot_general.html#sphx-glr-auto-examples-data-plot-general-py).

You can delete them if you want to. Keep in mind though, that this is essentially a cache and that you will download them again automatically the next time you access them.

**Comment by berendkleinhaneveld** [comment]
Is it possible to keep those images outside of the built wheel? Would save about 80% of the wheel size.

**Comment by FirefoxMetzger** [comment]
Theoretically, yes we can remove it to save wheel size. In practice, they might have a use case I am unaware of.

@almarklein You know the full history, did we include them to allow testing ImageIO in offline environments or what was the motivation for having the images included in the wheel? Also, any concerns/objections to removing them?

**Comment by almarklein** [comment]
IIRC the main reason is that in some workflows (e.g. some linux package builds?) the package is installed and then tested without an internet connection.

We could try removing them and see if this is still the case. People will complain here if it is :)  Or we could add them to the `tar.gz` but not to the wheels, so people can explicitly target the tarfile if needed.
