### ISSUE TITLE
Warnings should use `warnings.warn` instead of `logger.warning`

### ISSUE THREAD

**Issue by moi90** [imageio/imageio#837]
Like the author of #376 already said:

> A viable alternative would be to use the warnings infrastructure instead. This would allow developers to configure for warnings, specifically, such as silencing them (with a lot of control as to when to do so), or even turning such warnings into exceptions (if they would deem triggering the conditions a bug on their side).

I think this is not only a viable alternative, but the correct way to do warnings. Currently, it is rather hard to silence these warnings (`logging.getLogger("imageio").setLevel(logging.ERROR)` as opposed to `warnings.simplefilter` or even `-W ignore:...` on the command line) and impossible to convert them to exceptions (with the exception of writing a custom handler, maybe).

**Comment by FirefoxMetzger** [comment]
Hmm. I just went over the places where we emit logging events and I'm not fully convinced that they should all become `warnings.warn`.

For example, while reading a SWF file (a multi-image format), ImageIO will iterate over the contained images and may emit `"Ignoring JPEG image: cannot read JPEG."` because the current reader doesn't have a JPEG decoder. It can't decode those images, and this is useful information. At the same time, it's a problem the downstream application can't fix this on its end either. This makes it the intended candidate for a logging event instead of a warning [according to the python docs](https://docs.python.org/3/howto/logging.html#when-to-use-logging), and I currently agree with their general sentiment of when to use which:

> [warnings.warn()](https://docs.python.org/3/library/warnings.html#warnings.warn) in library code if the issue is avoidable and the client application should be modified to eliminate the warning
>[logging.warning()](https://docs.python.org/3/library/logging.html#logging.warning) if there is nothing the client application can do about the situation, but the event should still be noted

@moi90 What places did you have in mind specifically? Maybe those are places where ImageIO should warn instead of log. 

Another thing I'm wondering about is how this will make ignoring warnings easier. A generic `warnings.simplefilter("ignore")` will simply ignore all warnings, and may hide useful warnings such as deprecations or notifications of bad/outdated practice. The same is true for wrapping calls to ImageIO in `warnings.catch_warnings()`. We could introduce a custom warning class to allow more granular filtering, but that just seems like a custom and less intuitive copy of what logging already provides. 

@moi90 Could you elaborate on your thoughts here? Maybe I am missing something.

**Comment by FirefoxMetzger** [comment]
@moi90 This issue has been idle for a while. Is it still relevant for you?

**Comment by moi90** [comment]
Thanks for bringing up the python docs. I currently don't recall which warnings I encountered, but I assume that they fall under the "there is nothing the client application can do" category. I therefore close this issue.
