### ISSUE TITLE
Cannot write array of shape (H, W, 1) to JPEG image with v3 API

### ISSUE THREAD

**Issue by slanzmich** [imageio/imageio#842]
Switching from the v2 API to the v3 API, I noticed the following difference:

This works
```python
import numpy as np
import imageio

x = np.zeros((10, 30, 1), dtype=np.uint8)
imageio.v2.imwrite("test.jpg", x)
```
while the same with `imageio.v3.imwrite` fails with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kpkx626\AppData\Local\Programs\Python\Python38\lib\site-packages\imageio\v3.py", line 161, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "C:\Users\kpkx626\AppData\Local\Programs\Python\Python38\lib\site-packages\imageio\plugins\pillow.py", line 322, in write
    primary_image.save(self._request.get_file(), **save_args)
  File "C:\Users\kpkx626\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2305, in save
    save_handler = SAVE_ALL[format.upper()]
KeyError: 'JPEG'
```
This happens with Pillow 9.1.1 and 9.2.0 and Python 3.8.10 on Windows.

Is this considered an intended change, or should `PillowPlugin.write` squeeze out the third dimension?

**Comment by FirefoxMetzger** [comment]
Interesting find @slanzmich . When no mode is specified explicitly, ImageIO looks at the shape of the ndimage to try and work out if it is dealing with a single image or a batch of images:

https://github.com/imageio/imageio/blob/cd721d92fe096e6bb0ec82e5d0f2ed2fed44b06e/imageio/plugins/pillow.py#L289-L304

In your case, the image is treated as a batch of gray images with shape `(30, 1)`, because pillow only supports explicit color channels with 2, 3, or 4 dimensions. JPEG can't store batches of images, hence the exception. Unfortunately, even if we were to interpret the image "correctly", pillow would still fail to write the file, because `PIL.Ìmage.fromarray(x)` will complain about the trailing dimension (which doesn't represent any known colorspace).

> Is this considered an intended change, or should PillowPlugin.write squeeze out the third dimension?

This is a good question and I don't think I can give a definite answer. In many cases, the last dimension is a relic of some operation and it is okay to squeeze it away. This would remove some hassle for the user and we used to do it, so I get the idea for why we might want to bring it back.

At the same time, it might not always be the right thing to squeeze the last dimension, because - although rare - images with a single line exist, e.g., if you want to write out a colorpalette as a BMP or if you are working with a line scan camera. Here the last dimension might be `1` and we should provide a way to keep this.

Another argument against squeezing, and I think it is the main one, is that one would expect to be able to get an array back in the same way as it was stored when using a lossless format. However, squeezing internally breaks this equivalence, e.g. I can not do:

```python
import imageio as iio
import numpy as np

foo = np.random.default_rng().integers(0, 256, (50, 50, 1), dtype=np.uint8)
img_bytes = iio.v2.imwrite("<bytes>", foo, format=".png")
bar = iio.imread(img_bytes)
assert bar.shape == foo.shape
# AssertionError
```

We could bring it back by adding a `squeeze=False` kwarg to the writer to allow you to choose, but I feel like `iio.imwrite(x, ..., squeeze=False)` doesn't add much over `iio.imwrite(np.squeeze(x), ...)`.

I'm curious to hear your thoughts on this though :)

**Comment by slanzmich** [comment]
Thanks for the detailed reply! I'm completely ok with leaving this as it is, your arguments against squeezing sound reasonable. I agree that adding a `squeeze` argument would not add much value, callers can do that on their own. Maybe it is worth to add this to a migration guide to the v3 API, though.

I just wanted to confirm that this is an intended change and not a regression before changing our code that triggered this. But that's what I will do, then.

**Comment by FirefoxMetzger** [comment]
> Maybe it is worth to add this to a migration guide to the v3 API, though.

Good point. I'll see where in the docs this could live.

**Comment by slanzmich** [comment]
Another related thing I just noticed is that writing a TIFF image from an array of shape (256, 256, 3) writes multipage TIFF with 256 pages. (This uses the legacy tifffile plugin.)

To write an RGB image of shape (H, W, 3), I have to call `imageio.v3.imwrite` with an image of shape (1, H, W, 3), which I would expect to confuse some users. Writing an image of shape (3, H, W) creates a TIFF with three pages, which is again different. Maybe one should introduce the same special case
```python
if ndimage.ndim == 3 and ndimage.shape[-1] in [2, 3, 4]: ...
```
as above?

**Comment by FirefoxMetzger** [comment]
> Another related thing I just noticed is that writing a TIFF image from an array of shape (256, 256, 3) writes multipage TIFF with 256 pages. (This uses the legacy tifffile plugin.)

@slanzmich Oh? This sounds quite right. Could you make a new issue for this? `tifffile` is an entirely different plugin so it uses a different code path than what I shared above.

**Comment by slanzmich** [comment]
@FirefoxMetzger I created #849 to address the `tifffile` plugin issue.
