### ISSUE TITLE
imageio v3 cannot read metadata of tiff files it created itself

### ISSUE THREAD

**Issue by anntzer** [imageio/imageio#843]
```python
import imageio.v3 as iio, numpy as np; iio.imwrite("test.tiff", np.empty((10, 10, 3), "u1")); print(iio.immeta("test.tiff"))
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/imageio/v3.py", line 264, in immeta
    metadata = img_file.metadata(**call_kwargs)
  File "/usr/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py", line 308, in metadata
    raise ValueError(
ValueError: Legacy plugins don't support excluding applied metadata fields.
```
This is as of imageio 2.19.5.

**Comment by FirefoxMetzger** [comment]
what happens if you use `iio.immeta("test.tiff", exclude_applied=False)`?

**Comment by anntzer** [comment]
That works.

**Comment by FirefoxMetzger** [comment]
Yeah, we chose to have `exclude_applied=True` as the default value, because there are some metadata fields, like the famous EXIF rotation flag, that we apply to an image when loading (unless asked not to). When your read such an image and then inspect the metadata it is confusing to also find a `rotation` field in the metadata despite the image already being rotated. Hence we `exclude_applied` fields by default.

Then again, legacy plugins can't do this and will always return all fields that they find in the metadata. Currently, this raises an exception when used with the default settings of `iio.immeta`, which is far from ideal. 

That said, I'm not sure how a good fix looks like: Should we change the default until we have deprecated the legacy plugins? Should we ignore the field for legacy plugins and emit a warning instead? Should we change the error message to include `Try setting exclude_applied=False when reading metadata`? Ideas are welcome @anntzer :)

**Comment by anntzer** [comment]
Assuming that no legacy plugin ever has the ability to exclude applied metadata, I would just silently ignore `exclude_applied=True` for such plugins.
Asking people to explicitly `exclude_applied=True` is pretty bad for usability (if you're trying to write generic library code you'd basically end up having to always put `exclude_applied=True` as you can't know what format you'll get from your callers) and putting a warning is even worse (you basically have to make the catch_warnings dance).

**Comment by FirefoxMetzger** [comment]
@anntzer I've created a PR that will ignore `exclude_applied` for legacy plugins. 

I don't think it is a perfect solution, because now it can be surprising for the end-user to see that they get metadata they may not have expected to see, but I can see how it is the lesser of two evils. I will have a think if we can add something to the docs or if we should create a logging message for this.
