### ISSUE TITLE
Incomplete / misleading documentation for writing videos

### ISSUE THREAD

**Issue by estansifer** [imageio/imageio#859]
Last time I used imageio it had a clear interface and excellent documentation. After reading the [summary of the v3 api](https://imageio.readthedocs.io/en/stable/reference/core_v3.html) and the [migration instructions](https://imageio.readthedocs.io/en/stable/reference/userapi.html#migration-from-v2) I was left wondering: where did the detailed documentation go?

Examples of problems I ran into with the documentation:

* What does imageio.v3.imopen return? What operations does it support? What is the interface for the .write() function on the object returned by imopen?
* For example, the following code:
 
        with open('temp.mp4', 'w') as out:
            frame = np.zeros((160, 96, 3), dtype = 'uint8')
            out.write(frame) # etc. for more frames

failed, complaining that the the array needed to be 3D or 4D (which it is). The error message went away after installing imageio-ffmpeg. However, the resulting video files were corrupted anyhow.
* imageio.config is undocumented; I only know it exists from an aside in the imageio.v3.imopen documentation.
* The migration instructions say to replace get_writer() with imopen(). However, it is not a drop-in replacement, and there is no instruction on how to translate operations on the Writer object into operations on the latter.
* There is no example documentation for writing a video that is too large to fit in memory: all examples either use imwrite() or the v2 api.
* There is little discussion in the documentation about using the api to inspect, add, or specify plugins. Apparently plugins must be specified in all caps: 'ffmpeg' doesn't work.
* imopen() documentation says it accepts kwargs that will be passed to the plugin. The ffmpeg plugin says it accepts an 'fps' parameter. But imopen('temp.mp4', 'w', fps = 30) fails.

The best way I have found to write videos is something like:

    with iio.imopen('temp.mp4', 'w', plugin = 'FFMPEG') as out:
        out = out.legacy_get_writer(fps = 30) # note this function is deprecated
        frame = np.zeros((160, 96, 3), dtype = 'uint8')
        out.append_data(frame) # etc. for more frames

at which point one might as well just use the v2 api and not need to call imopen at all.

Note that append_data() was maybe 50x faster than the code at top using the v3 api function .write() and the resulting videos were not corrupted.

Maybe this list should be 8 different issues but I think they are all related to a central problem: It seems that the ability to write videos that are too large for memory, which the v2 api supported fine, was not finished being added to the v3 api, and the documentation does not communicate this.

Edit: Forgot to say, imageio 2.21.0, imageio-ffmpeg 0.4.7, python 3.10.6. Let me know if there is other information I can provide.

**Comment by FirefoxMetzger** [comment]
Thanks for the feedback @estansifer 

As with other open-source projects, we don't track how you use the library or collect statistics on existing use-cases. Since we don't have that data, the way we make improvements is by either having people give us direct feedback, by accepting contributions from others, by finding things while we use the library ourselves, or by outright guessing how people might be using the library. The documentation is no exception to this process, and you are very welcome to participate :D

I'm always happy to accept suggestions (or PRs ❤️) that improve ImageIO and its docs. If you see anything that could be made better, feel free to submit a PR and I am happy to review :) If you don't have time for a PR, suggestions are also more than welcome; however, keep in mind that they will remain suggestions until someone has the time to implement them.

---

To answer your actual questions:

> What does imageio.v3.imopen return? What operations does it support? What is the interface for the .write() function on the object returned by imopen?

`imopen` returns an instance of a [Plugin](https://imageio.readthedocs.io/en/stable/user_guide/overview.html#terminology) that wraps a [Backend](https://imageio.readthedocs.io/en/stable/user_guide/overview.html#terminology) and provides access to the backend's features. We didn't specify a return type, because the exact return type depends on the call signature of `imopen`, i.e., the exact API of a plugin (the operations it supports) is plugin-dependent. At a minimum, we require plugins to support the [v3 Plugin API](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.core.v3_plugin_api.PluginV3.html#imageio.core.v3_plugin_api.PluginV3), so those methods should always exist (and they do for the plugins that we provide).

> The migration instructions say to replace get_writer() with imopen(). However, it is not a drop-in replacement, and there is no instruction on how to translate operations on the Writer object into operations on the latter.

I am not sure what your question is, but my guess is that it relates to the above, i.e., what API is available on the object returned by `imopen`.

> There is no example documentation for writing a video that is too large to fit in memory: all examples either use imwrite() or the v2 API.

That's true; there is currently only one example that writes video and that uses the v2 API. Here is how I would go about writing  a large video with the v3 API (using our `pyav` plugin, which you can install via `pip install av`):

```python
import imageio.v3 as iio

# assume this is too large to keep in memory
source = "imageio:cockatoo.mp4"
dest = "foo.mp4"

with iio.imopen(source, "r", plugin="pyav") as in_file, iio.imopen(
    dest, "w", plugin="pyav"
) as out_file:
    for frame in in_file.iter(format="rgb24"):
        out_file.write(frame, codec="h264", is_batch=False)

```

> There is little discussion in the documentation about using the api to inspect, add, or specify plugins. Apparently plugins must be specified in all caps: 'ffmpeg' doesn't work.

Plugins must be specified using the name they are registered with. You can find the name to use by, for example, checking the plugins that support a [particular format](https://imageio.readthedocs.io/en/stable/formats/index.html#all-formats). I agree with you that ideally all plugin names should be lower case and match the name of the plugin/backend, but for backward compatibility the names of legacy plugins are kept as is and don't adhere to this convention.

Also yes, most of the features related to doing CRUD operations on plugins are currently undocumented. This was a feature that appears to not be in use (since I became a maintainer almost 2 years ago, we never got any issues related to this, nor did I ever hear about somebody using the feature), so we decided to "remove" it because it allows us to become more flexible and sophisticated in choosing the right plugin to use while also making our codebase cleaner. The v2 functions related to this raise a `DeprecationWarning` and ask that you open an issue if you need this feature, but so far there has been none.

> imopen() documentation says it accepts kwargs that will be passed to the plugin. The ffmpeg plugin says it accepts an 'fps' parameter. But imopen('temp.mp4', 'w', fps = 30) fails.

Both are correct. You need to differentiate between kwargs used to instantiate a plugin and kwargs used to write data via a plugin. `imopen` passes additional kwargs to the plugin's constructor, e.g., `imopen(..., plugin="pyav", container="mpeg")`. Kwargs that are used when writing should be passed to `write`, e.g., `file.write(..., fps=30)`.

We can probably improve the documentation of the FFmpeg plugin on this; if you would like to submit a PR that's greatly appreciated :)

> The best way I have found to write videos is something like: [...]

See my earlier comment on an example of how to write large videos using v3. 

There is a limitation with the ffmpeg plugin (compared to the pyav one) in that you currently can't write videos incrementally with it in v3 (it will replace the video each time you call `file.write()`). This is because of differences in the way legacy (v2) plugins and v3 plugins are designed and because I never found the time to look into fixing this for ffmpeg. That said, in v3 you have access to `pyav`, which is the preferred plugin for dealing with video and which will replace `imageio-ffmpeg` as the default once we reach feature parity (you are welcome to report missing features).

> It seems that the ability to write videos that are too large for memory, which the v2 api supported fine, was not finished being added to the v3 api, and the documentation does not communicate this.

It is possible to do this (see above :) ) and I agree that we should improve the documentation surrounding this. Would you like to make a suggestion on where to add this?

As a sidenote, you may also be interested in the discussion happening here: https://github.com/imageio/imageio/issues/841 https://github.com/imageio/imageio/pull/853 . The goal is to further improve on the ability to procedurally create/write videos (one use-case of this is large videos that don't fit in memory), and if you want to help shape this process, you are again welcome to do so.

**Comment by estansifer** [comment]
Thank you for your response, that resolves most of my questions.

> most of the features related to doing CRUD operations on plugins are currently undocumented

The two operations I care about are: the list of known plugins in my installation of imageio `imageio.config.known_plugins.keys()` and, given a writer or reader object what is the name of the plugin it is (I suggest `out_file.plugin_name` or some such).

> That said, in v3 you have access to pyav, which is the preferred plugin for dealing with video and which will replace imageio-ffmpeg as the default once we reach feature parity (you are welcome to report missing features).

That is very good information that probably should be mentioned somewhere, as ffmpeg is very well known and people will go towards it by default.

The one thing missing from pyav that I want is the ability to drop in ffmpeg command line options as is. However I think that would be more appropriate for a thin wrapper like imageio-ffmpeg, instead of a "semantically aware" wrapper like pyav. Thus I see both plugins as having their own potential uses even when pyav reaches feature parity.

**Comment by FirefoxMetzger** [comment]
> the list of known plugins in my installation of imageio

`imageio.config.known_plugins` contains a list of all plugins known to imageIO. Those plugins may or may not be actually installed on your system. For example, you may not have `pyav`/`av` installed, but you will still find `pyav` in the list of `known_plugins`. 

It is, unfortunately, not so easy to get a definite list of plugins that are actually present in your environment. You can get a mostly complete list by iterating over `imageio.config.known_plugins`, importing each plugin, and testing for an `ImportError`. This will cover all the plugins that are considered when searching for a plugin. You will still have to deal with plugins that we (ImageIO) don't know of and that are being used manually, i.e., those that are supplied directly via `iio.imread(..., plugin=MyPluginClass)`.

> given a writer or reader object what is the name of the plugin

If you have a plugin instance, you could figure out the name under which it is registered using a reverse lookup like so:

```python
[key for key, value in known_plugins.items() if value.class_name == foo.__class__.__name__][0]
```

That said, I'm not sure when this becomes useful to know. Could you describe your use-case?

> That is very good information that probably should be mentioned somewhere, as ffmpeg is very well known and people will go towards it by default.

I've added #865 which adds some examples and a note to the docs.

> The one thing missing from pyav that I want is the ability to drop in ffmpeg command line options as is. However I think that would be more appropriate for a thin wrapper like imageio-ffmpeg, instead of a "semantically aware" wrapper like pyav. Thus I see both plugins as having their own potential uses even when pyav reaches feature parity.

Unfortunately, this will be difficult to implement unless we reimplement FFPMEGs CLI. The main difference between `pyav` and `FFMPEG` is that FFMPEG calls the ffmpeg executable in a subprocess (hence the ability to provide CLI flags) whereas pyav directly binds to FFMPEGs C API, making it much (much) faster.

If you use a specific feature that the FFMPEG CLI provides and that isn't present in the pyav plugin please let us know; I'm happy to see if and how it might be included.

**Comment by estansifer** [comment]
> That said, I'm not sure when this becomes useful to know. Could you describe your use-case?

The use case is when I let imageio automatically select a plugin for opening a file, I would like to know what plugin was selected. For example, I detailed above that I was getting mysterious errors (complaining my data was not 3D even though it was) before I had updated my installation of imageio-ffmpeg; had I been able to see what plugin imageio had been using I might have realized sooner that FFMPEG was missing. Also, I still don't know what plugin it was using before I had FFMPEG, so I can't file a bug against it.

Another case where this might be useful is if I want to write a new file using the same plugin that imageio had selected for reading a file, but I don't know what plugin that'll be when writing the code.

> Unfortunately, this will be difficult to implement unless we reimplement FFPMEGs CLI. The main difference between `pyav` and `FFMPEG` is that FFMPEG calls the ffmpeg executable in a subprocess (hence the ability to provide CLI flags) whereas pyav directly binds to FFMPEGs C API, making it much (much) faster.

For me, a thin wrapper around the CLI is easier to use for many cases than a smarter wrapper. The reason is that pretty much the only way to learn how to use ffmpeg is from the documentation of the ffmpeg CLI. E.g., youtube posts instructions on how to encode videos with ffmpeg by giving explicit command line options. With FFMPEG I can then just plop those options directly into python and be done, but with pyav I have to first learn how to translate the CLI options I want into the corresponding features as pyav has exposed them. I'm not sure there's a way for a new user to learn what the more advanced encoding/etc. options do in pyav that doesn't involved learning the ffmpeg CLI along the way.

Therefore I see both plugins best for different purposes: FFMPEG for when your intent is specifically to use ffmpeg in a particular way with particular options, or pyav for sophisticated video tasks where it doesn't matter that the backend is ffmpeg in particular. Indeed I used pyav stand-alone about a month ago, not realizing it was an imageio plugin, so there are definitely tasks I prefer it for.

Github says my comment will close this issue, which is not my intent -- I just wanted to clarify the questions you brought up.

**Comment by FirefoxMetzger** [comment]
> The use case is when I let imageio automatically select a plugin for opening a file, I would like to know what plugin was selected. For example, I detailed above that I was getting mysterious errors (complaining my data was not 3D even though it was) before I had updated my installation of imageio-ffmpeg; had I been able to see what plugin imageio had been using I might have realized sooner that FFMPEG was missing. Also, I still don't know what plugin it was using before I had FFMPEG, so I can't file a bug against it.

If you want to use it for debugging, especially when looking at it interactively, you could use `type(plugin_instance)` where plugin_instance is the object returned by `imopen`. When filing bugs or searching for docs this is typically more useful, because it will tell you the name of the plugin rather than the name in the `known_plugin` registry. For legacy plugins (which are wrapped), you can inspect the `LegacyPlugin._format` attribute to see which format is being wrapped by the plugin.

> Another case where this might be useful is if I want to write a new file using the same plugin that imageio had selected for reading a file, but I don't know what plugin that'll be when writing the code.

This is the default behavior because plugin resolution is deterministic for a given format. If you don't specify a plugin and use the same runtime you will get the same plugin. This goes for both reading and writing and for the vast majority of formats. There are a few (more esoteric) formats where a plugin may only support reading, but for these, no other plugin that I know of supports writing so writing will fail regardless.

> For me, a thin wrapper around the CLI is easier to use for many cases than a smarter wrapper.

I think both plugins will continue to exist for quite a while, so `imageio-ffmpeg` won't disappear anytime soon. What will happen at some point is that the default changes and a call to read a MP4 without a specified plugin will pick pyav if it is present.

> Indeed I used pyav stand-alone about a month ago, not realizing it was an imageio plugin, so there are definitely tasks I prefer it for.

Pyav itself is an independent project. We simply maintain a wrapper around it (the plugin which is also referred to as pyav), which translates calls to the ImageIO v3 API into instructions for pyav to efficiently read/write video data.

**Comment by FirefoxMetzger** [comment]
I've added some examples on how to use pyav to the example collection. I've also added a note to the FFMPEG plugin that pyav exists and that it might be able to do things that FFMPEG can currently not do.

Since these were the two action items that I remember from our discussion, I've closed this issue in combination with the merge. If I've missed something, please do let me know. I will reopen and then we can see what else can be done to improve further :)
