### ISSUE TITLE
v2.21.0: LegacyPlugin.write() no longer preserves ndarray subclasses

### ISSUE THREAD

**Issue by RussTorres** [imageio/imageio#860]
Hello

This concerns  https://github.com/imageio/imageio/blob/27527d988c749403911c7fefa535cb1eb126591d/imageio/core/legacy_plugin_wrapper.py#L195-L198

Prior to v2.21.0, `np.asanyarray` was used to preserve ndarray subclasses (carrying e.g. image metadata to append_data) in this method.  `np.asarray` and `np.stack` here seem to result in ndarrays.  Is it possible to keep the previous behavior and preserve the subclass?

Thank you

**Comment by FirefoxMetzger** [comment]
Well spotted @RussTorres . Also sorry for the late response; I've been on vacation with limited internet access.I will see if we can bring back `np.asanyarray` for now. 

Over the long-term, however, I think we want a different solution for handling metadata when writing, because one of the things we are doing in V3 is that we are deprecating `imageio.util.Array` in favor if plain old `numpy.ndarray`s.

**Comment by FirefoxMetzger** [comment]
@RussTorres Would you happen to have a code example that uses this behavior that I can turn into a unit test to avoid regression?
