### ISSUE TITLE
How to know about "ndimage"? The return value of "imread".

### ISSUE THREAD

**Issue by cocoshe** [imageio/imageio#861]
I just can't find the "mode" or "pilmode" param in the doc, it seems should be exist. Where can I find it? I want to know the usage of the param, and it's default value, and the relationship between ".jpg  .png .gif..." and the return value of the imread function.

**Comment by FirefoxMetzger** [comment]
> I just can't find the "mode" or "pilmode" param in the doc, it seems should be exist. Where can I find it?

Assuming you are reading with our pillow plugin, you can find the documentation of `mode` [here](https://imageio.readthedocs.io/en/stable/_autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.read.html#imageio.plugins.pillow.PillowPlugin.read). If you are using the old (legacy) pillow plugin, then you'd use `pilmode` which is [documented here](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pillow_legacy.html#parameters-for-reading). Note that we are in the process of deprecating the old plugin in favor of the new one, so if you are writing new code, you should prefer the former (which is also the default in v3). Both `pilmode` in the old plugin and `mode` in the new plugin do the same thing.

In general, the kwargs accepted by a plugin are documented in the API docs of that particular plugin. This is because different plugins have different capabilities, so we can't always generalize/abstract them.

> [...] the relationship between ".jpg .png .gif..." and the return value of the imread function.

The returned ndimage is a `numpy.ndarray`. It's shape and dtype depend on the content of the file you are reading, so if your file stores a 800x600 RGBA image then you will get an ndarray with `shape=(600,300,4)` and `dtype=np.uint8`. If your data has 10bit depth then, where possible, you will get `dtype=np.uint16` (since that is the smallest numpy type that can represent 10-bit data). An exception to this rule are colorspaces that can not be represented by a single ndarray. For palette images (GIF and some PNG) we apply the palette and return the resulting RGB/RGBA image. For other colorspaces (eg YUV which is common for videos) we convert to RGB or raise an exception by default depending on the plugin's capabilities and common use-cases.

In the case of GIF and other multi-image formats you can control which image you want by using the `index` kwarg of imread. For GIF specifically, people usually want to read all the frames in the image, so by default we read all the frames in the GIF and provide a batch of frames (`(batch, height, width, channel)`), which you can also get specifically by using `index=...`.

Does that explain what to expect from imread? If not, could you specify the question a bit more?

**Comment by cocoshe** [comment]
> > I just can't find the "mode" or "pilmode" param in the doc, it seems should be exist. Where can I find it?
> 
> Assuming you are reading with our pillow plugin, you can find the documentation of `mode` [here](https://imageio.readthedocs.io/en/stable/_autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.read.html#imageio.plugins.pillow.PillowPlugin.read). If you are using the old (legacy) pillow plugin, then you'd use `pilmode` which is [documented here](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pillow_legacy.html#parameters-for-reading). Note that we are in the process of deprecating the old plugin in favor of the new one, so if you are writing new code, you should prefer the former (which is also the default in v3). Both `pilmode` in the old plugin and `mode` in the new plugin do the same thing.
> 
> In general, the kwargs accepted by a plugin are documented in the API docs of that particular plugin. This is because different plugins have different capabilities, so we can't always generalize/abstract them.
> 
> > [...] the relationship between ".jpg .png .gif..." and the return value of the imread function.
> 
> The returned ndimage is a `numpy.ndarray`. It's shape and dtype depend on the content of the file you are reading, so if your file stores a 800x600 RGBA image then you will get an ndarray with `shape=(600,300,4)` and `dtype=np.uint8`. If your data has 10bit depth then, where possible, you will get `dtype=np.uint16` (since that is the smallest numpy type that can represent 10-bit data). An exception to this rule are colorspaces that can not be represented by a single ndarray. For palette images (GIF and some PNG) we apply the palette and return the resulting RGB/RGBA image. For other colorspaces (eg YUV which is common for videos) we convert to RGB or raise an exception by default depending on the plugin's capabilities and common use-cases.
> 
> In the case of GIF and other multi-image formats you can control which image you want by using the `index` kwarg of imread. For GIF specifically, people usually want to read all the frames in the image, so by default we read all the frames in the GIF and provide a batch of frames (`(batch, height, width, channel)`), which you can also get specifically by using `index=...`.
> 
> Does that explain what to expect from imread? If not, could you specify the question a bit more?

The explanation is so clear! Thanks a lot for your patient answering! That really helps!

**Comment by FirefoxMetzger** [comment]
Happy to help :) If that answers the question, may I close the issue? (I try to keep things organized)

**Comment by cocoshe** [comment]
> Happy to help :) If that answers the question, may I close the issue? (I try to keep things organized)

OK~

**Comment by txmxthy** [comment]
Hi there, I am trying to combine gifs sequentially to animate some plots I have. I render the first set of gifs from pngs created by matplotlib and I want to reuse those gifs as blocks in different orders.  I.e. for each algorithm I have a gif for each dataset - I want to put them together as one gif for an alg across all datasets, and another for a dataset across each algorithm.

I write the gifs like this, 
```
def to_gif(images_dir, gif_path, filename):
    path = images_dir + "*.png"

    imgs = glob.glob(path)

    name = gif_path + filename

    # Ensure the files are ordered by name 
    costs = [int(img.split("\\")[-1].split("-")[0]) for img in imgs]

    imgs = sorted(imgs, key=lambda x: int(x.split("\\")[-1].split("-")[0]))

    kargs = {'fps': 10}

    with imageio.get_writer(name, mode='I', **kargs) as writer:
        for id in tqdm(imgs):
            image = imageio.v2.imread(id)
            writer.append_data(image)
```

and read them/merge them like this:
```
def merge_gifs(prefix, gifs, output_filename):
    # merge the gifs in list files to a single sequential gif
    # Create an empty list to store the frames of the output GIF
    print(f"Creating {output_filename} from {prefix}")
    kargs = {'fps': 10}
    with imageio.get_writer(prefix + output_filename, mode='I', **kargs) as writer:
        for gif_name in gifs:
            gif_path = prefix + "base\\" + gif_name
            # Load the frames of the GIF
            gif = imageio.v2.imread(gif_path, pilmode='I')
            # Append the frames to the lis
            writer.append_data(gif)

    print(f"Saved {prefix + output_filename}")

```
I am getting a lossy conversion error which leaves the merged gifs black and white, would you have any ideas on how to fix this? I'm not bound to v2 either, just used it because that's what I found first. 

I've included some example files, please ignore the poor formatting and all, its still wip!

<details>
  <summary>Example files</summary>
  
"Building Blocks"
![constraint_abz9](https://user-images.githubusercontent.com/50641082/210771328-a0f4aa17-4e97-453e-bfa3-3f13bad6d47b.gif)
![constraint_abz5](https://user-images.githubusercontent.com/50641082/210771334-100d8048-f099-4691-95e0-517610a5fbd4.gif)
![constraint_abz6](https://user-images.githubusercontent.com/50641082/210771337-6aa564a5-f789-451f-9b93-7bdf8b877054.gif)
![constraint_abz7](https://user-images.githubusercontent.com/50641082/210771339-761d7493-a0bc-4192-b6a0-c9db94e076be.gif)

Current output
![constraint_dataset_merged](https://user-images.githubusercontent.com/50641082/210771535-5d4df53f-777d-4a0a-9b72-249be960442f.gif)
  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>

Appreciate any help :)

**Comment by FirefoxMetzger** [comment]
@txmxthy You area using `pilmode="I"`, which means that you wish to write 32-bit grayscale pixels. This is why your result is grayscale (you explicitly request it). Further, GIF only supports 8-bit RGB (with some transparency support) hence you get a lossy conversion error when you go from 32-bit to 8-bit.

There is another problem in how you use `v2.imread` in `merge_gifs`. In v2, `imread` reads a single image, so you will only ever read the first image/frame of the gif, not the entire gif. In v2 you'd have to use `v2.mimread` - which gives you a list of images/frames - and then use a loop over the result to append frames individually.

Using v3 you can simplify your code and its defaults will do exactly what you want:

```python
import imageio.v3 as iio
import numpy as np

def merge_gifs(prefix, gifs, output_filename):
    # merge the gifs in list files to a single sequential gif
    # Create an empty list to store the frames of the output GIF

    print(f"Creating {output_filename} from {prefix}")
    gif_paths = [prefix + name for name in gifs]
    imgs = np.vstack([iio.imread(path) for path in gif_paths])

    # Note: loop=0 means loop forever
    # Note2: duration = 1/fps * 1000 (ie. gap between two frames in ms)
    iio.imwrite(prefix + output_filename, imgs, duration=100, loop=0)

    print(f"Saved {prefix + output_filename}")

# merge example gifs
# note: I downloaded your files and named them demo1.gif, demo2.gif, ...
merge_gifs("", [f"demo{idx+1}.gif" for idx in range(4)], "test.gif")
```

![test](https://user-images.githubusercontent.com/4402489/211002931-38a5cfad-040c-4967-8012-22bd4fc86bd7.gif)


> I'm not bound to v2 either, just used it because that's what I found first.

Where did you find the example if I may ask? I'm trying to find all the places that still use v2 and motion them to migrate to v3.
