### ISSUE TITLE
Passing `duration` or `fps` has no effect on the output GIF using PillowPlugin

### ISSUE THREAD

**Issue by ahuang11** [imageio/imageio#870]
```
import imageio.v3 as iio
import matplotlib.pyplot as plt

gif_path = "test.gif"
frames_path = "{i}.jpg"

n = 20
plt.figure(figsize=(4,4))
for x in range(n):
    plt.scatter(x/n, x/n)
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.savefig(f"{x}.jpg")

frames = np.stack(
    [iio.imread(f"{i}.jpg") for i in range(n)],
    axis=0
)

iio.imwrite(gif_path, frames, fps=1, loop=0)
```
I've tried `duration=1000` too

**Comment by FirefoxMetzger** [comment]
Interesting find. Here is a small test snippet that I created to see if I can replicate this issue:

```python
import imageio.v3 as iio

# v3 imread + PillowPlugin will read all frames in a GIF by default
frames = iio.imread("imageio:newtonscradle.gif")
iio.imwrite("test.gif", frames, duration=1000, loop=0)
```

which (on imageio v2.12.2) should produce the following GIF where each frame is shown for 1s:

![test](https://user-images.githubusercontent.com/4402489/187127027-9009ac5f-6310-4caf-835b-f10c0f33d130.gif)

For reference, GIF supports frames at a rate up to 100 Hz (though most tools like browsers cap out at 50 Hz) and `duration` is specified in `ms`. Hence a command like `duration=1` (which is 1/1000 or 1000 Hz) won't have any visual effect and it should indeed be `duration=1000`.

**Comment by ahuang11** [comment]
Oh, perhaps I got the duration mixed up when I tested in code (I thought `duration=1` is 1 second, but I typed it correctly in this issue.

However, `fps` is not working for me, unless I have that mixed up too.

**Comment by FirefoxMetzger** [comment]
No, I think you got that one right. The old pillow plugin added `fps` on top of pillow's native `duration`. I didn't port that addition into the new `PillowPlugin` because it is redundant. It is also more limiting because `duration` allows an iterable with one duration per frame whereas something like `fps=[1, 1/50, 1/25, 1/25]` seems a bit odd.

That said, I see how `fps` seems like the more intuitive keyword compared to `duration` so we could reintroduce it as a thin wrapper around (and coexistant with) `duration`. (Subject to resolving the above odd edge case) What do you think?

**Comment by ahuang11** [comment]
Oh, I honestly think `duration` is more useful too, but since it was listed in the Pillow docs, I thought it should have worked. Perhaps if `fps` is specified, could raise an error instead of supporting it since zen of python says there should only be one obvious way to do something?

**Comment by FirefoxMetzger** [comment]
> but since it was listed in the Pillow docs

Yes, it is part of the docs for the legacy plugin since we still have it here for backwards compatibility. You can force using it by setting `plugin="GIF-PIL"`. The docs for `PillowPlugin` shouldn't mention it and the other docs will get removed once we remove the old plugin (probably when we officially step into v3.0)

> Perhaps if fps is specified, could raise an error instead of supporting it 

I like this idea; lets do it :) Would you be interested in contributing a PR for it?

**Comment by FirefoxMetzger** [comment]
Of course I can. It would live in [`PillowPlugin.write`](https://github.com/imageio/imageio/blob/0c71a497c02e18523ff6117da5443ca6388e36a8/imageio/plugins/pillow.py#L229-L335). 

The way it works under the hood is that `imopen` selects the plugin, instantiates it, and returns it (a typical factory). `imwrite` calls `imopen` internally to figure out the plugin to use and then calls `plugin.write` to do the actual writing.

**Comment by ahuang11** [comment]
Thanks! I'll take a deeper look into it tomorrow

**Comment by ahuang11** [comment]
Made the PR #871. Let me know if there's anything I should change!
