### ISSUE TITLE
Reading webp image with an incorrect extension (.jpg)

### ISSUE THREAD

**Issue by smith1302** [imageio/imageio#875]
One of my projects requires me to read image URLs that may not have the correct extension for their data type.

Example:
[https://ae01.alicdn.com/kf/Hac2e53eec858443786614e07924c2f3aM/Women-Thick-Sole-Home-Slippers-4-5Cm-Heel-Ladies-Platform-Flat-Shoes-Non-Slip-Eva-Living.jpg](https://ae01.alicdn.com/kf/Hac2e53eec858443786614e07924c2f3aM/Women-Thick-Sole-Home-Slippers-4-5Cm-Heel-Ladies-Platform-Flat-Shoes-Non-Slip-Eva-Living.jpg)

This seems to be a webp image that is incorrectly named with a .jpg extension. This causes an issue when reading, even when using the WEBP format:

`imread(URL, format="WEBP-FI")`

Throws the error:

`RuntimeError: "WEBP-FI" can not handle the given uri.`

I'm not entirely sure why it can't handle the URI, but guessing it has something to do with the mismatched extension?

Without specifying a format i.e. `imread(URL)` this error is thrown:

`ValueError: Could not find a backend to open "https://ae01.alicdn.com/kf/Hac2e53eec858443786614e07924c2f3aM/Women-Thick-Sole-Home-Slippers-4-5Cm-Heel-Ladies-Platform-Flat-Shoes-Non-Slip-Eva-Living.jpg" with iomode "ri".`

Is there another way that I may have missed, possibly some config or error in my usage, that would allow me to read this image without having to download the image and convert it / rename it?

Thanks!

**Comment by FirefoxMetzger** [comment]
Hm. on the master branch the image reads fine for me using the v3 API:

```python
>>> import imageio.v3 as iio
>>> import matplotlib.pyplot as plt
>>> img = iio.imread("https://ae01.alicdn.com/kf/Hac2e53eec858443786614e07924c2f3aM/Women-Thick-Sole-Home-Slippers-4-5Cm-Heel-Ladies-Platform-Flat-Shoes-Non-Slip-Eva-Living.jpg")
>>> plt.imshow(img)
<matplotlib.image.AxesImage object at 0x000002158A528370>
>>> plt.show()
```

You could consider switching to v3 (generally recommended for new code as we are transitioning towards it).

**Comment by FirefoxMetzger** [comment]
To add some explanation on what is happening: The example image that you've shared is actually a JPEG and the extension is correct. You can inspect this, for example, by doing the following:

```python
import imageio.v3 as iio

# note: this is not a general solution and plugin dependent
with iio.imopen(url, "r") as file:
    print(type(file._image))
```

There are many ways to read JPEG. We use pillow by default, because it ships together with ImageIO and doesn't require additional setup. However, you can also use FreeImage if you really want to via:

```python
import imageio.v3 as iio

img = iio.imread(url)  # reads with pillow
img = iio.imread(url, plugin="pillow")  # reads with pillow
img = iio.imread(url, plugin="JPEG-FI")  # reads with freeimage
```

or in v2 (which will get deprecated over time):

```python
import imageio.v2 as iio

img = iio.imread(url)  # reads with JPEG-PIL
img = iio.imread(url, format="JPEG-PIL")  # reads with pillow
img = iio.imread(url, format="JPEG-FI")  # reads with FreeImage
```

---

If you do encounter an image with the wrong extension, then ImageIO v3 can often recover by itself. It tries to open the image as JPEG, fails, and then tries other backends to see if it can still make sense of the file. ImageIO v2 is a bit less flexible here, because decisions are typically made based on the extension, so if it is wrong you might not be able to read the file.

Further, if you know the extension is wrong (or missing), but you know the correct extension, you can set the extension explicitly in v3 via the `extension=` kwarg. This will act as a hint for the plugin selection and can reduce read times (less trial and error to find a suitable plugin):

```python
import imageio.v3 as iio

img = iio.imread(url, extension=".jpeg")  # or extension=".webp", etc.
```

**Comment by smith1302** [comment]
Thank you for your fast response! That was a very informative reply. I will upgrade to V3 and close this out.
