### ISSUE TITLE
imwrite to png bit depth depends on max value in array

### ISSUE THREAD

**Issue by tomas16** [imageio/imageio#881]
I have a 2D numpy array with dtype = np.uint16. If I write it to a PNG file using `iio.imwrite(outpath, img)`, then the resulting image has a bit depth of 8 if the max value is <= 255, and a bit depth of 16 if it's larger. If I force freeimage by doing `iio.imwrite(outpath, img, 'PNG-FI')`, the resulting image always has a bit depth of 16.

I'm working on some code that batch processes images and I was hoping to read each image, apply a user-supplied function to it, then write the result to a new image **in exactly the same format** as the input image. Because of above behavior, even if I simply read an image and write it back, it could flip from 16bpp to 8bpp. If I add 'PNG-FI', then now I'm specializing to PNG only.

Is there any way to do what I'm trying to do?

In general, it seems like a good idea to me that reading an image and writing it back should result in an image with the same bit depth etc.

Using imageio 2.19.3.

**Comment by tomas16** [comment]
I was testing this on version 2.9.0, then updated to 2.19.3 before opening this issue.
But now I discovered the v3 behavior is completely different. `v3.imread` now reads my 16bpp png's into numpy arrays with dtype int32, so I'm not even sure what the bit depth of the written files is.

**Comment by tomas16** [comment]
Using `v3.imwrite`, it looks like the uint16 dtype of the numpy array is respected when writing to a PNG file.
This behavior seems better. What's still missing is a way to determine the original bit depth stored in the PNG, so that even if imread always returns int32, that result can be cast to a different type (and crucially, written back using the same bit depth).

**Comment by FirefoxMetzger** [comment]
@tomas16 Do you have an example image that you can share? 16-bit depth should work fine for gray PNGs, but 16-bit RGB is not very widely supported. (afaik, neither pillow nor FreeImage support it)

That said, if you have 8-bit and 16-bit grayscale then you could differentiate them by inspecting the results dtype and checking if it is `np.uint8`:

```python
    rng = np.random.default_rng()

    img16 = rng.integers(2**8, 2**16, (128, 128), dtype=np.uint16)
    img16_bytes = iio.v3.imwrite("<bytes>", img16, extension=".png", plugin="pillow")
    img16_read = iio.v3.imread(img16_bytes)

    assert img16_read.dtype != np.uint8
    assert np.allclose(img16_read, img16)

    img8 = rng.integers(2**0, 2**8, (128, 128), dtype=np.uint8)
    img8_bytes = iio.v3.imwrite("<bytes>", img8, extension=".png", plugin="pillow")
    img8_read = iio.v3.imread(img8_bytes)

    assert img8_read.dtype == np.uint8
```

The behavior is like this because pillow (the default choice for PNG in v3) supports 8-bit grayscale (`mode="L"`) and 32-bit grayscale (`mode="I"`) but not 16-bit grayscale, so it uses the closest type that captures the full range of the image.

When writing a 32-bit image (that uses more than 8-bit effective depth) you should get a 16-bit PNG, because that is the limit of what the PNG spec supports, i.e, you can't actually produce 32-bit PNG images.

**Comment by tomas16** [comment]
Thanks, that makes sense.

**Comment by FirefoxMetzger** [comment]
I'm closing this issue because I think the question has been resolved. If I missed something, please comment and I will reopen.
