### ISSUE TITLE
When iterate over supported extenstions of imageio got ModuleNotFoundError

### ISSUE THREAD

**Issue by Czaki** [imageio/imageio#887]
In tests, when iterating over supported extensions of imagio it ends with `ModuleNotFoundError` exception.

As ffmpeg support is optional, if there is a lack of this dependency, it should end with not reporting support for such extension, not exception about the missed format. 

https://github.com/napari/superqt/actions/runs/3172165766/jobs/5166348387
```
 /opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
napari/_qt/__init__.py:54: in <module>
    from .qt_main_window import Window
napari/_qt/qt_main_window.py:56: in <module>
    from .qt_viewer import QtViewer
napari/_qt/qt_viewer.py:15: in <module>
    from napari_builtins.io import imsave_extensions
napari_builtins/io/__init__.py:1: in <module>
    from ._read import magic_imread, napari_get_reader
napari_builtins/io/_read.py:25: in <module>
    IMAGEIO_EXTENSIONS = {x for f in imageio.formats for x in f.extensions}
napari_builtins/io/_read.py:25: in <setcomp>
    IMAGEIO_EXTENSIONS = {x for f in imageio.formats for x in f.extensions}
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/imageio/core/format.py:640: in <genexpr>
    return iter(x.format for x in self._formats)
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/imageio/config/plugins.py:85: in format
    module = importlib.import_module(self.module_name, self.package_name)
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py:136: in <module>
    import imageio_ffmpeg
E   ModuleNotFoundError: No module named 'imageio_ffmpeg
```

**Comment by FirefoxMetzger** [comment]
Interesting find. Could you point me to the actual code that produces this exception?

**Comment by Czaki** [comment]
@FirefoxMetzger this line https://github.com/napari/napari/blob/3bf872cbb1df98665fdb7d5e0f3e1a4845a84202/napari_builtins/io/_read.py#L25

**Comment by FirefoxMetzger** [comment]
Ah, I see. You are using the legacy `FormatManager` to check for available plugins. I'll have a look and see if I can spot what is going on. 

In the meantime, note we are moving away from `FormatManager`, and once all plugins are ported to v3 the class will be deprecated and will disappear entirely (either in v3 or in v4). If you can tell me a bit more about why you are worried about the exact extensions available to/supported by the current session maybe I can suggest a better/alternative way of achieving that with ImageIO.

**Comment by Czaki** [comment]
> In the meantime, note we are moving away from `FormatManager`, and once all plugins are ported to v3 the class will be deprecated and will disappear entirely (either in v3 or in v4). If you can tell me a bit more about why you are worried about the exact extensions available to/supported by the current session maybe I can suggest a better/alternative way of achieving that with ImageIO.

To render the list of supported extensions in GUI.   
We also use extensions to determine the list of napari plugins capable to read the such file and allow users to select them from GUI.

**Comment by FirefoxMetzger** [comment]
@Czaki #888 should fix the issue. If you have time to leave a review (or check if it does) that would be appreciated :)

> To render the list of supported extensions in GUI.

Depending on what's installed that can be a [fairly long list](https://imageio.readthedocs.io/en/stable/formats/index.html), which makes me wonder if this is desirable from a UX standpoint. To brainstorm the problem a bit, could it be smoother to only show the 3-5 extensions that are commonly used by napari and to then have a "custom/other" option that allows the user to manually specify the extension?

> We also use extensions to determine the list of napari plugins capable to read the such file and allow users to select them from GUI.

Ah, yeah, I recognize this from inside ImageIO. It's one of the assumptions that I am working to get out of ImageIO, because I think it's an antipattern. Backends ultimately decide based on the file header whether they can or can not decode a file and, because of that, you introduce annoying corner cases when making hard decisions based on the file extension. For example, `large.png.part` can not be read (except that it can) or a PNG encoded `faulty_extension.jpg` will be seen as corrupt. Also `png_scans/image0XX` appears to be an arbitrary binary file that we can't make sense of.

The easier way (I think) is to hand the file to the backend/plugin and allow it to check if it recognizes the header. If yes, all good, if not, choose a different backend. We can use the extension to pre-order available backends, but making hard decisions on this causes problems. With ImageIO, one of the ways to do that would be:

```python
import imageio.v3 as iio

def iio_can_read():
    try:
        iio.immeta("my_file.asdf")
    except OSError:
        return False  # no backend can read it
    else:
        return True
```

For sane images (common format, and/or correct extension) this is fast because we just read metadata and don't decode pixels when using a modern (v3) plugin, so nothing changes compared to being purely extension-based. For not-so-sane images (missing/wrong extension) this may take a bit more time because more work is needed to find a suitable plugin; however, we significantly reduce the rate of false negatives and it's nice to be able to handle "problematic" images smoothly.

Also note that this approach provides a "catch all" for the scenario for when backends release updates and are now able to read more formats. In the extension-based scenario, we would have to recognize the improvement and add the extension to the list of supported extensions. Backends typically don't have a "list of all extensions we support" because extensions don't matter to them so we have to track commonly used ones manually. However, for the approach above it just works out-of-the-box.

**Comment by Czaki** [comment]
> Ah, yeah, I recognize this from inside ImageIO. It's one of the assumptions that I am working to get out of ImageIO, because I think it's an antipattern. Backends ultimately decide based on the file header whether they can or can not decode a file and, because of that, you introduce annoying corner cases when making hard decisions based on the file extension. For example, `large.png.part` can not be read (except that it can) or a PNG encoded `faulty_extension.jpg` will be seen as corrupt. Also `png_scans/image0XX` appears to be an arbitrary binary file that we can't make sense of.

We test if the selected reader fails, and if it happens, we suggest user to select another reader, but we limit the list of available readers based on file extension. It is not a good idea to use the imageio-based reader for a file that extension is not on the list of supported extensions. 

A list of supported extensions is also required to get a proper working "open file dialog".


> Depending on what's installed that can be a [fairly long list](https://imageio.readthedocs.io/en/stable/formats/index.html), which makes me wonder if this is desirable from a UX standpoint. To brainstorm the problem a bit, could it be smoother to only show the 3-5 extensions that are commonly used by napari and to then have a "custom/other" option that allows the user to manually specify the extension?

You are right. I just checked and this is one of the reasons, why our jobs on present tifffile extensions are stuck. So currently there is no presenting all supported extensions, but if there is more than one reader capable to read the file with such an extension then user selection for a given plugin is saved and used until reader fails to read some file.

**Comment by FirefoxMetzger** [comment]
I finished the PR to fix the issue and I've added your suggestions as well. Should roll out next Monday (during the next release).

---

> We test if the selected reader fails, and if it happens, we suggest user to select another reader, but we limit the list of available readers based on file extension.

So the full process is: Napari filters available readers based on the file's extension. Among these the user chooses a reader to use. If reading fails, the user is prompted to select the next reader until all readers are exhausted or the file was read successfully.

In that case there could be two options: Since readers are allowed to fail, you could inspect `imageio.config.known_extensions`, which is a dict of commonly used extensions, which formats they typically represent, and which ImageIO plugin can read them. You could use it like this:

```python
from imageio.config import known_extensions

def iio_can_read(extension):
    # at least one backend exists that can read a format
    # associated with this extension
    # (though this backend may not be installed)
    return extension in known_extensions
```

If you _need_ to be sure that the backend is actually installed and available in the current session you can check that, too. The process is, however, a bit more lengthy, because it involves importing the plugin and because I never came across a scenario where this seems like the optimal solution, so I never implemented a ready-made function for it.

```python
from imageio.config import known_plugins, known_extensions

def iio_can_read(extension):
    for format in known_extensions.get(extension, []):
        # more than one format may use the same extension
        for plugin_name in format.priority:
            # more than one backend may be able to read the format
            plugin_config = known_plugins[plugin_name]
            try:
                plugin_config.plugin_class()
            except ImportError:
                pass
            else:
                return True
    return False

```

As we discussed earlier, neither of these approaches will give you a definite yes/no on if ImageIO can actually read the file (because its impossible to say from the extension), but it might still be what you are looking for?

---

Also, I am beginning to feel that there is a bit of redundancy here. Napari maintains a set of plugins that can read files, among which there is ImageIO which maintains a set of plugins that can read files, among which is pillow which maintains a set of plugins which can read files... (ImageIO also has FreeImage, FFMPEG, and ITK plugins, which too are plugin-based)

Just a funny thought, but: Would it be useful to think if this could be simplified? Which plugins would we need to support so that you could deprecate your code in favor of ImageIO and so that we can avoid reinventing the wheel in different places?

**Comment by FirefoxMetzger** [comment]
I've merged the PR that closes this issue. @Czaki let me know if you still want to explore alternative solutions.

**Comment by Czaki** [comment]
The main problem was that imageio reads only the first frame of tiff, when using tifffile directly allow to read all planes. (I see that v3 handle tiff properly). 

But the core reason for a separate system now is handling file metadata in napari uniformly. A fast check shows that the metadata in imageio will not handle everything. 

Also, using own plugin system allows one to enable/disable the plugin reader/writer without installing/uninstall it. 

Maybe it will be possible to merge it in the future.

**Comment by FirefoxMetzger** [comment]
> But the core reason for a separate system now is handling file metadata in napari uniformly. A fast check shows that the metadata in imageio will not handle everything.

Which metadata fields are you concerned about? As you know, image file metadata is quite diverse, so handling that uniformly is not easy. That said, we currently have two ways of reading metadata. One is via [`immeta`](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v3.immeta.html#imageio.v3.immeta), which is format-specific, i.e., it gives you a dict with keys matching the names used by the format, and then there is [`improps`](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v3.improps.html#imageio.v3.improps), which is generic, i.e., it gives you a dataclass with standardized names at the expense of not reading all the fields that may exist on a file.

If you want, we could check if it is possible to standardize the fields you are interested in.

> Also, using own plugin system allows one to enable/disable the plugin reader/writer without installing/uninstall it.

I'm not sure I understand this point, you mean that you can dynamically load/unload plugins in the application?

**Comment by Czaki** [comment]
> I'm not sure I understand this point, you mean that you can dynamically load/unload plugins in the application?

Currently, we could disable/enable plugin (that require restart), but we are working on dynamically load/unload, even part of plugins (for example disable reader, but use widget). 

Using immeta in viewer requires building its own abstraction layers, which will not be much different from its own plugin system. 

Also, our system allows returning a list of layers (for example each channel in a separate array)

Some of the properties that are used by existing readers: colormap, contrast_limits, scale, translate, rotate, blending, visibility

**Comment by Czaki** [comment]
When we could expect a new release?

**Comment by FirefoxMetzger** [comment]
This should have been released last Monday, but the CD was halted because of a test failing, which I actually didn't notice. I've triggered a manual re-run so if that works the new release should be out in a few hours; otherwise on Monday :)
