### ISSUE TITLE
v3.imwrite to grayscale PNG of image with shape HWC does not work

### ISSUE THREAD

**Issue by hookxs** [imageio/imageio#904]
Numpy image of shape HWC with C==1 (grayscale) is not correctly saved to .png when calling imageio.imwrite (defaulting to pillow backend). I would swear this used to work in the (not so distant) past because I have results from some older code where these images are saved correctly. Now imageio just silently fails without throwing any error (as a result, I was using the code for some time after imageio update without noticing that the logged images are rubbish). Grayscale HW images work fine as expected. I don't know if this is intentional feature or a bug but I think that silent conversion from HW1 to HW would be much better than silent failure. Or even throwing an error would be better. I have imageio 2.22.0 and pillow 9.2.0.

**Comment by FirefoxMetzger** [comment]
That sounds really annoying. I can indeed reproduce this on master:

```python
import imageio.v3 as iio
import numpy as np

buffer = iio.imwrite("<bytes>", np.ones((128, 128, 1), dtype=np.uint8), extension=".png")
print(iio.improps(buffer).shape)
# prints (1, 128, 1)
```

This is definitely a bug and you should have gotten an exception. The image is recognized as a batch of images and, writing a PNG should fail and raise an exception since PNG doesn't support batches. We were relying on pillow to raise the exception here since their PNG writer doesn't support the kwarg to indicate batch writing; however, it looks like pillow just silently eats unknown kwargs without raising anything...

I will see what changes need to be made to handle this correctly and make a PR. 

Note, however, that the PR will simply add an exception. You still can't write a `(128, 128, 1)` image to PNG, even as a single image. This would lose the last dimension and, in other formats, we made the decision to raise an exception. This is more explicit compared to `np.squeeze`ing under the hood, which might surprise the user. I will do the same here.

**Comment by hookxs** [comment]
Thanks. I would think that silent conversion to HW would work but exception is fine of course if it's consistent with the rest of the library.

**Comment by FirefoxMetzger** [comment]
The reason for raising an exception is that you should be able to expect your data to be preserved; especially for lossless formats like PNG. This means that something like the following should work:

```python
import numpy as np
import imageio.v3 as iio

rng = np.random.default_rng()

source_img = rng.integers(0, 255, (128, 128, 3), dtype=np.uint8)
buffer = iio.imwrite("<bytes>", source_img, extension=".png")
read_img = iio.imread(buffer)

assert np.allclose(read_img, source_img)
```

However, if you silently squeeze a grayscale HWC image then the above would break because loading `buffer` would yield a grayscale HW image, which loses information about the trailing channel. If that is fine for your application then you can simply add `np.squeeze` before writing; however, if it is not then you have a silent failure ... which I try to avoid wherever possible.
