### ISSUE TITLE
Lower frame rate in webcam frame capture than OpenCV

### ISSUE THREAD

**Issue by yukw777** [imageio/imageio#908]
When I use imageio to capture webcam frames and save them as a video, its frame radio is noticeably lower (the video is choppier) than when I create a video from webcam frames captured using OpenCV. See below for minimal reproducible examples:

```python
# OpenCV
import cv2
import imageio.v3 as iio

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
cap.set(cv2.CAP_PROP_FPS, 30)

out_file = iio.imopen("test-cv2.mp4", "w", plugin="pyav")
out_file.init_video_stream("h264", fps=30)
for _ in range(30 * 5):
    _, frame = cap.read()
    out_file.write_frame(frame, pixel_format="bgr24")
out_file.close()
```
```python
# ImageIO
import imageio.v3 as iio

out_file = iio.imopen("test-imageio.mp4", "w", plugin="pyav")
out_file.init_video_stream("h264", fps=30)
for idx, frame in enumerate(
    iio.imiter("<video0>", input_params=["-video_size", "1920x1080"])
):
    out_file.write_frame(frame)
    if idx == 149:
        break
out_file.close()
```
You'll notice that `test-cv2.mp4` is a lot smoother than `test-imageio.mp4`. Why is this the case? Is `cv2.VideoCapture` simply faster b/c it's not run as a subprocess like `imageio` does with `ffmpeg`? I'm running the latest `imageio` and `imageio-ffmpeg`:
```
imageio==2.22.4
imageio-ffmpeg==0.4.7
```

**Comment by yukw777** [comment]
I also found this on StackOverflow: https://stackoverflow.com/questions/73753126/why-does-opencv-read-video-faster-than-ffmpeg. One notable comment:

```
If I change pix_fmt='bgr24' to pix_fmt='yuv420p' (and remove re-shaping of output for ffmpeg) the speed of ffmpeg is now slightly above OpenCV.
```

I tried to do this, but couldn't figure out a way to handle `yuv420p` correctly. Any advice? Would this really be the culprit?

```python
import imageio.v3 as iio

out_file = iio.imopen("test-imageio.mp4", "w", plugin="pyav")
out_file.init_video_stream("h264", fps=30)
for idx, frame in enumerate(
    iio.imiter(
        "<video0>",
        input_params=["-video_size", "1920x1080"],
        output_params=["-pix_fmt", "yuv420p"],
    )
):
    out_file.write_frame(frame.transpose((2, 0, 1)), pixel_format="yuv420p")
    if idx == 149:
        break
out_file.close()
```

**Comment by FirefoxMetzger** [comment]
> Is `cv2.VideoCapture` simply faster b/c it's not run as a subprocess like `imageio` does with `ffmpeg`?

Yes, that's the short version of it. Under the hood, imageio-ffmpeg spins up a python thread that continually receives data from stdout of a `subprocess.Popen` call. This data then gets converted into a numpy array that you then receive.

Unfortunately, there is no way this process can beat directly binding into the C libraries and passing a pointer around because it is just so much slower to do a full copy than to copy a single 64-bit int. This is especially true for HD images like the one you are using.

At some point in the future, we will be able to read webcams via the pyav backend as well. At this point, the performance of OpenCV and ImageIO should be much closer and both videos should be equally smooth.

>I tried to do this, but couldn't figure out a way to handle yuv420p correctly. Any advice? Would this really be the culprit?

This won't do you any good, because you will likely still have to convert YUV to RGB later on in your actual application because most image processing libraries in python assume that your image is 8-bit RGB. 

The issue with YUV420 specifically is that its U and V components are subsampled and because of that the image can't be represented by a contiguous ndarray (Y has a different shape than UV). This would break our convention to always return an image as an ndarray so we raise an exception.

---

A final word of caution about openCV: It's issue/problem reporting is not great. My webcam doesn't support 1280p (it's an old 720p one), so you can't actually capture `(1280, 1920)` images with it. It also doesn't do 30 FPS but rather 24 FPS. However, openCV happily accepts setting those parameters anyway and serves images. This is fine for visualizations, but if you want to do quantification on the image then you will get the wrong result because your image wasn't captured with the parameters you think they were.

**Comment by FirefoxMetzger** [comment]
That being said, if you want to have a go at implementing webcam support for `pyav` and address the performance difference, I'd be happy to help you and to review the PR :)

**Comment by yukw777** [comment]
I see. Thank you so much for a quick response! I'll see what I can do about implementing webcam support for `pyav`. Could you give me some pointers, e.g. which file to modify and relevant docs for `imageio` and `pyav`? I'll close this issue for now.

**Comment by FirefoxMetzger** [comment]
@yukw777 Sure thing. I think the best way to start is to create a new issue for this feature so that we have an obvious place to discuss this. Could you make one where you propose this feature?

As for how to go about implementing it, the bulk of the changes will be inside of `imageio/plugins/pyav.py` and the outline of the change is the following:

1. we have to check if the current `request` asks to open a webcam (this happens in init) and add a code-path that initializes the plugin correspondingly. This happens in `__init__` and you can get a more in-depth overview of a plugin's anatomy [here](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.core.v3_plugin_api.PluginV3.html#imageio.core.v3_plugin_api.PluginV3).
2. we have to instruct av to open the webcam. I can share more details in the separate thread, but on linux that means opening `/dev/videoX`, on Windows using [`dshow`](http://ffmpeg.org/ffmpeg-devices.html#dshow). On Mac I would have to look it up, because I don't own one.
3. we have to find a good way to drop frames from the buffer/queue since we may not start consuming frames immediately after we started the webcam. Also an IDE or notebook may take very long between two subsequent reads.
4. Perhaps add some extra plumbing to correctly handle metadata (`improps` and `immeta`).
5. Tests and documentation. ( I will contribute some of the work here)
