### ISSUE TITLE
Confused about `duration` kwarg for gifs

### ISSUE THREAD

**Issue by eigenvivek** [imageio/imageio#919]
I've generated GIFs using [this tutorial from the documentation](https://imageio.readthedocs.io/en/stable/examples.html#optimizing-a-gif-using-pygifsicle). However, when I try to set the `duration` kwarg to different values, all the videos are the same length. Are there some limits on the range of duration? Or any other way to speed up the GIF after the fact?

**Comment by FirefoxMetzger** [comment]
Not sure if this is the point of confusion but, `duration` sets the duration each frame should be shown in ms not the total duration of the GIF (the default backend for GIF is pillow and its relevant documentation for writing lives [here](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif-saving)). 

The shortest delay for GIF is 1/100 s or 10ms and other delays are multiples of that. In practice, however, most GIF readers cap out at 50 FPS (`duration=20`) and if they encounter any framerate (`duration`) they don't support they will fall back to a default duration; this is what common web browsers do anyway.

For your specific problem (optimizing with pygifsicle) there are two parts. The first part is writing with ImageIO and then you process the result with pygifsicle and generate a new file which may or may not preserve the duration that ImageIO has set. Can you check if the issue is ImageIO (imwrite) not changing the duration or if it is pygifsicle (optimize) changing the duration?

**Comment by eigenvivek** [comment]
Hi Sebastian, thank you very much for the reply. Lots of helpful information that I didn't know about GIFs.

> In practice, however, most GIF readers cap out at 50 FPS (duration=20) and if they encounter any framerate (duration) they don't support they will fall back to a default duration.

This is exactly what my browser did. GIFs with `duration<20` played back at a constant framerate, much slower than `duration=20`. This was true even when I removed the `pygifsicle` optimization (not sure how to check the intrinsic framerate of the GIF without opening it in browser though).

I was trying to visualize an optimization process that runs at 150 iterations / second. To animate it at the appropriate framerate, I will just subsample the frames. Thanks for teaching me about the min duration!

**Comment by FirefoxMetzger** [comment]
> not sure how to check the intrinsic framerate of the GIF without opening it in browser though

You can use ImageIO ❤️ 

```python
import imageio.v3 as iio
iio.immeta("imageio:newtonscradle.gif")
# {'version': b'GIF89a', 'background': 0, 'loop': 0, 'comment': b'File source: http://commons.wikimedia.org/wiki/File:Newtons_cradle_animation_book_2.gif', 'duration': 50, 'extension': (b'NETSCAPE2.0', 510), 'mode': 'P', 'shape': (200, 150), 'palette': <PIL.ImagePalette.ImagePalette object at 0x000001FD56D773A0>}
iio.immeta("imageio:newtonscradle.gif")["duration"]
# 50
```

This assumes a constant duration for all frames, but that is often true in practice. (Theoretically, you can set a per-frame duration, but good luck finding support for this, especially in browsers)

> I was trying to visualize an optimization process that runs at 150 iterations / second. To animate it at the appropriate framerate, I will just subsample the frames. Thanks for teaching me about the min duration!

You might want to look into [WEBP](https://developers.google.com/speed/webp), which is (almost) strictly superior to GIF, just less well known. Its browser support is almost as good as GIFs and its minimum delay between frames is 1/1000 s (`duration=1`), so it can (almost) handle 150 FPS sequences via `duration=6` or `duration=7`. 

You also get better compression (smaller files), a full 8-bit colorspace (no more 256 color limit), and the option to store lossless (at the expense of compression efficiency). I.e., all the perks you'd expect from switching from a format that was invented in the late 80s to something invented in 2010 😅 

ImageIO natively supports WEBP, so you should be able to do `iio.imwrite("fancy.webp", img)` and it should just work.

**Comment by eigenvivek** [comment]
Wow very cool! Using `immeta` confirms what you said: (1) the minimum `duration=10` for GIFs, (2) the input `duration` gets rounded down the the nearest multiple of 10 ms, and (3) my browser can't render a GIF with `duration<20` (it falls back to the default).

Very cool tip about WEBP format. The files are much smaller (176KB vs 2.1MB). Seems like I can use any integer duration value without rounding down. However, the smallest `duration` I can get get to play in the browser is 11 ms. Lower than that defaults to a slower, constant duration. (Might be a problem with my browsers, tried with Brave and Safari).

It also seems that `immeta` doesn't return a `duration` field for WEBP.
