### ISSUE TITLE
ValueError: Could not find a backend to open `video.ogv` with iomode `r?`.

### ISSUE THREAD

**Issue by ArtyomVancyan** [imageio/imageio#923]
I am trying to read a `.ogv` file with `imageio.get_reader`, and it raises this error.
### STDOUT
```text
Traceback (most recent call last):
  File "/home/artyom/Python/thumbnails/ffmpeg/__init__.py", line 8, in __init__
    self.reader = imageio.get_reader(filename)
  File "/home/artyom/anaconda3/lib/python3.9/site-packages/imageio/v2.py", line 159, in get_reader
    image_file = imopen(uri, "r" + mode, **imopen_args)
  File "/home/artyom/anaconda3/lib/python3.9/site-packages/imageio/core/imopen.py", line 298, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `valerian-1080p.ogv`` with iomode `r?`.
```

### PACKAGE VERSIONS
imageio==2.23.0
imageio-ffmpeg==0.4.7

**Comment by FirefoxMetzger** [comment]
OGG Vorbis should be supported by pyAV. imageio-ffmpeg should support this as well, but we might need to manually add the extension for this to work (due to how the legacy API works).

Do you have a snippet of code that reproduces the behavior?

**Comment by ArtyomVancyan** [comment]
> Do you have a snippet of code that reproduces the behavior?

No, I just debugged the `imopen`.

> imageio-ffmpeg should support this

It seems, it does not :)

**Comment by FirefoxMetzger** [comment]
I am asking because when I tried it locally, I could read and write OGV without issues:

```python
>>> import imageio.v3 as iio
>>> test_frames = iio.imread("imageio:newtonscradle.gif")
>>> iio.imwrite("test.ogv", test_frames, codec="libtheora")
>>> frames = iio.imread("test.ogv")
>>> frames.shape
(36, 150, 200, 3)
```

That said, I am using pyAV which is only available in the v3 API (`legacy_mode=False`), which is why I would need more context to better understand your situation and see what could/should be done about it. For this, a snippet that allows me to reproduce your behavior is always a good start.

**Comment by ArtyomVancyan** [comment]
Sure I have tried this before, and that works fine, but in my case, I want to read all formats of videos with a single function, unfortunately when reading another format of video such as `.mp4`, my computer memory leaks for some reason.

**Comment by FirefoxMetzger** [comment]
Interesting. Does the memory leak disappear when you set the legacy mode to `False`? 

Also, since your stack trace hints at you reading 1080p video, is it a memory leak in the sense that memory doesn't get freed correctly, or in the sense that you are running out of memory while loading the video? I'm asking, because uncompressed 1080p is quite greedy. For example, 32s of 1080p uncompressed at 30Hz will consume about 16GB.

**Comment by ArtyomVancyan** [comment]
No, it happens only when I am trying to read non-OGG formats using `imageio.v3.imread`.

**Comment by ArtyomVancyan** [comment]
By the way, the video I am testing with is short (about a minute and a half in length), and my computer's RAM is 32GM, which I think should be enough :)

**Comment by ArtyomVancyan** [comment]
The cause of the memory leak is the infinite iteration.

I am not an expert at file extensions, and content types, but some of the files I am working with are streams, and `reader.get_length()` returns `inf` for those, and I can't read the content as a `numpy.ndarray`.

**Comment by ArtyomVancyan** [comment]
The problem was [solved](https://github.com/pysnippet/thumbnails/blob/master/src/thumbnails/ffmpeg.py#L38) by parsing the metadata from the stdout.
