### ISSUE TITLE
PyAV: Avoiding the use of np.stack

### ISSUE THREAD

**Issue by hmaarrfk** [imageio/imageio#927]
https://github.com/imageio/imageio/blob/4658049bc37b6e89796233306df393d8a51b68bd/imageio/plugins/pyav.py#L597

Over the years, I've found that np.stack is pretty detrimental to performance. The reason is simple: one is copying memory around. That really hurts especially when you are doing video processing.

One might want to optimize these calls away.

You can likely "check for the same dimensions" with:

```
if any(f.shape != ndimage[0].shape for f in ndimage):
    raise ValueError("All frames should have the same shape")
```

In either case, this is a pretty minor for me since I don't use that codepath (yet) but I figured i would flag it as a potential contribution for new contributors.

**Comment by FirefoxMetzger** [comment]
Yes, this could be optimized. All we need here is to have the shapes match so that repeated calls to `self.write_frame` succeed. We could (potentially) even delegate this check upstream and let `self.write_frame` or pyav decide what to do.

In any case, I'll flag this as a good first issue as this is a fairly straight forward fix.
