### ISSUE TITLE
Undocumented difference reading 16-bit gray-scale PNG in v2 and v3 APIs

### ISSUE THREAD

**Issue by crisluengo** [imageio/imageio#931]
The v2 API used to read 16-bit gray-scale PNGs as uint16 arrays. The v3 API reads them in as int32 arrays. This makes no sense, data should be read in unaltered. For example, I have a workflow where gray values are interpreted differently depending on the data type range, which breaks with the change to the v3 API.

#881 mentions that this is because Pillow doesn't support 16-bit images (though that issue is related to writing, not reading):
> The behavior is like this because pillow (the default choice for PNG in v3) supports 8-bit grayscale (mode="L") and 32-bit grayscale (mode="I") but not 16-bit grayscale, so it uses the closest type that captures the full range of the image.

I need to mention here that 16-bit images are very common in many fields: scientific imagers usually have 12 or 16 bit ADCs, and yield 16-bit outputs. Not having a 16-bit mode is a strange choice for an imaging library.

This is a major change in functionality for imageio, not mentioned anywhere in the v2 to v3 transition guide. At the least I'd expect this to be documented. But IMO the best solution is to drop Pillow if it doesn't support 16-bit images.

[I'm sure there are workarounds, including changing the plugin used to read the file. This issue is not about finding a workaround.]

---

To reproduce:

```python
import numpy as np
import imageio.v2 as iio2
import imageio.v3 as iio3

img = rng.integers(2**12, size=(128, 128), dtype=np.uint16)
png_bytes = iio3.imwrite("<bytes>", img, extension=".png")
print(iio3.imread(png_bytes).dtype)
print(iio2.imread(png_bytes).dtype)
```
This shows `int32` for the v3 API and `uint16` for the v2 API.

**Comment by FirefoxMetzger** [comment]
> The v2 API used to read 16-bit gray-scale PNGs as uint16 arrays.

The v2 API returned a `np.uint16` image, yes, but it did not handle the image as `uint16` internally. Instead, it is converted before returning it to the user:

https://github.com/imageio/imageio/blob/c591a1c4ea20269382877110ce486c5bf84bd99d/imageio/plugins/pillow_legacy.py#L778-L781

> The v3 API reads them in as int32 arrays. This makes no sense, data should be read in unaltered.

Indeed, a (pure) IO library should keep modifications of the data to a minimum, which is why v3 returns the image to the user as-is without doing additional modifications e.g. no internal copy as we did in v2.

A 32-bit PNG does indeed not make sense, because the standard doesn't support it. If you know your data comes from PNG then it is safe to assume that the largest value is 16-bit and a subsequent `img.astype(np.uint16)` will not loose any information.

> https://github.com/imageio/imageio/issues/881 mentions that this is because Pillow doesn't support 16-bit images

You have misunderstood me here. Pillow fully supports reading PNGs in 1, 2, 4, 8, or 16-bit and in any supported color format (gray, RGB, palette, or with alpha). What it does not do is expose all these formats downstream. There is a limited number of [`modes`](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) that pillow supports (color-format + depth), most of which are 8-bit. 

The only mode with more than 8 bit depth that is fully supported is `mode="I"` which is 32-bit grayscale. Hence, 16-bit grayscale PNGs are loaded into a 32-bit buffer. There is partial support for a 16-bit grayscale mode called `mode="I;16"`, but it doesn't support conversions which limits its usability.

For example, you _can_ read 16-bit PNGs directly _if you know that they are 16-bit PNGs_:

```python
import imageio.v3 as iio
import numpy as np

img = iio.imread("imageio:chelsea.png", mode="I").astype(np.uint16)
encoded = iio.imwrite("<bytes>", img, extension=".png", mode="I;16")
decoded = iio.imread(encoded, mode="I;16") 
print(decoded.dtype)
# uint16
```

However, if you try and read an image that isn't stored as 16-bit grayscale using this approach you will get an exception because pillow doesn't know how to convert to 16-bit grayscale (hence limited support):

```python
img = iio.imread("imageio:chelsea.png", mode="I;16")  # stored as RGB
# ValueError: conversion from RGB to I;16 not supported
```

> This is a major change in functionality for imageio, not mentioned anywhere in the v2 to v3 transition guide. At the least I'd expect this to be documented. But IMO the best solution is to drop Pillow if it doesn't support 16-bit images.

This is again not entirely correct. The reading mechanic hasn't changed from before (v2 also used pillow to read 16-bit PNGs), but what did change is that we reduced the number of internal copies that happened before the data was forwarded to the user.

That said, I'm happy to add documentation of this change in behavior. Do you think the migration guide would be a good place for this info?

> [I'm sure there are workarounds, including changing the plugin used to read the file. This issue is not about finding a workaround.]

I see, then what would be a good way to resolve the issue for you?

**Comment by crisluengo** [comment]
> Indeed, a (pure) IO library should keep modifications of the data to a minimum, which is why v3 returns the image to the user as-is without doing additional modifications e.g. no internal copy as we did in v2.

This makes sense, let the plugin do what it does, and pass the data unchanged to the user. Leave it up to the user to choose the plugin that behaves as required.

> That said, I'm happy to add documentation of this change in behavior. Do you think the migration guide would be a good place for this info?

Yes, that is where I expected to find information about such changes.

After reading the guide, I expected to be able to use v3 without any change to my code, because the changes mentioned there didn't apply to what I was doing. So I was a little frustrated when things broke down. I looked through all of the documentation of the ImageIO API and the Pillow plugin, but didn't find any information about how data could have a different type than what's in the file.

> I see, then what would be a good way to resolve the issue for you?

Adding a note about this to the migration guide will hopefully make transition less frustrating to other people. There should probably also be a note in the documentation page for the Pillow plugin describing how the array returned is always either `uint8` or `int32`, depending on the file being read. For people familiar with Pillow this might be natural, but I use ImageIO so I don't need to learn about Pillow. ;)

---

By the way, this is unrelated, but the documentation to `imread` ([here](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v3.imread.html)) says that the function returns an `ndimage`, whereas it actually returns an `numpy.array`.
