### ISSUE TITLE
Preallocate result array in PyAVPlugin.read while bulk reading

### ISSUE THREAD

**Issue by hmaarrfk** [imageio/imageio#932]
as a followup to https://github.com/imageio/imageio/issues/927

The PyAV plugin read function uses stack. This is somewhat less than desirable.

What will happen is:

1. PyAV will create an internal frame
2. Reading a single frame will create a copy of the data (this is likely inevitable)
3. Once all the data has been collected, it will then be-recopied.

It would be good to:

1. Preallocate the data
2. Iterate through the frames. As we iterate, we copy the data from PyAV's frame to the buffer we created.

https://github.com/imageio/imageio/blob/c591a1c4ea20269382877110ce486c5bf84bd99d/imageio/plugins/pyav.py#L426

Mostly, I'm going through trying to integrate with this and writing some notes on findings.

**Comment by FirefoxMetzger** [comment]
Well spotted. We can add a fast-path for this if the number of frames inside the video is known in advance. I.e., we can (now) use `PyAVPlugin.properties().shape` to get the shape and allocate an appropriately sized array in advance and avoid the copy introduced by `np.stack`. This would be a nice addition and I'm happy to accept a PR for it 👍.

We will likely also have to provide a `out` argument to `PyAVPlugin.iter` to allow passing the view from `read` to `iter`. This would be nice to have as part of the public API anyway, because it allows optimizations like:

```python
with iio.imopen("imageio:cockatoo.mp4", "r", plugin="pyav") as file:
    props = file.properties()
    buffer = np.empty(props.shape, dtype=props.dtype)
    for _ in file.iter(out=buffer):
        pass  # do stuff with buffer
```
which avoids allocating a new array each frame.

At the same time, we also need to keep the path that uses `np.stack`, because this doesn't work in the general case. Ffmpeg may return a frame count of -1 for some videos whenever it can't figure out the number of frames in the video. In these cases, we need to fall back on the current implementation.


As a future step, it would be really awesome if we could hand that buffer upstream (to pyav) and avoid another copy. Another enhancement would then be to add `out`  to `PyAVPlugin.read`, which would allow users to preallocate the array.

Would you be interested in contributing something like this?
