### ISSUE TITLE
Writing metadata to video files with ffmpeg

### ISSUE THREAD

**Issue by GenevieveBuckley** [imageio/imageio#934]
I noticed that imageio produces an error *"The ffmpeg format does not support setting " "meta data."*. I am a little confused, given that it is possible to write metadata directly with ffmpeg, eg:
```
ffmpeg -i INPUT.mp4 -metadata title="My Amazing Title" OUTPUT.mp4
```

This is the part of the code where the error message is produced:

https://github.com/imageio/imageio/blob/c591a1c4ea20269382877110ce486c5bf84bd99d/imageio/plugins/ffmpeg.py#L597-L600

Does this error message just indicate that support is not currently implemented, or that it is not possible for technical reasons?

**Comment by GenevieveBuckley** [comment]
Please let me know if this question is better asked over at https://github.com/kkroening/ffmpeg-python

**Comment by FirefoxMetzger** [comment]
> Does this error message just indicate that support is not currently implemented, or that it is not possible for technical reasons?

It indicates that it is not currently implemented for our ffmpeg plugin. I suppose this is also related to the current capabilities of our [imageio-ffmpeg](https://github.com/imageio/imageio-ffmpeg) backend, i.e., FFMPEG can do it, imageio-ffmpeg can not, and therefore we can not either.

> Please let me know if this question is better asked over at https://github.com/kkroening/ffmpeg-python

No, this place is fine :)

---

That being said, we also have a pyav plugin, which interacts with video data using pyav and is (yet another) wrapper around ffmpeg. This one writes metadata just fine:

```python
>>> import imageio.v3 as iio 
>>> frames = iio.imread("imageio:cockatoo.mp4", plugin="pyav")
>>> with iio.imopen("test.mp4", "w", plugin="pyav") as file:
...      # Note: within an imopen context you may get access to a plugin-specific API
...      file.container_metadata["title"] = "My Amazing Title" 
...      file.write(frames, codec="libx264")
... 
```

You can install it using `pip install av` or `pip install imageio[pyav]`. It is also the preferable backend to use with video, because it has several advantages over the current ffmpeg plugin, e.g., faster reading, `iio.improps` without decoding pixel data, arbitrary* filter support, and more.

**Comment by GenevieveBuckley** [comment]
Thank you very much!

I'll discuss your pyav suggestion with our group. I'll check how large the pyav dependency is too, since that might be one potential objection to adopting it. Other than that possibility, it looks like a good strategy :)
