### ISSUE TITLE
Array returned from image.imread in 2.28 is not writeable anymore

### ISSUE THREAD

**Issue by phofl** [imageio/imageio#972]
The numpy array is set to read only:

```
from imageio import imread, imsave

fn = "image.png"
x = np.random.randint(0, 255, size=(5, 5)).astype("u1")
imsave(fn, x)
imread(fn).flags.writeable
```

This was writeable with 2.27

**Comment by mmatl** [comment]
We're experiencing this too. It's a breaking change.

**Comment by FirefoxMetzger** [comment]
@phofl Thanks for the report. https://github.com/imageio/imageio/pull/976 should address this.

In a nutshell, we can get a performance boost on some images if it is okay to return them read-only (e.g. because we can read uncompressed pixel data as raw `bytes` and can then build an array around these `bytes` instead of copying the `bytes` into an array.

Most numpy operations don't modify their inputs so I thought this would be the overall better default as it means a performance gain for most users. The exception are users that optimize their code by switching to in-place operations to avoid unneeded copies, and I figured that they, too, would appreciate copying explicitly instead of being forced to "eat" a copy when it is not needed.

Looking at this now, I think making a copy when needed to ensure a writable output is the better default. Especially since we can still give performance-conscious users the option to disable this behavior by passing a flag (`writeable_output=False`) to ImageIO.
