### ISSUE TITLE
BUG Using get_reader with pilmode leads to DeprecationWarnings

### ISSUE THREAD

**Issue by miriam-groeneveld** [imageio/imageio#991]
We were using the following code to load an image:

```
from imageio import get_reader         
with open("some_file", "rb") as f:   
  with get_reader(f, mode="i", as_gray=True) as r:
    return r.get_data(0)
```

From version 2.28.1 (or maybe earlier) this raises a TypeError: "The keyword `as_gray` is no longer supported. Use `mode='L'` instead."
As we are using the get_reader function, the only way to set this mode is using `pilmode`:

```
from imageio import get_reader         
with open("some_file", "rb") as f:   
  with get_reader(f, mode="i", pilmode="L") as r:
    return r.get_data(0)
```

This raises a Depracation Warning: `pilmode` is deprecated. Use `mode` instead.

Besides the DeprecationWarning, it also seems like the suggested alternative mode is not correct, or at least, does not result in the same data. 
In version 2.22.4:
`as_gray` returns data with type `float`. 
Mode `L` returns data with type `uint`. 
Mode `F` returns data with type `float` (From the `as_gray` [docs](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pillow_legacy.html) it seems it should be mode `F`)

**Comment by FirefoxMetzger** [comment]
Sorry for being slow with replying @miriam-groeneveld . I had an important presentation on Tuesday and preparing the slides took way more time than I anticipated 🥲 . I will respond more thoroughly after work tonight :)

**Comment by FirefoxMetzger** [comment]
First off, I'm a bit curious about why you ended up using such a convoluted way of reading the image. How come? I'm asking, because in `imageio.v3` your first code snippet could be replaced by a single line and I wonder what is preventing this refactor:

```python
import imageio.v3 as iio

#  # you can replace all of this
#  from imageio import get_reader         
#
#  with open("some_file", "rb") as f:   
#    with get_reader(f, mode="i", as_gray=True) as r:
#      return r.get_data(0)

# with a single line like this:
return iio.imread("some_file", index=0, mode="F")

```

(in v2, you could have chosen `imageio.v2.imread("some_file", as_gray=True)` if I remember correctly.)


Regarding `mode="L"` vs `mode="F"`, you are correct; we should remain backward compatible and recommend using `mode="F"`. At the same time, most users expect an integer-valued colorspace, so I guess we might actually wish to recommend both and point out that `F` is backwards compatible whereas `L` is often the more desirable one.

Regarding `pilmode` vs `mode` in v2 I have to take a closer look tomorrow into the best way forward. My current thinking is that we should check for the usage of `pilmode` in either the v2 API or the pillow plugin explicitly and substitute it when used via the v2 namespace. I will have to double check though that this won't have any other unwanted side-effects.

**Comment by miriam-groeneveld** [comment]
Thanks Sebastian!
